import { useCallback, useEffect, useRef, useState } from 'react'
import { CourseActivity } from './CourseActivity'
import {createDraft} from './activityState'
import { courseUnits, firstLessonTitle, lessonById } from './courseContent'
import { emptyRecord, mergeRecords, persistRecord, readRecord, skillEvidence, validateRecord, xpFor, type LearningRecord, type StorageResult } from './learningStore'
import { LearningRecordView } from './LearningRecord'
import { ReferencePanel } from './ReferencePanel'
import { skillNames } from './teachingProject'
import { Icon } from './Icon'
import './App.css'
import './learning.css'
const pathIds=courseUnits.flatMap((u,i)=>[...u.lessonIds,`unit-${i}`]).concat('final')
const titleFor=(id:string)=>id==='0.1'?firstLessonTitle:id==='final'?'Independent design review':id.startsWith('unit-')?`Unit ${Number(id.slice(5))+1} check`:lessonById[id]?.title??'Skill review'
function saveDownload(text:string,name:string){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function App(){
  const[initial]=useState(()=>{try{return readRecord(localStorage)}catch{return{record:emptyRecord(),status:{durable:false,error:'Device storage cannot be accessed. Export your work before closing.'}}}})
  const[record,setRecord]=useState<LearningRecord>(initial.record),[status,setStatus]=useState<StorageResult>(initial.status),[view,setView]=useState<'path'|'records'|'reviews'>('path'),[activity,setActivity]=useState<string>(),[reference,setReference]=useState(false),[importError,setImportError]=useState('')
  const latest=useRef(record),pathHeading=useRef<HTMLHeadingElement>(null),fileInput=useRef<HTMLInputElement>(null)
  const[recoveryRaw]=useState(()=>{if(!initial.status.error)return;try{return Object.fromEntries(['circuitlab.learning.v3','circuitlab.course.v2','circuitlab.lesson-0.1.v1'].map(key=>[key,localStorage.getItem(key)]).filter(([,value])=>value!==null))}catch{return undefined}})
  const unreadable=useRef(Boolean(initial.status.error))
  const update=useCallback((fn:(r:LearningRecord)=>LearningRecord)=>{const next=fn(latest.current);latest.current=next;setRecord(next);try{if(unreadable.current){const raw=localStorage.getItem('circuitlab.learning.v3');if(raw){const key='circuitlab.learning.v3.original-unreadable';if(localStorage.getItem(key)!==raw)localStorage.setItem(localStorage.getItem(key)?key+'.'+Date.now():key,raw)};unreadable.current=false}setStatus(persistRecord(localStorage,next))}catch{setStatus({durable:false,error:'Storage is unavailable. Work is held in this session; download a backup before closing.'})}},[])
  const backup=useCallback(()=>saveDownload(JSON.stringify(latest.current,null,2),`First-PCB-learning-${new Date().toISOString().slice(0,10)}.json`),[])
  function open(id:string){update(r=>({...r,drafts:{...r.drafts,[id]:createDraft(r,id)}}));setActivity(id)}
  useEffect(()=>{if(!activity&&view==='path')pathHeading.current?.focus()},[activity,view])
  useEffect(()=>{if(status.durable||!record.submissions.length&&!Object.keys(record.drafts).length)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=true};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[status.durable,record])
  const isDone=(id:string)=>Boolean(record.completions[id])
  const isReady=(id:string)=>{const index=pathIds.indexOf(id);return index===0||isDone(id)||isDone(pathIds[index-1])}
  const next=pathIds.find(id=>!isDone(id))??'final'
  const completed=courseUnits.flatMap(u=>u.lessonIds).filter(isDone).length
  const due=Object.keys(skillNames).filter(id=>skillEvidence(record,id).due||skillEvidence(record,id).needsPractice).length
  const legacy=Object.values(record.completions).filter(c=>c.legacy).length
  async function importFile(file?:File){if(!file)return;try{if(file.size>10*1024*1024)throw Error('This file is too large for a learning record.');const imported=validateRecord(JSON.parse(await file.text()));update(r=>mergeRecords(r,imported));setImportError('');setView('records')}catch(error){setImportError(error instanceof Error?error.message:'The backup could not be imported.')}finally{if(fileInput.current)fileInput.current.value=''}}
  if(activity)return <CourseActivity key={activity} activityId={activity} record={record} status={status} update={update} close={()=>{setActivity(undefined);setView('path')}} nextId={pathIds.indexOf(activity)>=0?pathIds[pathIds.indexOf(activity)+1]:undefined} openNext={open} backup={backup}/>
  const nav=<nav className="app-navigation" aria-label="Learning navigation"><button type="button" aria-current={view==='path'?'page':undefined} onClick={()=>setView('path')}><Icon name="book"/>Lesson path</button><button type="button" aria-current={view==='records'?'page':undefined} onClick={()=>setView('records')}><Icon name="check"/>Learning record</button><button type="button" aria-current={view==='reviews'?'page':undefined} onClick={()=>setView('reviews')}><Icon name="refresh"/>Review skills{due>0&&<span>{due}</span>}</button><button type="button" onClick={()=>setReference(true)}><Icon name="board"/>Project and reference</button></nav>
  const node=(id:string,ordinal:string,sway:number)=><li className={`trail-item sway-${sway}`} key={id}><span className="trail-line" aria-hidden="true"/><button className={`trail-node ${isReady(id)?'ready':'locked'} ${isDone(id)?'done':''}`} type="button" disabled={!isReady(id)} aria-label={`${titleFor(id)}. ${record.drafts[id]?'Resume activity':isDone(id)?'Review activity':isReady(id)?'Start activity':'Locked activity'}`} onClick={()=>open(id)}><Icon name={isDone(id)?'check':'arrow'} size={27}/></button><div className="trail-text"><small>{ordinal}</small><strong>{titleFor(id)}</strong><em>{record.drafts[id]?'Resume saved case':record.completions[id]?.legacy?'Earlier completion · new practice available':isDone(id)?'Recorded · notes in learning record':isReady(id)?'Ready to start':'Complete the previous activity'}</em></div></li>
  return <div className="app-grid"><aside className="left-rail"><div className="brand"><Icon name="board" size={26}/>First PCB</div><span className="mobile-xp">{xpFor(record)} XP</span>{nav}<p className="rail-note">Learn the decisions behind a PCB. CAD and physical work are optional and recorded separately.</p></aside>
    <div className="workspace-content"><div className="mobile-navigation">{nav}</div><div className="device-tools"><span>{status.durable?'Saved on this device':'Session only · backup needed'}</span><button type="button" onClick={backup}><Icon name="download" size={16}/>Download backup</button><button type="button" onClick={()=>fileInput.current?.click()}>Import backup</button><input ref={fileInput} hidden type="file" accept="application/json,.json" aria-label="Import learning backup" onChange={e=>void importFile(e.target.files?.[0])}/></div>
    {!status.durable&&<div className="storage-alert" role="alert"><p>{status.error}</p><button type="button" className="secondary-button" onClick={()=>update(r=>r)}>Retry saving</button></div>}{recoveryRaw&&Object.keys(recoveryRaw).length>0&&<div className="storage-alert"><p>An earlier record could not be read. Its original stored text is available for recovery separately from this session.</p><button type="button" onClick={()=>saveDownload(JSON.stringify(recoveryRaw,null,2),'First-PCB-original-record-recovery.json')}>Download original data</button></div>}{importError&&<p role="alert" className="storage-alert">{importError}</p>}
    {view==='path'?<main className="path-main"><header className="path-hero"><div><span className="kicker">YOUR FIRST PCB</span><h1 ref={pathHeading} tabIndex={-1}>Design, inspect and debug a PCB.</h1><p>Practice on a consistent LED project. Use calculations, diagrams and measurements to support your decisions.</p><progress className="native-progress" aria-label="Lessons recorded" max={56} value={completed}/><small>{completed} of 56 lessons recorded · {xpFor(record)} XP for participation</small></div><div className="hero-art" aria-hidden="true"><span className="art-chip"><Icon name="board" size={36}/></span><span className="art-led"/><span className="art-line a"/><span className="art-line b"/><span className="art-label">LED A</span></div></header>
      {legacy>0&&<p className="legacy-notice">{legacy} earlier activity records were preserved. New task skills need their own evidence; your old notes and attempts are in the learning record.</p>}
      {due>0&&<div className="review-banner"><div><strong>{due} skills have practice or review suggested</strong><p>Use a changed case to check what you can apply.</p></div><button type="button" className="secondary-button" onClick={()=>setView('reviews')}>Open reviews</button></div>}
      <div className="path-intro"><div><span className="kicker">THE COURSE PATH</span><h2>Continue learning</h2></div><span>10 units · 56 lessons · 11 checks</span></div>{courseUnits.map((unit,i)=><section className={`unit-section ${isReady(unit.lessonIds[0])?'':'future-unit'}`} key={unit.title} aria-labelledby={`unit-${i}`}><div className="unit-banner"><span className="unit-number">{String(i+1).padStart(2,'0')}</span><div><small>UNIT {i+1}</small><h3 id={`unit-${i}`}>{unit.title}</h3><p>{unit.lessonIds.length} lessons + changed-case check</p></div><b>{isDone(`unit-${i}`)?'RECORDED':isReady(unit.lessonIds[0])?'IN PROGRESS':'UP NEXT'}</b></div><ol className="trail-list">{unit.lessonIds.map((id,j)=>node(id,id,j%3))}{node(`unit-${i}`,'CHECK',unit.lessonIds.length%3)}</ol></section>)}<section className="unit-section"><div className="unit-banner"><span className="unit-number"><Icon name="target"/></span><div><small>COURSE FINISH</small><h3>Independent design review</h3><p>Six integrated tasks · physical work may remain pending</p></div></div><ol className="trail-list">{node('final','FINAL',1)}</ol></section></main>:<LearningRecordView record={record} open={open} reviewOnly={view==='reviews'}/>}
    </div><aside className="right-rail"><div className="profile"><span>FP</span><div><strong>Learning record</strong><small>{status.durable?'Saved on this device':'Held in this session'}</small></div></div><div className="xp-chip"><Icon name="target"/><strong>{xpFor(record)} XP</strong><span>Participation</span></div><div className="side-card"><small>COURSE PROGRESS</small><strong className="big-stat">{completed}<span> / 56</span></strong><p>Lessons recorded. Skill evidence is tracked separately.</p><progress className="native-progress" max={56} value={completed} aria-label="Course lesson progress"/></div><div className="side-card"><small>NEXT ACTIVITY</small><h3>{titleFor(next)}</h3><button type="button" className="side-link" onClick={()=>open(next)}>Open activity <Icon name="arrow"/></button></div><p className="source-note">Sources and assumptions accompany each task. Supplied measurements are simulations. Real parts and physical results need their own verification.</p></aside>{reference&&<ReferencePanel close={()=>setReference(false)}/>}</div>
}
