import type { StageVisualId } from './StageVisual'

export type SourceId = 'F1' | 'F2' | 'F3' | 'C1' | 'C2' | 'B1' | 'B2' | 'K2' | 'K3' | 'K4' | 'K5' | 'M1' | 'A1' | 'A2' | 'A3' | 'P1'
export const sources: Record<SourceId, { title: string; url: string }> = {
  F1: { title: 'OpenStax: Ohm’s law and simple circuits', url: 'https://openstax.org/books/college-physics-2e/pages/20-2-ohms-law-resistance-and-simple-circuits' },
  F2: { title: 'OpenStax: Series and parallel resistors', url: 'https://openstax.org/books/university-physics-volume-2/pages/10-2-resistors-in-series-and-parallel' },
  F3: { title: 'OpenStax: Electric power', url: 'https://openstax.org/books/college-physics-2e/pages/20-4-electric-power-and-energy' },
  C1: { title: 'Kingbright WP7113ID datasheet', url: 'https://www.kingbrightusa.com/images/catalog/SPEC/WP7113ID.pdf' },
  C2: { title: 'Energizer E91 AA datasheet', url: 'https://data.energizer.com/pdfs/e91.pdf' },
  B1: { title: 'Adafruit: Breadboards for beginners', url: 'https://learn.adafruit.com/breadboards-for-beginners/breadboards' },
  B2: { title: 'Energizer battery care', url: 'https://energizer.com/about-batteries/battery-care/' },
  K2: { title: 'KiCad: Getting started', url: 'https://docs.kicad.org/10.0/en/getting_started_in_kicad/getting_started_in_kicad.html' },
  K3: { title: 'KiCad: Schematic editor', url: 'https://docs.kicad.org/10.0/en/eeschema/eeschema.html' },
  K4: { title: 'KiCad: PCB editor', url: 'https://docs.kicad.org/10.0/en/pcbnew/pcbnew.html' },
  K5: { title: 'KiCad: GerbView', url: 'https://docs.kicad.org/10.0/en/gerbview/gerbview.html' },
  M1: { title: 'Adafruit: Multimeters', url: 'https://learn.adafruit.com/multimeters?view=all' },
  A1: { title: 'Adafruit: Soldering tools and safety', url: 'https://learn.adafruit.com/adafruit-guide-excellent-soldering' },
  A2: { title: 'Adafruit: Making a good solder joint', url: 'https://learn.adafruit.com/adafruit-guide-excellent-soldering/making-a-good-solder-joint' },
  A3: { title: 'Adafruit: Common soldering problems', url: 'https://learn.adafruit.com/adafruit-guide-excellent-soldering/common-problems' },
  P1: { title: 'JLCPCB: Fabrication capabilities', url: 'https://jlcpcb.com/capabilities/Capab' },
}

export type LessonContent = {
  id: string
  title: string
  learn: string
  prompt: string
  options: [string, string, string]
  correct: number
  why: string
  evidence: string
  sources: SourceId[]
  visual: StageVisualId
  work?: 'design' | 'bench'
  numeric?: { answer: number; unit: string; tolerance: number }
}

const lesson = (id: string, title: string, learn: string, prompt: string, options: [string, string, string], correct: number, why: string, evidence: string, sourceIds: SourceId[], visual: StageVisualId, work?: 'design' | 'bench'): LessonContent => ({ id, title, learn, prompt, options, correct, why, evidence, sources: sourceIds, visual, work })

export const courseUnits: { title: string; lessonIds: string[] }[] = [
  { title: 'Prepare the mission', lessonIds: ['0.1', '0.2', '0.3', '0.4'] },
  { title: 'Understand a circuit', lessonIds: ['1.1', '1.2', '1.3', '1.4', '1.5', '1.6'] },
  { title: 'Choose the parts', lessonIds: ['2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7'] },
  { title: 'Prototype and measure', lessonIds: ['3.1', '3.2', '3.3', '3.4', '3.5', '3.6'] },
  { title: 'Draw the schematic', lessonIds: ['4.1', '4.2', '4.3', '4.4', '4.5', '4.6'] },
  { title: 'Lay out the PCB', lessonIds: ['5.1', '5.2', '5.3', '5.4', '5.5', '5.6', '5.7', '5.8'] },
  { title: 'Prepare fabrication', lessonIds: ['6.1', '6.2', '6.3', '6.4'] },
  { title: 'Assemble and test', lessonIds: ['7.1', '7.2', '7.3', '7.4', '7.5', '7.6'] },
  { title: 'Debug with evidence', lessonIds: ['8.1', '8.2', '8.3', '8.4', '8.5'] },
  { title: 'Make one independent change', lessonIds: ['9.1', '9.2', '9.3', '9.4'] },
]

export const firstLessonTitle = 'From idea to tested PCB'

export const lessons: LessonContent[] = [
  lesson('0.2', 'Work safely', 'This course uses a small external holder with two alkaline AA cells. Keep cells out during wiring and continuity checks. A shorted battery can heat wiring or cells.', 'Which supply belongs in the first-board exercise?', ['A wall outlet', 'An unknown lithium pack', 'Two alkaline AA cells in an external holder'], 2, 'The planned course supply is the two-AA alkaline holder. Other supplies need separate design and safety work.', 'State the supply you will use and one reason to stop before power.', ['B2', 'C2'], 'schematic'),
  lesson('0.3', 'Know your tools', 'A meter checks voltage and unpowered continuity. A breadboard tests temporary connections. KiCad creates the schematic and board files; a soldering iron assembles the physical board.', 'What should you use to check the voltage between two points?', ['A multimeter set up for DC voltage', 'A Gerber viewer', 'A soldering iron'], 0, 'DC voltage is measured with a meter across two points. Check the meter’s jacks and mode first.', 'List the tools and parts you have, and note anything missing.', ['M1', 'B1', 'K2', 'A1'], 'tested'),
  lesson('0.4', 'Plan first power', 'Power is the final step after inspecting the build. With cells absent, check for shorts and polarity; then apply power and stop if anything heats, smells unusual, or behaves unexpectedly.', 'When should cells be inserted?', ['Before soldering so the LED can be watched', 'After an unpowered inspection and continuity check', 'During continuity mode'], 1, 'Inspect and check the unpowered board first. Never use continuity mode on a powered circuit.', 'Write your first-power sequence and stop conditions.', ['B2', 'M1'], 'tested'),

  lesson('1.1', 'Trace a closed loop', 'A simple circuit needs a closed conducting path from one battery terminal, through the load, and back to the other. An open switch interrupts that path.', 'The switch in a single series loop is open. What happens to the current?', ['It keeps flowing through air', 'The loop is broken and current stops', 'The battery voltage becomes zero'], 1, 'An open switch breaks the conducting loop. The battery can still have voltage across its terminals.', 'Trace a battery–switch–resistor–LED loop and mark where an open switch breaks it.', ['F1'], 'schematic'),
  lesson('1.2', 'Voltage and current', 'Current describes charge flow through a branch. Voltage is a difference in electric potential between two points. A voltmeter therefore compares two probe locations.', 'A voltage reading across a resistor uses how many circuit points?', ['One', 'Two', 'Every point on the board'], 1, 'Voltage is between two points. Current is associated with a branch or path.', 'Describe two probe points for measuring voltage across a resistor.', ['F1', 'M1'], 'schematic'),
  lesson('1.3', 'Units that matter', '1 ampere equals 1000 milliamperes; 1 kilo-ohm equals 1000 ohms. Write the unit on every value so the scale of a calculation remains visible.', 'How many amperes is 10 mA?', ['0.010 A', '10,000 A', '0.1 A'], 0, 'Divide milliamperes by 1000: 10 mA is 0.010 A.', 'Convert 2.2 kΩ to ohms and 0.015 A to milliamperes, with units.', ['F1'], 'schematic'),
  lesson('1.4', 'Change a resistor', 'For an ideal fixed voltage across an ohmic resistor, I = V/R. Increasing R reduces I. The LED itself is not an ohmic resistor, so this is a model of the resistor portion.', 'With the same voltage across a resistor, what does doubling its resistance do to current?', ['Doubles it', 'Halves it', 'Leaves it unchanged'], 1, 'I = V/R, so doubling R halves current when the voltage across it stays fixed.', 'Predict the direction of current change before trying a different resistor in a model.', ['F1'], 'schematic'),
  lesson('1.5', 'Use Ohm’s law', 'Use I = V/R for an ohmic resistor and keep units visible. Rearrange to V = IR or R = V/I only after identifying what is known.', 'A 100 Ω resistor has 2 V across it. What is its current?', ['0.02 A', '50 A', '200 A'], 0, '2 V / 100 Ω = 0.02 A, or 20 mA. This example concerns the resistor, not an LED.', 'Calculate the current through a 200 Ω resistor with 1 V across it.', ['F1'], 'schematic'),
  lesson('1.6', 'Series, open, and short', 'A series path carries the same current through each component. An open breaks it. A low-resistance bypass across a load can create a dangerous short path.', 'A wire directly connects the two battery terminals. What is the safe response?', ['Leave it connected to measure brightness', 'Remove power and correct the short', 'Increase the LED size'], 1, 'A direct battery short is a stop condition. Remove the cells before correcting wiring.', 'Sketch a series loop, an open, and a bypass; explain what changes.', ['F2', 'B2'], 'schematic'),

  lesson('2.1', 'LED direction', 'An LED conducts primarily in one direction and needs a current-limiting element in this course circuit. Check both the schematic symbol and the exact part’s physical polarity marks.', 'What must you check before installing the LED?', ['Only its color', 'Polarity and the exact package drawing', 'Whether the board has a logo'], 1, 'Symbol orientation and physical lead/pad orientation both matter. Use the manufacturer drawing for the selected LED.', 'Mark anode and cathode on a sketch of the planned LED and its schematic symbol.', ['C1'], 'schematic'),
  lesson('2.2', 'Read the datasheets', 'A datasheet number is meaningful only with its conditions. The candidate Kingbright LED lists 1.9 V typical and 2.3 V maximum forward voltage at 10 mA and 25 °C; the AA cell’s 1.5 V is nominal.', 'Which statement keeps the LED voltage condition intact?', ['Every LED is exactly 1.9 V', 'This LED’s stated values are specified at 10 mA and 25 °C', 'Two AA cells always measure exactly 3.000 V'], 1, 'The test current and temperature are part of the specification. Nominal battery voltage is not a fixed measurement.', 'Record the datasheet page and test conditions for one LED parameter and one battery parameter.', ['C1', 'C2'], 'files'),
  lesson('2.3', 'Set a current target', 'LED brightness and current involve a design tradeoff. Choose a modest target only after checking the chosen LED’s limits and testing visibility in the reference build.', 'What makes a current target defensible?', ['A remembered universal LED current', 'Datasheet limits plus the intended visibility and tested build', 'The largest number the battery can supply'], 1, 'A target is a design choice constrained by the part and intended use, then checked on hardware.', 'State a tentative target and what evidence you still need before approving it.', ['C1'], 'schematic'),
  lesson('2.4', 'Choose the resistor', 'Estimate resistor voltage from battery voltage minus LED forward voltage, then use R = V/I. Check a range of battery and LED conditions before selecting a real resistor.', 'Hypothetical model: a 3 V supply, 2 V across the LED, and a 5 mA target. What resistance in ohms does the model suggest?', ['200 Ω', '5 Ω', '600 Ω'], 0, '(3 V − 2 V) / 0.005 A = 200 Ω. The 2 V LED assumption is only for this exercise; a real choice needs range checks.', 'Work the hypothetical calculation with units, then list what actual part data remains to be verified.', ['F1', 'C1', 'C2'], 'schematic'),
  lesson('2.5', 'Check power and tolerance', 'For a resistor, P = IV or I²R. Compare the computed worst-case dissipation with the exact resistor’s rating and tolerance in its datasheet.', 'In a hypothetical case, a 200 Ω resistor carries 5 mA. What power does it dissipate in watts?', ['0.005 W', '1 W', '200 W'], 0, 'P = I²R = (0.005 A)² × 200 Ω = 0.005 W. The exact resistor rating and worst-case conditions still need checking.', 'Show the power calculation and cite the selected part’s rating, or mark the part unresolved.', ['F3'], 'schematic'),
  lesson('2.6', 'Switch and battery holder', 'The switch, holder, and connection must fit physically and connect the intended pins. A schematic symbol alone does not establish a footprint or polarity.', 'What should be checked before choosing a switch footprint?', ['Exact part pinout and mechanical dimensions', 'Only the switch color', 'Only the board outline'], 0, 'Use the exact switch drawing to confirm pin arrangement, operation, dimensions, and rating.', 'List the exact switch and holder part numbers or mark them unresolved.', ['K3', 'B2'], 'layout'),
  lesson('2.7', 'Review failure cases', 'A reversed LED, open switch, missing resistor, or short can produce different symptoms. Predict and choose a safe inspection or measurement before changing parts.', 'The LED is dark. What is the best first response?', ['Bridge the resistor', 'Remove power and inspect supply, polarity, and connections', 'Assume the LED is broken'], 1, 'Start with a safe check that can distinguish causes. Never bypass the current-limiting resistor.', 'Name two possible causes of a dark LED and a test that distinguishes them.', ['C1', 'B2', 'M1'], 'tested'),

  lesson('3.1', 'Breadboard connections', 'Breadboard rows and power rails connect internally, but rail breaks and layouts vary. Verify the specific board before inserting parts.', 'What should you check before trusting a long breadboard rail?', ['Whether it is split or continuous', 'Its plastic color', 'Whether it has a logo'], 0, 'Many boards have split rails. Inspect the markings or check continuity with power absent.', 'Sketch the connected groups on your own breadboard, or use a verified reference diagram.', ['B1', 'M1'], 'layout', 'bench'),
  lesson('3.2', 'Build the prototype', 'Build the approved low-voltage series circuit with cells absent. Compare each connection to the schematic before the first powered trial.', 'When should the cells be installed?', ['Before moving jumpers', 'After checking every connection and polarity', 'While using continuity mode'], 1, 'Make and inspect connections without cells. Power only after the pre-power checks.', 'Record your cell-free build inspection; label any unbuilt step as pending.', ['B2', 'M1'], 'tested', 'bench'),
  lesson('3.3', 'Measure voltage', 'A DC voltmeter reads a potential difference between two probes. Check the meter’s jack and mode, predict the sign, then measure across the intended two points.', 'Where do probes go for voltage across the battery holder?', ['Across its two terminals', 'Both on one terminal', 'In series by cutting a wire'], 0, 'Voltage is measured across two points. Follow the manual for your particular meter.', 'Record meter model, jack/mode, probe points, and observed or expected reading.', ['M1'], 'tested', 'bench'),
  lesson('3.4', 'Infer current', 'Instead of moving a lead to a current jack, measure voltage across the known series resistor and calculate I = V/R. Never put a meter in current mode directly across a battery.', 'You measured 1 V across a known 200 Ω resistor. What is the inferred current?', ['5 mA', '200 A', '200 mA'], 0, '1 V / 200 Ω = 0.005 A = 5 mA. This assumes the resistor value is known.', 'Record resistor value, resistor voltage, and inferred current with units.', ['F1', 'M1'], 'tested', 'bench'),
  lesson('3.5', 'Compare results', 'Compare actual supply and component voltages with predictions. Differences may come from supply state, component spread, measurement, or wiring; do not force an exact nominal result.', 'A reading differs from a nominal prediction. What should you do first?', ['Declare the board failed', 'Check the measured supply, component values, and probe points', 'Change a resistor at random'], 1, 'Reconcile observations with assumptions before changing the design.', 'Write a predicted/observed table and one evidence-based explanation, or mark measurement pending.', ['C1', 'C2', 'F1'], 'tested', 'bench'),
  lesson('3.6', 'Find a wiring fault', 'A dark LED can result from an open rail, reversed LED, wrong resistor, or absent supply. Choose a measurement that separates likely causes.', 'The battery reads normally but a breadboard rail may be split. What is a useful next check with cells removed?', ['Continuity across the suspected rail break', 'Current mode across the battery', 'Randomly replace every part'], 0, 'An unpowered continuity check can reveal whether that rail segment is connected.', 'Record a suspected fault, distinguishing test, observation, and correction.', ['B1', 'M1', 'C1'], 'tested', 'bench'),

  lesson('4.1', 'Create a KiCad project', 'A KiCad project keeps the schematic and board together. Save it in a named folder and note the KiCad version used.', 'Which file is the circuit connection drawing?', ['The schematic', 'The Gerber drill file', 'The 3D model only'], 0, 'The schematic records parts and their electrical connections. The board file records physical placement and copper.', 'Record your project folder and KiCad version, or mark installation pending.', ['K2'], 'schematic', 'design'),
  lesson('4.2', 'Choose symbols', 'Choose schematic symbols for the exact planned parts, then compare pin numbers and meaning with the manufacturer drawings.', 'Does a matching symbol name prove the real part pinout?', ['Yes, always', 'No; inspect its pins against the exact part', 'Only if ERC passes'], 1, 'A symbol represents connectivity; the exact part pinout must still be verified.', 'List each part and the symbol used, noting any unresolved pin mapping.', ['K3'], 'schematic', 'design'),
  lesson('4.3', 'Wire the nets', 'Join the intended pins and inspect junction dots and highlighted nets. Crossing lines without the intended junction can leave nets separate.', 'Two wires cross without a junction. What should you verify?', ['That KiCad treats them as the intended connected or separate nets', 'Only that the drawing is neat', 'That the board is green'], 0, 'Visual proximity is not proof of electrical connectivity. Highlight each net.', 'Trace supply to return and name the nets in your schematic.', ['K3'], 'schematic', 'design'),
  lesson('4.4', 'Assign footprints', 'A footprint maps schematic pins to real pads and holes. Compare pin numbering, pitch, hole size, and body outline with each exact component.', 'What is the strongest footprint check?', ['Matching the part’s datasheet drawing and pin numbers', 'A similar-looking 3D image alone', 'A clean ERC alone'], 0, 'Physical dimensions and pin mapping must match the actual part.', 'Record a footprint-to-part table and mark any part without an exact match.', ['K3', 'K4'], 'layout', 'design'),
  lesson('4.5', 'Run ERC', 'Electrical Rules Check catches configured connection problems and unconnected pins. It cannot prove that a functioning circuit was designed.', 'ERC reports no errors. What remains necessary?', ['A separate logic, polarity, and rating review', 'Nothing; the circuit must work', 'Only changing the theme'], 0, 'KiCad explicitly limits what ERC can establish. Review the circuit intent yourself.', 'Record ERC findings and how you resolved or documented each one.', ['K2', 'K3'], 'schematic', 'design'),
  lesson('4.6', 'Review the schematic', 'Follow the intended loop without relying on ERC: supply, switch, resistor, LED polarity, return, part values, and ratings.', 'Which review can catch an LED drawn backward even if rules pass?', ['A human trace of the intended circuit and polarity', 'An unrelated file rename', 'Only a board color change'], 0, 'A logical review checks meaning that an electrical rule checker may not know.', 'Write the net-by-net review result and any unresolved item.', ['K2', 'C1'], 'schematic', 'design'),

  lesson('5.1', 'Read board layers', 'Copper carries connections, solder mask covers most copper, and silkscreen provides markings. Through-hole pads may connect on both copper sides.', 'Which layer carries routed electrical traces?', ['Copper', 'Silkscreen', 'The project title'], 0, 'Electrical routes are copper. Silkscreen is printed marking, not a conductor.', 'Label copper, mask, silkscreen, holes, and edge outline on a board view.', ['K4'], 'layout', 'design'),
  lesson('5.2', 'Check footprints', 'Use exact part drawings and, when possible, a printed 1:1 footprint check. Inspect pad numbering, drill, lead spacing, and polarity.', 'A 3D model looks similar. What check is still needed?', ['Exact dimensions, drills, and pin mapping', 'Only a different board color', 'None'], 0, 'A visual resemblance cannot establish mechanical or electrical fit.', 'Record the exact part and footprint dimensions you checked.', ['K4'], 'layout', 'design'),
  lesson('5.3', 'Set fabrication rules', 'Read the chosen fabricator’s current capabilities and enter appropriate project rules before routing. Capability minimums are not automatic design targets.', 'When should width, spacing, and drill rules be chosen?', ['Before layout decisions are finalized', 'Only after ordering', 'After assembly'], 0, 'Set rules before routing so checks reflect the intended manufacturer.', 'Record vendor, date, rule source, and the conservative values selected.', ['K4', 'P1'], 'layout', 'design'),
  lesson('5.4', 'Place parts', 'Place parts so the switch can be reached, LED can be seen, battery polarity is legible, and parts can be hand assembled.', 'What is a useful placement review?', ['Check access, orientation, and assembly clearance', 'Only minimize empty space', 'Only align every label'], 0, 'The board must be usable and buildable, not merely pass routing checks.', 'Describe one placement decision and its use or assembly reason.', ['K4'], 'layout', 'design'),
  lesson('5.5', 'Route copper', 'Route each schematic net to the matching pads. A remaining ratsnest line signals an unrouted connection, even if copper appears close.', 'What does an unrouted connection require?', ['A real connection on the correct net or a deliberate design correction', 'A decorative silkscreen line', 'Ignoring it if the board looks complete'], 0, 'Follow net highlighting and the unrouted count until each intended connection is complete.', 'Record the unrouted count and trace at least one full net.', ['K4'], 'layout', 'design'),
  lesson('5.6', 'Outline and markings', 'A closed board outline defines the manufactured edge. Add readable polarity and switch-state markings, then inspect the design at actual scale.', 'Which item defines the board edge for fabrication?', ['A closed outline on the correct edge layer', 'A screenshot border', 'A component courtyard'], 0, 'The manufacturing outline must be a closed shape in the board data.', 'Record board dimensions and inspect the outline and markings.', ['K4'], 'layout', 'design'),
  lesson('5.7', 'Run DRC', 'Design Rules Check tests the configured board rules and connectivity. Run schematic parity as part of the review; inspect every violation.', 'A clean DRC proves what?', ['Configured checks pass for this board state', 'The exact parts must fit and the circuit must work', 'The physical solder joints are good'], 0, 'DRC is essential but only checks what it knows and what was configured.', 'Record rules/version, DRC result, parity result, and any documented exceptions.', ['K4'], 'layout', 'design'),
  lesson('5.8', 'Review the board', 'Independently compare every net and footprint with the schematic and exact parts. Check polarity, edges, access, labels, and assembly.', 'What can a human review catch after clean DRC?', ['A wrong but electrically connected LED orientation or footprint', 'A missing click sound', 'Only spelling in the project name'], 0, 'Electrical and mechanical intent require checks beyond the rule engine.', 'Record the board review checklist and unresolved issues.', ['K4', 'C1'], 'layout', 'design'),

  lesson('6.1', 'Generate files', 'Export copper, mask, silkscreen, outline, and Excellon drill data from the same approved board revision. Keep outputs together.', 'Which output records drill locations?', ['Excellon drill file', 'A schematic screenshot', 'A lesson score'], 0, 'The drill output describes hole locations and sizes for manufacturing.', 'Record board revision and the files generated.', ['K2', 'K4'], 'files', 'design'),
  lesson('6.2', 'Inspect Gerbers', 'Open exported files in GerbView. Inspect copper, mask, outline, markings, and drill alignment independently from the PCB editor.', 'Why inspect exported files?', ['To catch missing or misaligned manufacturing layers', 'Because ERC verifies solder quality', 'Only to change colors'], 0, 'Inspection catches export and layer mistakes before an order.', 'Record a layer-by-layer and drill review, including any missing file.', ['K5'], 'files', 'design'),
  lesson('6.3', 'Prepare the order', 'Compare the fabricator preview with your board and recheck current options, price, shipping, and exact part availability. Do not order until the release review passes.', 'A vendor preview differs from GerbView. What next?', ['Stop and resolve the mismatch', 'Order and hope it is cosmetic', 'Discard the schematic'], 0, 'A preview mismatch is a release blocker until explained.', 'Record the vendor preview check and bill of materials status; keep payment outside the app.', ['P1', 'K5'], 'files', 'design'),
  lesson('6.4', 'Release the design', 'Freeze a matching revision of schematic, board, checks, Gerbers, drills, and bill of materials before spending money.', 'Which set is order-ready?', ['Matching reviewed files and resolved checks', 'Any files with familiar names', 'Only the latest screenshot'], 0, 'The package must be coherent and independently inspected.', 'Record the release revision and each signed-off check, or mark release blocked.', ['K4', 'K5', 'P1'], 'files', 'design'),

  lesson('7.1', 'Inspect the bare board', 'Compare the received board with the approved output: outline, holes, pads, mask, silkscreen, and visible defects. Keep cells away.', 'A required drill hole is missing. What should you do?', ['Stop assembly and compare with the approved files', 'Force the component through copper', 'Power the board first'], 0, 'A mismatch should be investigated before assembly.', 'Record what you inspected on the received board, or mark it not yet received.', ['K5'], 'bare', 'bench'),
  lesson('7.2', 'Prepare to solder', 'Set up a stable iron stand, ventilation, eye protection, and a clear workspace. Practice a joint on scrap before the real board.', 'Where should a hot iron rest?', ['In its stable stand', 'On the battery holder', 'On loose paper'], 0, 'Use a stable stand and follow your tool and solder instructions.', 'Record the setup and practice-joint observation, or mark equipment pending.', ['A1'], 'tested', 'bench'),
  lesson('7.3', 'Install the parts', 'Install and verify each exact part’s orientation before soldering. Keep cells out and follow component soldering limits.', 'What should be checked before soldering a polarized LED?', ['Its anode/cathode orientation against the board and datasheet', 'Only the LED color', 'Whether the board looks full'], 0, 'A reversed LED can leave the board dark; check the exact part drawing and board marks.', 'Record part orientation and assembly sequence, or mark assembly pending.', ['A2', 'C1'], 'tested', 'bench'),
  lesson('7.4', 'Inspect joints', 'A good-looking photo is a clue, not proof. Inspect for bridges, dull or disturbed joints, incomplete wetting, and damaged pads; follow with electrical checks.', 'You see solder joining adjacent pads unintentionally. What next?', ['Remove power and repair the bridge', 'Ignore it if the LED glows', 'Add more solder'], 0, 'An unintended bridge can short nets. Correct it with the board unpowered, then inspect again.', 'Record any joint concern, repair, and electrical recheck.', ['A2', 'A3'], 'tested', 'bench'),
  lesson('7.5', 'Check continuity', 'With cells absent, verify expected connections and check for an unintended supply short. Confirm meter mode and test it on a known connection.', 'What state must the board be in for continuity checks?', ['Unpowered, with cells removed', 'Powered with the switch on', 'Powered with the meter in current mode'], 0, 'Continuity mode is for unpowered circuits. Follow the meter manual.', 'Record expected and observed connections, including supply-short check.', ['M1', 'B2'], 'bare', 'bench'),
  lesson('7.6', 'Apply first power', 'Only after unpowered inspection, insert cells and observe. Stop for heat, smell, smoke, or unexpected behavior. Record supply and resistor voltages rather than relying on light alone.', 'The LED lights. Is testing finished?', ['No; record safe operation and relevant voltages', 'Yes; light proves all ratings and joints', 'Only if XP increased'], 0, 'A glowing LED is one observation; measurements and inspection are still required.', 'Record first-power observations and readings, or mark power-up pending.', ['M1', 'B2', 'C1'], 'tested', 'bench'),

  lesson('8.1', 'Start with the symptom', '“LED dark” is an observation with several possible causes. List hypotheses, then choose the safest measurement that separates them.', 'Which is a good diagnostic first step?', ['Check supply and switch state, then choose a discriminating test', 'Replace every component', 'Short the resistor'], 0, 'A measured observation narrows the possible causes without creating a new hazard.', 'Record a symptom, two hypotheses, and your next safe test.', ['M1', 'C1'], 'tested', 'bench'),
  lesson('8.2', 'Localize the fault', 'Use unpowered continuity for connection questions and DC voltage for powered node questions. Decide what result each hypothesis predicts before probing.', 'With cells removed, which test best checks whether a trace is open?', ['Continuity between its intended ends', 'Current mode across the battery', 'Board color comparison'], 0, 'Continuity can test an intended connection while unpowered.', 'Record one hypothesis, predicted reading, actual or simulated reading, and conclusion.', ['M1', 'F1'], 'layout', 'bench'),
  lesson('8.3', 'Explain unusual current', 'Measure voltage across the series resistor and use its actual resistance to infer current. Then compare with the design assumptions.', 'A 100 Ω resistor measures 0.5 V across it. What current in milliamperes does that imply?', ['5 mA', '50 mA', '0.5 mA'], 0, '0.5 V / 100 Ω = 0.005 A = 5 mA.', 'Calculate current from a reading and state one possible cause if it differs from prediction.', ['F1', 'M1'], 'schematic', 'bench'),
  lesson('8.4', 'Repair and retest', 'Record the fault evidence before changing hardware. Remove cells, repair safely, then repeat the same discriminating test to see whether the hypothesis was correct.', 'Why repeat the original test after repair?', ['To see whether the predicted change occurred', 'Only to increase XP', 'Because photos always prove function'], 0, 'A before/after test connects the repair to evidence rather than guesswork.', 'Record before/after readings and whether they support your diagnosis.', ['A3', 'M1'], 'tested', 'bench'),
  lesson('8.5', 'Diagnose a new fault', 'For an unfamiliar failure, use observations to rule hypotheses in or out. A reasoned diagnosis is useful even before a physical repair succeeds.', 'Two causes predict different voltage at a node. What should you do?', ['Measure that node safely and compare with both predictions', 'Guess the more familiar cause', 'Replace the battery without checking'], 0, 'A discriminating measurement separates the hypotheses.', 'Describe an unfamiliar fault, your test choice, evidence, and remaining uncertainty.', ['M1', 'F1'], 'tested', 'bench'),

  lesson('9.1', 'Choose another LED', 'Pick a compatible exact LED and read its electrical conditions, polarity, dimensions, and package. A different color or part may change the resistor calculation and footprint.', 'Can a new LED be substituted based on color alone?', ['No; verify ratings, test conditions, polarity, and fit', 'Yes; all LEDs share one forward voltage', 'Yes if the silkscreen stays the same'], 0, 'The exact datasheet and physical package determine what must change.', 'Record the new part number, datasheet, relevant conditions, and footprint implications.', ['C1', 'K4'], 'files', 'design'),
  lesson('9.2', 'Recalculate', 'Recalculate the series resistor and power for the new LED using supply and LED ranges. State what is predicted and what still needs a real test.', 'Hypothetical revision: 3 V supply, 2 V assumed new LED voltage, 5 mA target. What resistor value in ohms does this model suggest?', ['200 Ω', '2 Ω', '1000 Ω'], 0, '(3 V − 2 V) / 0.005 A = 200 Ω. The real revised design must use the exact new datasheet and a range of conditions.', 'Record new calculations with units, assumptions, and a comparison to the old design.', ['F1', 'F3', 'C2'], 'schematic', 'design'),
  lesson('9.3', 'Update and recheck', 'Update the schematic, footprint if needed, board, ERC, DRC, and fabrication outputs as one versioned revision. Keep old and new packages separate.', 'After changing the LED footprint, what must be rerun?', ['Schematic/board review, ERC, DRC, and output inspection', 'Only the lesson quiz', 'Nothing if the LED still fits visually'], 0, 'A part change can affect both electrical and physical design.', 'Record the revised file set and each rerun check, or mark CAD work pending.', ['K2', 'K4', 'K5'], 'layout', 'design'),
  lesson('9.4', 'Defend the design', 'Explain what the evidence supports: exact parts, assumptions, checks, measured behavior, failure risks, and remaining uncertainty. A design review should not claim a physical board works without a test.', 'Which statement is justified if the revised board has not been built?', ['The files passed documented checks; physical behavior remains unverified', 'The revised PCB definitely works', 'The LED must draw exactly its typical current'], 0, 'Design checks support a file review; only a physical build and measurement establish physical behavior.', 'Write a short design review with evidence and unresolved questions.', ['K2', 'K4', 'M1'], 'tested', 'design'),
]

const numericExercises: Record<string, { answer: number; unit: string; tolerance: number }> = {
  '1.3': { answer: 0.01, unit: 'A', tolerance: 0.00001 },
  '1.5': { answer: 0.02, unit: 'A', tolerance: 0.00001 },
  '2.4': { answer: 200, unit: 'Ω', tolerance: 0.5 },
  '2.5': { answer: 0.005, unit: 'W', tolerance: 0.00001 },
  '3.4': { answer: 5, unit: 'mA', tolerance: 0.01 },
  '8.3': { answer: 5, unit: 'mA', tolerance: 0.01 },
  '9.2': { answer: 200, unit: 'Ω', tolerance: 0.5 },
}
for (const item of lessons) if (numericExercises[item.id]) item.numeric = numericExercises[item.id]

export const lessonById: Record<string, LessonContent> = Object.fromEntries(lessons.map(item => [item.id, item]))

export const unitChecks = [
  { prompt: 'You have a new low-voltage board idea. What should happen before first power?', options: ['Inspect the unpowered design and build', 'Order boards before choosing parts', 'Insert cells while soldering'] as [string,string,string], correct: 0, why: 'A safe plan and unpowered inspection precede first power.' },
  { prompt: 'An unfamiliar simple loop has an open switch. What should you predict?', options: ['No conducting loop current', 'Current jumps across the opening', 'The battery becomes a short'] as [string,string,string], correct: 0, why: 'An open switch interrupts the conducting path.' },
  { prompt: 'A new LED datasheet gives forward voltage at a stated test current. What should your design record include?', options: ['The test condition and a range-based resistor check', 'Only the typical voltage', 'A universal LED voltage'] as [string,string,string], correct: 0, why: 'Part data and assumptions must be tied to their conditions.' },
  { prompt: 'Your prototype lights but differs from prediction. Which evidence is most useful?', options: ['Measured supply and resistor voltages with values and units', 'Only a photo of the light', 'A higher XP total'] as [string,string,string], correct: 0, why: 'Measurements help reconcile model and hardware.' },
  { prompt: 'A schematic passes ERC. What still needs checking?', options: ['Intent, LED polarity, exact parts, and pin mapping', 'Nothing', 'Only the project name'] as [string,string,string], correct: 0, why: 'ERC cannot prove a circuit works or its parts fit.' },
  { prompt: 'A PCB passes DRC. What independent review remains?', options: ['Footprints, polarity, routing intent, assembly, and edge details', 'Only board color', 'None'] as [string,string,string], correct: 0, why: 'DRC tests configured rules; physical and circuit intent need review.' },
  { prompt: 'Before paying for fabrication, what package should you inspect?', options: ['Matching board revision, Gerbers, drills, BOM, and checks', 'Any Gerber folder', 'A screenshot alone'] as [string,string,string], correct: 0, why: 'A released package must be internally consistent and inspected.' },
  { prompt: 'A finished board lights. What confirms it has been tested responsibly?', options: ['Unpowered checks plus recorded powered measurements', 'Only the light', 'A clean CAD DRC'] as [string,string,string], correct: 0, why: 'The real assembly and behavior require evidence.' },
  { prompt: 'An unfamiliar fault has two plausible causes. What is the strongest next step?', options: ['Choose a safe reading that distinguishes their predictions', 'Replace both parts without testing', 'Assume the common cause'] as [string,string,string], correct: 0, why: 'A discriminating test supports a diagnosis.' },
  { prompt: 'A new LED changes the design. What must your final review explain?', options: ['Recalculation, file revisions, checks, measurements, and uncertainty', 'Only a new color name', 'That simulation proves physical success'] as [string,string,string], correct: 0, why: 'A part change must be traced through calculation, files, and evidence.' },
]

const extraChecks: typeof unitChecks = [
  { prompt: 'Which item should be absent while checking continuity?', options: ['The board outline', 'The AA cells', 'The schematic'] as [string,string,string], correct: 1, why: 'Continuity mode is used with the circuit unpowered.' },
  { prompt: 'A resistor has 1 V across it and carries 0.01 A. What is its resistance?', options: ['0.01 Ω', '10 Ω', '100 Ω'] as [string,string,string], correct: 2, why: 'R = V/I = 1 V / 0.01 A = 100 Ω.' },
  { prompt: 'Two AA cells are rated 1.5 V nominal each. What does nominal mean for the pack?', options: ['A useful rating, not a guaranteed exact measured 3 V', 'Exactly 3.000 V at every load', 'The LED must drop exactly 3 V'] as [string,string,string], correct: 0, why: 'Actual battery voltage depends on condition, load, and temperature.' },
  { prompt: 'Where should a meter be connected to read resistor voltage?', options: ['In current mode across the battery', 'Across the resistor’s two terminals in voltage mode', 'To the board outline'] as [string,string,string], correct: 1, why: 'A voltmeter compares the potential at two points across the component.' },
  { prompt: 'A symbol pin number differs from the exact part drawing. What should you do?', options: ['Ignore it if ERC passes', 'Order the board and test later', 'Stop and correct the pin mapping'] as [string,string,string], correct: 2, why: 'The schematic and physical part must map to the same pins.' },
  { prompt: 'A footprint looks right in 3D but the drill size differs from the part drawing. What is the next step?', options: ['Fix or replace the footprint before release', 'Let DRC decide the part will fit', 'Bend every lead after fabrication'] as [string,string,string], correct: 0, why: 'Physical fit requires the exact dimensions and hole size.' },
  { prompt: 'The drill file belongs to an older board revision. Can the package be released?', options: ['Yes if the file name looks correct', 'No; regenerate and inspect matching outputs', 'Yes if the silkscreen is visible'] as [string,string,string], correct: 1, why: 'A manufacturing package must be internally consistent.' },
  { prompt: 'Before applying power to a newly soldered board, which check is required?', options: ['A clean profile icon', 'A higher XP total', 'Unpowered polarity and supply-short checks'] as [string,string,string], correct: 2, why: 'Unpowered inspection and electrical checks precede first power.' },
  { prompt: 'A repair changes a reading. What confirms the diagnosis?', options: ['A predicted before/after difference in the same test', 'A different board color', 'The number of clicks made'] as [string,string,string], correct: 0, why: 'A repeatable change in a discriminating test supports the diagnosis.' },
  { prompt: 'Your revised LED design passes DRC but has not been built. What can you claim?', options: ['It will certainly work', 'The configured board checks passed; physical behavior is unverified', 'Its measured current is known'] as [string,string,string], correct: 1, why: 'CAD checks do not establish measured physical behavior.' },
]

const thirdChecks: typeof unitChecks = [
  { prompt: 'You notice heat or an unusual smell on first power. What should you do?', options: ['Continue for another minute', 'Touch the resistor to locate heat', 'Remove power and investigate'] as [string,string,string], correct: 2, why: 'Unexpected heat or odor is a stop condition.' },
  { prompt: 'A wire bypasses the load directly between battery terminals. What should you call this?', options: ['A possible short that requires power removal', 'A useful parallel LED path', 'Proof of a working circuit'] as [string,string,string], correct: 0, why: 'A low-resistance battery bypass can cause excessive current.' },
  { prompt: 'The LED’s typical forward voltage is listed at 10 mA. May you assume it is the same at all currents?', options: ['Yes, by definition', 'No; read the stated test condition and curves', 'Only on a green PCB'] as [string,string,string], correct: 1, why: 'Forward voltage depends on current and other conditions.' },
  { prompt: 'A breadboard rail is split halfway. The LED is dark. What is a safe way to test the suspected open?', options: ['Bridge the battery with the meter', 'Increase the current blindly', 'Remove cells and check rail continuity'] as [string,string,string], correct: 2, why: 'Check suspected connectivity with the circuit unpowered.' },
  { prompt: 'ERC passes but the LED symbol points opposite the intended current. Which conclusion follows?', options: ['Review and correct the logical design', 'ERC proves it will work', 'Only the footprint can fix it'] as [string,string,string], correct: 0, why: 'Rule checks cannot infer every design intention.' },
  { prompt: 'One ratsnest line remains after routing. What does it indicate?', options: ['The board is ready', 'An intended net may still be unrouted', 'A silkscreen spelling error'] as [string,string,string], correct: 1, why: 'An unrouted connection needs correction or a deliberate design change.' },
  { prompt: 'A Gerber viewer shows no board outline. What should happen before ordering?', options: ['Proceed because the PCB editor had an outline', 'Ask the vendor to guess it', 'Regenerate or correct outputs and inspect again'] as [string,string,string], correct: 2, why: 'The exported manufacturing files are what the fabricator receives.' },
  { prompt: 'Which evidence best supports that a soldered LED board behaves as designed?', options: ['Inspection plus recorded supply and resistor voltage', 'Only a lit LED photo', 'Only a passing schematic ERC'] as [string,string,string], correct: 0, why: 'Physical measurements help test the design prediction.' },
  { prompt: 'A dark LED could mean open switch or reversed LED. What should a diagnostic test do?', options: ['Change both at once', 'Produce different predicted readings for the two causes', 'Start with random resoldering'] as [string,string,string], correct: 1, why: 'A useful test separates competing explanations.' },
  { prompt: 'The new LED has different lead spacing. What else needs review?', options: ['Only the displayed name', 'Only the lesson XP', 'Footprint, board layout, and outputs'] as [string,string,string], correct: 2, why: 'A package change affects the physical design and manufacturing files.' },
]

export const unitAssessments = unitChecks.map((first, index) => [first, extraChecks[index], thirdChecks[index]])

export const finalReviewItems = [
  'Exact component datasheets and calculation assumptions recorded',
  'Schematic reviewed; ERC findings resolved or documented',
  'Footprints and PCB reviewed; configured DRC and parity checked',
  'Gerbers and drills inspected against the released board revision',
  'Original board assembly and measurements recorded, or fault diagnosis documented',
  'Independent LED substitution recalculated and design files revised',
  'Remaining uncertainty and self-reported evidence clearly identified',
]
