import { learningText } from './learningLanguage'
import { LabelKey } from './LabelKey'
import { useEffect, useRef, useState } from 'react'
import { activityTasks, makeTask, VARIANTS } from './learningTasks'
import { lessonPlans } from './lessonPlans'
import { unitForCheck, checkTitle, firstLessonTitle, lessonById, finalReviewItems } from './courseContent'
import { lessonArticles } from './lessonArticles'
import { COURSE_VERSION, addSubmission, type ActivityDraft, type LearningRecord, type StorageResult, type Submission } from './learningStore'
import { gradePart } from './taskTypes'
import { TaskRunner } from './TaskRunner'
import {freshVariant,initialAnswers} from './activityState'
import { ArtifactView } from './ArtifactView'
import { Icon } from './Icon'
import { ReferencePanel, SourceLinks } from './ReferencePanel'
export function CourseActivity({activityId,record,status,update,close,nextId,openNext,backup}:{activityId:string;record:LearningRecord;status:StorageResult;update:(fn:(record:LearningRecord)=>LearningRecord)=>void;close:()=>void;nextId?:string;openNext:(id:string)=>void;backup:()=>void}){
  const[exitOpen,setExitOpen]=useState(false),[reference,setReference]=useState(false),[done,setDone]=useState(false),[notice,setNotice]=useState('')
  const heading=useRef<HTMLHeadingElement>(null),keep=useRef<HTMLButtonElement>(null),closeButton=useRef<HTMLButtonElement>(null)
  const draft=record.drafts[activityId];const taskIds=activityTasks(activityId),taskId=taskIds[draft?.index??0],task=makeTask(taskId,draft?.variant??0,activityId==='final'),plan=lessonPlans[taskId]
  const isFinal=activityId==='final',isCheck=activityId.startsWith('unit-'),isReview=activityId.startsWith('review:')
  const title=isFinal?'Independent design review':isCheck?checkTitle(activityId):isReview?`Review: ${plan.outcome}`:activityId==='0.1'?firstLessonTitle:lessonById[activityId].title
  const worked=Array.from({length:VARIANTS},(_,i)=>makeTask(taskId,((draft?.variant??0)+2+i)%VARIANTS)).find(t=>t.variantId!==task.variantId)??task
  useEffect(()=>{if(!done&&draft?.stage==='learn'&&!isCheck&&!isFinal&&!record.exposures[worked.variantId])update(r=>({...r,exposures:{...r.exposures,[worked.variantId]:{taskId,at:new Date().toISOString(),taskVersion:COURSE_VERSION}}}))},[done,draft?.stage,isCheck,isFinal,worked.variantId,taskId,record.exposures,update])
  const repeated=Boolean(record.exposures[task.variantId])||record.submissions.some(s=>s.variantId===task.variantId&&s.attemptId!==draft?.caseId)
  const hasSubmissions=record.submissions.some(s=>s.attemptId===draft?.caseId)
  const dirty=!done&&Boolean(draft&&(draft.stage!=='learn'||hasSubmissions||Object.keys(draft.answers).length||draft.note!==record.completions[activityId]?.note&&draft.note))
  useEffect(()=>{heading.current?.focus();window.scrollTo(0,0)},[activityId,draft?.stage,draft?.index,draft?.variant,done])
  useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=true};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty])
  useEffect(()=>{if(exitOpen)keep.current?.focus()},[exitOpen])
  const patch=(value:Partial<ActivityDraft>)=>update(r=>({...r,drafts:{...r.drafts,[activityId]:{...r.drafts[activityId],...value}}}))
  function submit(){
    if(draft.checked)return
    const parts=task.revealAfter&&!draft.revealed?task.parts.slice(0,task.revealAfter):task.retestAfter&&!draft.retested?task.parts.slice(0,task.retestAfter):task.parts
    const grades=parts.map(p=>gradePart(p,draft.answers[p.id]));const correct=grades.every(x=>x.correct);const setup=Boolean(task.revealAfter&&!draft.revealed),retest=Boolean(!setup&&task.retestAfter&&!draft.retested)
    const earlier=record.submissions.filter(s=>s.attemptId===draft.caseId)
    const submission:Submission={id:crypto.randomUUID(),attemptId:draft.caseId,phase:setup?'setup':retest?'retest':'complete',activityId,taskId,taskVersion:COURSE_VERSION,variantId:task.variantId,variantIndex:draft.variant,artifactId:`led-a:${task.artifact.kind}:${task.variantId}`,skillIds:[...new Set(parts.flatMap(p=>p.skillIds))],at:new Date().toISOString(),answers:structuredClone(draft.answers),correct,mistakes:grades.flatMap((g,i)=>g.correct?[]:[`${parts[i].id}:${g.mistake}`]),assisted:draft.helped||earlier.some(s=>!s.correct),repeated,firstSubmission:!earlier.some(s=>s.phase===(setup?'setup':retest?'retest':'complete')),purpose:isFinal?'final':isCheck?'check':isReview?'review':'lesson'}
    update(r=>{const next=addSubmission(r,submission);return{...next,drafts:{...next.drafts,[activityId]:{...next.drafts[activityId],checked:!((setup||retest)&&correct),revealed:setup&&correct?true:draft.revealed,retested:retest&&correct?true:draft.retested}}}})
  }
  function advance(){
    const earlier=record.submissions.filter(s=>s.attemptId===draft.caseId);const assisted=draft.helped||earlier.some(s=>!s.correct)
    if(assisted&&!draft.followup){const variant=freshVariant(record,taskId,draft.variant+1,task.variantId,isFinal);const next=makeTask(taskId,variant,isFinal);if(next.variantId!==task.variantId){patch({variant,answers:initialAnswers(next),helped:false,checked:false,caseId:crypto.randomUUID(),revealed:false,retested:false,followup:true});setNotice('Apply the correction to a different case. Support remains available.');return}setNotice('The reviewed cases have already been seen. This completion records practice; it does not create new independent evidence.')}
    if(draft.index<taskIds.length-1){const index=draft.index+1;const variant=freshVariant(record,taskIds[index],isFinal?4:3,undefined,isFinal);patch({index,variant,answers:initialAnswers(makeTask(taskIds[index],variant,isFinal)),helped:false,checked:false,caseId:crypto.randomUUID(),revealed:false,retested:false,followup:false});setNotice('Use the next artifact to support your decision.')}else patch({stage:'record'})
  }
  function finish(){update(r=>{const copy={...r.drafts};delete copy[activityId];return{...r,drafts:copy,completions:{...r.completions,[activityId]:{at:new Date().toISOString(),note:draft.note.trim(),physical:draft.physical,fields:draft.fields,...(isFinal?{reviewStatuses:Object.fromEntries(finalReviewItems.map((_,i)=>[String(i),draft.reviewStatuses[String(i)]??'pending']))}:{})}},awards:r.awards.includes(activityId)||isReview?r.awards:[...r.awards,activityId]}});setDone(true)}
  function openReference(){if(draft?.stage==='practice')patch({helped:true});setReference(true)}
  const dismiss=()=>{setExitOpen(false);closeButton.current?.focus()}
  const support=()=>{patch({helped:true});setNotice(plan.example)}
  return <div className="lesson-page"><header className="lesson-header"><div><button ref={closeButton} className="icon-button" aria-label="Return to lesson path" type="button" onClick={()=>dirty?setExitOpen(true):close()}><Icon name="close"/></button><progress className="native-progress" max="3" value={done?3:draft?.stage==='learn'?1:draft?.stage==='practice'?2:3} aria-label="Activity stage"/><button type="button" className="text-button" onClick={openReference}>Reference</button></div></header><main className="lesson-main"><article className="lesson-panel activity-panel">
    <span className="lesson-eyebrow">{isFinal?'FINAL REVIEW':isCheck?'UNIT CHECK':isReview?'RETRIEVAL':`LESSON ${activityId}`}</span><h1 tabIndex={-1} ref={heading}>{done?'Practice recorded':draft.stage==='practice'?`${learningText(task.title)}${taskIds.length>1?` · ${draft.index+1}/${taskIds.length}`:''}`:learningText(title)}</h1>
    {!status.durable&&<div className="storage-alert" role="alert"><p>{status.error}</p><button type="button" onClick={backup} className="secondary-button">Download backup</button></div>}
    {done?<><p className="lesson-lead">{status.durable?'Your decisions and note are saved on this device.':'Your decisions and note are held in this session. Download a backup before closing.'}</p><p>Corrected practice, fresh answers and self-reported physical work remain separate in your learning record.</p>{isFinal&&<p>This review checked six changed tasks. Physical assembly and measurements can remain pending.</p>}<div className="result-actions">{nextId&&<button type="button" className="primary-button" onClick={()=>openNext(nextId)}>Next activity <Icon name="arrow"/></button>}<button type="button" className="secondary-button" onClick={close}>Return to path</button></div></>:draft.stage==='learn'?<>
      <p className="reading-goal"><strong>{isFinal?'Changed design review':isCheck?'Use changed cases':isReview?'Retrieve a skill':'Your required practice'}</strong>{isFinal?'Extract replacement-part data, calculate, check fit and outputs, and diagnose with evidence.':isCheck?`Apply ideas from ${unitForCheck(activityId)!.title.toLowerCase()} using changed examples.`:learningText(plan.outcome)}</p>
      {!isFinal&&!isCheck&&<div className="lesson-reading">{lessonById[taskId]&&<><h2>The idea</h2><p className="lesson-lead">{learningText(lessonById[taskId].learn)}</p></>}{lessonArticles[taskId]&&<><h2>Words you need</h2><dl className="reading-terms">{lessonArticles[taskId].terms.map(([term,meaning])=><div key={term}><dt>{term}</dt><dd>{learningText(meaning)}</dd></div>)}</dl></>}
      <LabelKey text={[...plan.steps,plan.example,worked.context,...worked.parts.flatMap(p=>[p.prompt,p.explanation]),...(worked.artifact.rows?.flat()??[])].join(" ")}/><h2>How to do it</h2><ol className="lesson-steps">{plan.steps.map(step=><li key={step}>{learningText(step)}</li>)}</ol><h2>Worked example</h2><p>{learningText(worked.context)}</p></div>}
      <ArtifactView showKey={isFinal||isCheck} task={isFinal||isCheck?{...task,artifact:{kind:activityId==='unit-basics'?'basics':'circuit',variant:0,target:activityId==='unit-basics'?'E.9':undefined}}:worked}/>{!isFinal&&!isCheck&&<details open className="worked-case"><summary>Walk through this example</summary><ol>{worked.parts.map(p=><li key={p.id}><strong>{learningText(p.prompt)}</strong> {learningText(p.explanation)}</li>)}</ol></details>}<SourceLinks ids={task.sources}/><p className="record-help">The app supplies example values and readings. You can practice without tools; optional CAD and physical work have their own records. Opening Reference during practice records that you used help.</p><div className="lesson-actions"><span className="activity-helper">{record.completions[activityId]?.legacy?'Earlier completion preserved; new practice is available.':'Study the example, then try a changed case.'}</span><button className="primary-button" type="button" onClick={()=>patch({stage:'practice',answers:Object.keys(draft.answers).length?draft.answers:initialAnswers(task)})}>Begin practice <Icon name="arrow"/></button></div>
    </>:draft.stage==='practice'?<>{notice&&<p className="practice-notice" role="status">{learningText(notice)}</p>}{repeated&&<p className="record-help">This exact case has been shown or attempted before. Repeating it counts as practice, rather than new independent evidence.</p>}<div className="practice-tools"><button className="text-button" type="button" onClick={support}>Show worked example</button><button className="text-button" type="button" onClick={()=>patch({stage:'learn',helped:true})}>Back to explanation</button></div><TaskRunner task={task} draft={draft} change={patch} submit={submit} advance={advance}/><SourceLinks ids={task.sources}/></>:<>
      <p className="lesson-lead">Your submitted decisions are already checkpointed. Add a note or optional physical record, then finish this activity.</p>{isFinal&&<div className="review-list">{finalReviewItems.map((label,i)=><label key={label}><span>{label}</span><select aria-label={`${label} status`} value={draft.reviewStatuses[String(i)]??'pending'} onChange={e=>patch({reviewStatuses:{...draft.reviewStatuses,[String(i)]:e.target.value}})}><option value="pending">Pending</option><option value="present">Self-reported present</option></select></label>)}</div>}
      <label className="record-label" htmlFor="activity-note">Your note (optional)</label><textarea id="activity-note" value={draft.note} onChange={e=>patch({note:e.target.value})} rows={4}/>
      {plan.optionalSteps&&<><h2>Optional real work</h2><ol className="lesson-steps">{plan.optionalSteps.map(x=><li key={x}>{learningText(x)}</li>)}</ol></>}
      {plan.records&&<details className="physical-record"><summary>Optional CAD or bench record</summary><p>These are your reports. The app does not inspect files, tools or hardware.</p><label>Work status <select value={draft.physical} onChange={e=>patch({physical:e.target.value as ActivityDraft['physical']})}><option value="pending">Physical/CAD work pending</option><option value="reported">Work tried (self-reported)</option></select></label>{plan.records.map(field=><label className="record-label" key={field}>{learningText(field)}<input value={draft.fields[field]??''} onChange={e=>patch({fields:{...draft.fields,[field]:e.target.value}})}/></label>)}</details>}
      <p className="record-help">No note length is graded. Your actual problem decisions provide the conceptual evidence.</p><button type="button" className="primary-button" onClick={finish}>Finish activity <Icon name="check"/></button>
    </>}
  </article></main>{reference&&<ReferencePanel close={()=>setReference(false)}/>}{exitOpen&&<div className="exit-backdrop"><div className="exit-dialog" role="dialog" aria-modal="true" aria-labelledby="activity-exit-title" onKeyDown={e=>{if(e.key==='Escape')dismiss();if(e.key==='Tab'){e.preventDefault();const buttons=e.currentTarget.querySelectorAll<HTMLButtonElement>('button');(document.activeElement===buttons[0]?buttons[1]:buttons[0]).focus()}}}><h2 id="activity-exit-title">Leave this activity?</h2><p>{status.durable?'Your current case, answers and place are saved. You can resume from the path.':'This work is only in memory. Stay and download a backup before closing the app.'}</p><div className="exit-actions"><button ref={keep} type="button" className="primary-button" onClick={dismiss}>Keep learning</button><button type="button" className="secondary-button" onClick={close}>Leave activity</button></div></div></div>}</div>
}
