import type { StageVisualId } from './StageVisual'
import { assessmentPracticeEdits, lessonPracticeEdits } from './practiceEdits.ts'

export type SourceId = 'F1' | 'F2' | 'F3' | 'C1' | 'C2' | 'B1' | 'B2' | 'K2' | 'K3' | 'K4' | 'K5' | 'M1' | 'M2' | 'A1' | 'A2' | 'A3' | 'P1'
export const sources: Record<SourceId, { title: string; url: string }> = {
  F1: { title: 'OpenStax: Ohm’s law and simple circuits', url: 'https://openstax.org/books/college-physics-2e/pages/20-2-ohms-law-resistance-and-simple-circuits' },
  F2: { title: 'OpenStax: Series and parallel resistors', url: 'https://openstax.org/books/university-physics-volume-2/pages/10-2-resistors-in-series-and-parallel' },
  F3: { title: 'OpenStax: Electric power', url: 'https://openstax.org/books/college-physics-2e/pages/20-4-electric-power-and-energy' },
  C1: { title: 'Kingbright WP7113ID datasheet', url: 'https://www.kingbrightusa.com/images/catalog/SPEC/WP7113ID.pdf' },
  C2: { title: 'Energizer E91 AA datasheet', url: 'https://data.energizer.com/pdfs/e91.pdf' },
  B1: { title: 'Adafruit: Breadboards for beginners', url: 'https://learn.adafruit.com/breadboards-for-beginners/breadboards' },
  B2: { title: 'Energizer battery care', url: 'https://energizer.com/about-batteries/battery-care/' },
  K2: { title: 'KiCad: Getting started', url: 'https://docs.kicad.org/10.0/en/getting_started_in_kicad/getting_started_in_kicad.html' },
  K3: { title: 'KiCad: Schematic editor', url: 'https://docs.kicad.org/10.0/en/eeschema/eeschema.html' },
  K4: { title: 'KiCad: PCB editor', url: 'https://docs.kicad.org/10.0/en/pcbnew/pcbnew.html' },
  K5: { title: 'KiCad: GerbView', url: 'https://docs.kicad.org/10.0/en/gerbview/gerbview.html' },
  M1: { title: 'Adafruit: Multimeters', url: 'https://learn.adafruit.com/multimeters?view=all' },
  M2: { title: 'Fluke: Continuity testing', url: 'https://www.fluke.com/en-gb/learn/blog/digital-multimeters/how-to-test-for-continuity' },
  A1: { title: 'Adafruit: Soldering tools and safety', url: 'https://learn.adafruit.com/adafruit-guide-excellent-soldering' },
  A2: { title: 'Adafruit: Making a good solder joint', url: 'https://learn.adafruit.com/adafruit-guide-excellent-soldering/making-a-good-solder-joint' },
  A3: { title: 'Adafruit: Common soldering problems', url: 'https://learn.adafruit.com/adafruit-guide-excellent-soldering/common-problems' },
  P1: { title: 'JLCPCB: Fabrication capabilities', url: 'https://jlcpcb.com/capabilities/Capab' },
}

export type LessonContent = {
  id: string
  title: string
  learn: string
  prompt: string
  options: [string, string, string]
  correct: number
  why: string
  evidence: string
  sources: SourceId[]
  visual: StageVisualId
  work?: 'design' | 'bench'
  numeric?: { answer: number; unit: string; tolerance: number }
}

const lesson = (id: string, title: string, learn: string, prompt: string, options: [string, string, string], correct: number, why: string, evidence: string, sourceIds: SourceId[], visual: StageVisualId, work?: 'design' | 'bench'): LessonContent => ({ id, title, learn, prompt, options, correct, why, evidence, sources: sourceIds, visual, work, ...lessonPracticeEdits[id] })

export const courseUnits: { title: string; lessonIds: string[] }[] = [
  { title: 'Prepare the mission', lessonIds: ['0.1', '0.2', '0.3', '0.4'] },
  { title: 'Understand a circuit', lessonIds: ['1.1', '1.2', '1.3', '1.4', '1.5', '1.6'] },
  { title: 'Choose the parts', lessonIds: ['2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7'] },
  { title: 'Prototype and measure', lessonIds: ['3.1', '3.2', '3.3', '3.4', '3.5', '3.6'] },
  { title: 'Draw the schematic', lessonIds: ['4.1', '4.2', '4.3', '4.4', '4.5', '4.6'] },
  { title: 'Lay out the PCB', lessonIds: ['5.1', '5.2', '5.3', '5.4', '5.5', '5.6', '5.7', '5.8'] },
  { title: 'Prepare fabrication', lessonIds: ['6.1', '6.2', '6.3', '6.4'] },
  { title: 'Assemble and test', lessonIds: ['7.1', '7.2', '7.3', '7.4', '7.5', '7.6'] },
  { title: 'Debug with evidence', lessonIds: ['8.1', '8.2', '8.3', '8.4', '8.5'] },
  { title: 'Make one independent change', lessonIds: ['9.1', '9.2', '9.3', '9.4'] },
]

export const firstLessonTitle = 'From idea to tested PCB'

export const lessons: LessonContent[] = [
  lesson('0.2', 'Work safely', 'This course uses a small external holder with two alkaline AA cells. Keep cells out during wiring and continuity checks. A shorted battery can heat wiring or cells.', 'The two AA cells are still in the holder while you change a wire. What should you do before moving it?', ['Open the switch and leave the cells in place', 'Remove the cells, change the wire, then inspect for shorts', 'Use continuity mode to check the live board'], 1, 'Opening the switch does not guarantee every point is unpowered. Remove the cells before rewiring or checking continuity.', 'State the supply you will use and one reason to stop before power.', ['B2', 'C2'], 'schematic'),
  lesson('0.3', 'Know your tools', 'A meter checks voltage and unpowered continuity. A breadboard tests temporary connections. KiCad creates the schematic and board files; a soldering iron assembles the physical board.', 'You want to know whether a jumper wire connects to an LED lead on a breadboard. The cells are removed. Which tool and setting would help?', ['A meter in DC voltage mode across the empty holder', 'A meter in continuity mode between the jumper and LED lead', 'A breadboard rail used as a probe'], 1, 'Continuity mode can check a suspected connection when the circuit is unpowered. Confirm the meter mode and probe locations.', 'List the tools and parts you have, and note anything missing.', ['M1', 'B1', 'K2', 'A1'], 'tested'),
  lesson('0.4', 'Plan first power', 'Power is the final step after inspecting the build. With cells absent, check for shorts and polarity; then apply power and stop if anything heats, smells unusual, or behaves unexpectedly.', 'Your unpowered check finds continuity directly between the holder’s positive and negative terminals with the switch closed. What is the next step?', ['Insert the cells briefly to see whether the LED lights', 'Investigate the possible short before inserting cells', 'Assume the meter beep means the circuit is ready'], 1, 'A low-resistance path across the supply may be a short. Investigate the path with cells absent before first power.', 'Write your first-power sequence and stop conditions.', ['B2', 'M1'], 'tested'),

  lesson('1.1', 'Trace a closed loop', 'A simple circuit needs a closed conducting path from one battery terminal, through the load, and back to the other. An open switch interrupts that path.', 'The battery still measures voltage, but opening the only switch turns the LED off. What does that tell you about the loop?', ['The switch interrupted the conducting path while the battery may retain voltage', 'The battery voltage must have become zero', 'Current continues through the open switch but the LED blocks it'], 0, 'An open switch breaks the current path; the battery can still have voltage across its terminals.', 'Trace a battery–switch–resistor–LED loop and mark where an open switch breaks it.', ['F1'], 'schematic'),
  lesson('1.2', 'Voltage and current', 'Current describes charge flow through a branch. Voltage is a difference in electric potential between two points. A voltmeter therefore compares two probe locations.', 'You need the voltage across the series resistor. Where do the two voltage probes go?', ['One on each end of the resistor', 'One on the battery positive terminal and one on its negative terminal', 'Both on the same end of the resistor'], 0, 'A voltage measurement compares two points. Probing the resistor’s two ends measures its voltage drop; probing the battery measures supply voltage.', 'Describe two probe points for measuring voltage across a resistor.', ['F1', 'M1'], 'schematic'),
  lesson('1.3', 'Units that matter', '1 ampere equals 1000 milliamperes; 1 kilo-ohm equals 1000 ohms. Write the unit on every value so the scale of a calculation remains visible.', 'How many amperes is 10 mA?', ['0.010 A', '10,000 A', '0.1 A'], 0, 'Divide milliamperes by 1000: 10 mA is 0.010 A.', 'Convert 2.2 kΩ to ohms and 0.015 A to milliamperes, with units.', ['F1'], 'schematic'),
  lesson('1.4', 'Change a resistor', 'For an ideal fixed voltage across an ohmic resistor, I = V/R. Increasing R reduces I. The LED itself is not an ohmic resistor, so this is a model of the resistor portion.', 'With the same voltage across a resistor, what does doubling its resistance do to current?', ['Doubles it', 'Halves it', 'Leaves it unchanged'], 1, 'I = V/R, so doubling R halves current when the voltage across it stays fixed.', 'Predict the direction of current change before trying a different resistor in a model.', ['F1'], 'schematic'),
  lesson('1.5', 'Use Ohm’s law', 'Use I = V/R for an ohmic resistor and keep units visible. Rearrange to V = IR or R = V/I only after identifying what is known.', 'A 100 Ω resistor has 2 V across it. What is its current?', ['0.02 A', '50 A', '200 A'], 0, '2 V / 100 Ω = 0.02 A, or 20 mA. This example concerns the resistor, not an LED.', 'Calculate the current through a 200 Ω resistor with 1 V across it.', ['F1'], 'schematic'),
  lesson('1.6', 'Series, open, and short', 'A series path carries the same current through each component. An open breaks it. A low-resistance bypass across a load can create a dangerous short path.', 'A jumper connects around the series resistor, leaving the LED in the loop. Why should you stop before powering it?', ['The jumper may remove current limiting from the LED', 'The jumper makes the LED an open circuit', 'The jumper guarantees the resistor takes more current'], 0, 'A bypass around the resistor can leave the LED without its intended current limit. Remove cells and correct the wiring.', 'Sketch a series loop, an open, and a bypass; explain what changes.', ['F2', 'B2'], 'schematic'),

  lesson('2.1', 'LED direction', 'An LED conducts primarily in one direction and needs a current-limiting element in this course circuit. Check both the schematic symbol and the exact part’s physical polarity marks.', 'The LED’s flat edge seems to disagree with the board’s polarity mark. What should you do before soldering?', ['Trust the board mark because it was generated from the schematic', 'Check the exact LED drawing and pad mapping, then resolve the mismatch', 'Try both orientations with the cells installed'], 1, 'A footprint or marking can be wrong. Compare the actual part drawing with the pad numbers and schematic before assembly.', 'Mark anode and cathode on a sketch of the planned LED and its schematic symbol.', ['C1'], 'schematic'),
  lesson('2.2', 'Read the datasheets', 'A datasheet number is meaningful only with its conditions. The candidate Kingbright LED lists 1.9 V typical and 2.3 V maximum forward voltage at 10 mA and 25 °C; the AA cell’s 1.5 V is nominal.', 'You measured the LED at a different current and temperature than the datasheet test. Can you treat 1.9 V as its guaranteed drop?', ['Yes, because typical means guaranteed', 'No; record the actual conditions and use an appropriate voltage range', 'Yes, if the batteries are rated 1.5 V each'], 1, 'The listed typical voltage is tied to test conditions; it is not a guaranteed value for every operating point.', 'Record the datasheet page and test conditions for one LED parameter and one battery parameter.', ['C1', 'C2'], 'files'),
  lesson('2.3', 'Set a current target', 'LED brightness and current involve a design tradeoff. Choose a modest target only after checking the chosen LED’s limits and testing visibility in the reference build.', 'A candidate target is below the LED’s rated limit but the prototype is hard to see. What should guide a revision?', ['Raise current as high as the battery allows', 'Compare visibility tests with the exact LED limits and resistor power', 'Keep the number because any value under the rating is equally useful'], 1, 'A current target balances the intended visibility with component limits and should be checked on the real prototype.', 'State a tentative target and what evidence you still need before approving it.', ['C1'], 'schematic'),
  lesson('2.4', 'Choose the resistor', 'Estimate resistor voltage from battery voltage minus LED forward voltage, then use R = V/I. Check a range of battery and LED conditions before selecting a real resistor.', 'Hypothetical model: a 3 V supply, 2 V across the LED, and a 5 mA target. What resistance in ohms does the model suggest?', ['200 Ω', '5 Ω', '600 Ω'], 0, '(3 V − 2 V) / 0.005 A = 200 Ω. The 2 V LED assumption is only for this exercise; a real choice needs range checks.', 'Work the hypothetical calculation with units, then list what actual part data remains to be verified.', ['F1', 'C1', 'C2'], 'schematic'),
  lesson('2.5', 'Check power and tolerance', 'For a resistor, P = IV or I²R. Compare the computed worst-case dissipation with the exact resistor’s rating and tolerance in its datasheet.', 'In a hypothetical case, a 200 Ω resistor carries 5 mA. What power does it dissipate in watts?', ['0.005 W', '1 W', '200 W'], 0, 'P = I²R = (0.005 A)² × 200 Ω = 0.005 W. The exact resistor rating and worst-case conditions still need checking.', 'Show the power calculation and cite the selected part’s rating, or mark the part unresolved.', ['F3'], 'schematic'),
  lesson('2.6', 'Switch and battery holder', 'The switch, holder, and connection must fit physically and connect the intended pins. A schematic symbol alone does not establish a footprint or polarity.', 'A slide switch has three pins, but your symbol uses two. What must you establish before assigning its footprint?', ['Which physical pins connect in each switch position and how they map to the symbol', 'Whether its body color matches the LED', 'Only whether the footprint has three pads'], 0, 'The exact switch pinout and operation determine the symbol-to-pad mapping; pad count alone is insufficient.', 'List the exact switch and holder part numbers or mark them unresolved.', ['K3', 'B2'], 'layout'),
  lesson('2.7', 'Review failure cases', 'A reversed LED, open switch, missing resistor, or short can produce different symptoms. Predict and choose a safe inspection or measurement before changing parts.', 'The holder voltage is normal and the switch is closed, but the LED stays dark. Which check helps distinguish a reversed LED from an open connection?', ['Inspect LED polarity, then check the suspected connection unpowered', 'Immediately replace the battery', 'Short across the resistor to increase LED current'], 0, 'A normal supply narrows the search. Check the LED orientation and connections safely before replacing parts.', 'Name two possible causes of a dark LED and a test that distinguishes them.', ['C1', 'B2', 'M1'], 'tested'),

  lesson('3.1', 'Breadboard connections', 'Breadboard rows and power rails connect internally, but rail breaks and layouts vary. Verify the specific board before inserting parts.', 'Your LED works on one half of the breadboard but not when moved to the far end of the same marked rail. What should you test with cells removed?', ['Continuity across the rail’s midpoint', 'Voltage across the LED while moving jumpers', 'Only whether the rail markings have the same color'], 0, 'Some breadboard rails are split. An unpowered continuity test across the suspected break checks the actual connection.', 'Sketch the connected groups on your own breadboard, or use a verified reference diagram.', ['B1', 'M1'], 'layout', 'bench'),
  lesson('3.2', 'Build the prototype', 'Build the approved low-voltage series circuit with cells absent. Compare each connection to the schematic before the first powered trial.', 'Your LED and resistor appear connected, but one jumper may be in the next breadboard row. What should you do before inserting cells?', ['Check the row connections against the schematic with cells absent', 'Insert cells and watch for a brief flash', 'Move the jumper at random until the meter beeps'], 0, 'Breadboard rows can be easy to misread. Confirm the actual connections against the schematic before applying power.', 'Record your cell-free build inspection; label any unbuilt step as pending.', ['B2', 'M1'], 'tested', 'bench'),
  lesson('3.3', 'Measure voltage', 'A DC voltmeter reads a potential difference between two probes. Check the meter’s jack and mode, predict the sign, then measure across the intended two points.', 'The meter shows a negative DC voltage across the holder. What is the first interpretation to check?', ['The probes may be reversed relative to the holder polarity', 'The batteries must be empty', 'The meter is necessarily in current mode'], 0, 'A negative sign often means the red probe is at lower potential than the black probe. Verify probe placement and meter setup.', 'Record meter model, jack/mode, probe points, and observed or expected reading.', ['M1'], 'tested', 'bench'),
  lesson('3.4', 'Infer current', 'Instead of moving a lead to a current jack, measure voltage across the known series resistor and calculate I = V/R. Never put a meter in current mode directly across a battery.', 'You measured 1 V across a known 200 Ω resistor. What is the inferred current?', ['5 mA', '200 A', '200 mA'], 0, '1 V / 200 Ω = 0.005 A = 5 mA. This assumes the resistor value is known.', 'Record resistor value, resistor voltage, and inferred current with units.', ['F1', 'M1'], 'tested', 'bench'),
  lesson('3.5', 'Compare results', 'Compare actual supply and component voltages with predictions. Differences may come from supply state, component spread, measurement, or wiring; do not force an exact nominal result.', 'Your model assumed 3.0 V, but the holder measures 2.7 V under load. Which comparison should you make before changing the resistor?', ['Recalculate using the measured supply and the LED’s plausible voltage range', 'Compare only the LED color with the drawing', 'Treat the nominal 3.0 V as the actual voltage'], 0, 'The model should use measured supply and realistic part ranges before a design change is justified.', 'Write a predicted/observed table and one evidence-based explanation, or mark measurement pending.', ['C1', 'C2', 'F1'], 'tested', 'bench'),
  lesson('3.6', 'Find a wiring fault', 'A dark LED can result from an open rail, reversed LED, wrong resistor, or absent supply. Choose a measurement that separates likely causes.', 'The battery reads normally, but the LED is dark. You suspect either a split rail or a reversed LED. Which check tests the rail hypothesis directly?', ['With cells removed, check continuity across the suspected rail break', 'Measure battery voltage again at the holder', 'Swap the LED immediately without checking the rail'], 0, 'A direct unpowered continuity check can confirm or rule out the suspected rail break.', 'Record a suspected fault, distinguishing test, observation, and correction.', ['B1', 'M1', 'C1'], 'tested', 'bench'),

  lesson('4.1', 'Create a KiCad project', 'A KiCad project keeps the schematic and board together. Save it in a named folder and note the KiCad version used.', 'You found two KiCad project folders with different schematic versions. Before editing the board, what should you establish?', ['Which schematic and board belong to the intended project revision', 'Which folder has the newest screenshot', 'Which board file has the most components, regardless of revision'], 0, 'The schematic and PCB need to belong to the same intended project revision before changes or fabrication.', 'Record your project folder and KiCad version, or mark installation pending.', ['K2'], 'schematic', 'design'),
  lesson('4.2', 'Choose symbols', 'Choose schematic symbols for the exact planned parts, then compare pin numbers and meaning with the manufacturer drawings.', 'A library switch symbol has pins 1 and 2, while the selected part closes pins 1 and 3 in the intended position. What should you resolve?', ['Map the symbol pins to the actual switch operation before using it', 'Rely on the matching switch name', 'Wait for PCB DRC to determine switch behavior'], 0, 'The symbol’s electrical pin mapping must reflect the exact part and intended switch position.', 'List each part and the symbol used, noting any unresolved pin mapping.', ['K3'], 'schematic', 'design'),
  lesson('4.3', 'Wire the nets', 'Join the intended pins and inspect junction dots and highlighted nets. Crossing lines without the intended junction can leave nets separate.', 'Two wires cross where you intended a connection, but net highlighting selects only one wire. What should you do?', ['Add a junction or redraw the connection, then highlight the net again', 'Assume the crossing is connected because the lines touch visually', 'Assign both wires the same color'], 0, 'The editor’s net connectivity matters more than visual overlap. Correct the connection and verify the highlighted net.', 'Trace supply to return and name the nets in your schematic.', ['K3'], 'schematic', 'design'),
  lesson('4.4', 'Assign footprints', 'A footprint maps schematic pins to real pads and holes. Compare pin numbering, pitch, hole size, and body outline with each exact component.', 'A footprint hole pitch matches your switch, but pads 1 and 3 are reversed relative to the datasheet. What should happen?', ['Correct the pad mapping or choose a matching footprint', 'Use it because the leads physically fit', 'Change only the 3D model orientation'], 0, 'Physical fit does not fix an electrical pin mismatch. Match the exact part drawing and symbol mapping.', 'Record a footprint-to-part table and mark any part without an exact match.', ['K3', 'K4'], 'layout', 'design'),
  lesson('4.5', 'Run ERC', 'Electrical Rules Check catches configured connection problems and unconnected pins. It cannot prove that a functioning circuit was designed.', 'ERC passes, but your LED symbol points opposite to the intended current path. What should happen before layout?', ['Correct the LED orientation and rerun ERC', 'Keep it because ERC passed', 'Rotate the footprint only and leave the schematic'], 0, 'ERC does not know your intended LED direction. Fix the circuit design and run the check again.', 'Record ERC findings and how you resolved or documented each one.', ['K2', 'K3'], 'schematic', 'design'),
  lesson('4.6', 'Review the schematic', 'Follow the intended loop without relying on ERC: supply, switch, resistor, LED polarity, return, part values, and ratings.', 'The schematic passes ERC, but tracing from battery positive reaches the LED cathode first. What should you review?', ['LED orientation and the complete intended current path', 'Only the project folder name', 'Only the board outline'], 0, 'Trace the actual circuit and compare LED polarity with the selected part; ERC may not know the intended direction.', 'Write the net-by-net review result and any unresolved item.', ['K2', 'C1'], 'schematic', 'design'),

  lesson('5.1', 'Read board layers', 'Copper carries connections, solder mask covers most copper, and silkscreen provides markings. Through-hole pads may connect on both copper sides.', 'A line between LED and resistor pads appears only on the silkscreen layer. Will it carry current?', ['Yes, because it touches both pad drawings', 'No; route the connection on copper', 'Yes, once solder mask covers it'], 1, 'Silkscreen is printed labeling. The electrical route must be copper connected to the correct pads.', 'Label copper, mask, silkscreen, holes, and edge outline on a board view.', ['K4'], 'layout', 'design'),
  lesson('5.2', 'Check footprints', 'Use exact part drawings and, when possible, a printed 1:1 footprint check. Inspect pad numbering, drill, lead spacing, and polarity.', 'The 3D view shows the switch fitting, but its lead diameter exceeds the footprint drill size. What should you do?', ['Correct the hole size using the exact part drawing and fabrication rules', 'Trust the 3D view because it shows a fit', 'File down every lead after the board arrives'], 0, 'The real lead and drilled hole dimensions govern fit; a 3D image alone cannot validate them.', 'Record the exact part and footprint dimensions you checked.', ['K4'], 'layout', 'design'),
  lesson('5.3', 'Set fabrication rules', 'Read the chosen fabricator’s current capabilities and enter appropriate project rules before routing. Capability minimums are not automatic design targets.', 'A trace fits only if you use the fabricator’s absolute minimum width. What is the sound design decision?', ['Check the current vendor rules and seek comfortable margin or change the layout', 'Assume any width accepted by KiCad will fabricate', 'Set the project rule below the vendor minimum'], 0, 'A stated manufacturing minimum is a limit, not a design target. Verify current capabilities and revise the layout where practical.', 'Record vendor, date, rule source, and the conservative values selected.', ['K4', 'P1'], 'layout', 'design'),
  lesson('5.4', 'Place parts', 'Place parts so the switch can be reached, LED can be seen, battery polarity is legible, and parts can be hand assembled.', 'The switch fits electrically but sits under the battery holder. What should you change?', ['Move it where a finger can reach it while keeping clearances', 'Leave it because DRC can verify access', 'Hide the holder outline so the switch is visible in the editor'], 0, 'Placement must allow the finished board to be used and assembled. DRC does not test finger access.', 'Describe one placement decision and its use or assembly reason.', ['K4'], 'layout', 'design'),
  lesson('5.5', 'Route copper', 'Route each schematic net to the matching pads. A remaining ratsnest line signals an unrouted connection, even if copper appears close.', 'Copper appears to touch a pad, yet KiCad still shows one unrouted connection. What should you inspect?', ['The net assignment and actual pad-to-track connection', 'The silkscreen label near the pad', 'Only the trace color in 3D view'], 0, 'A visible overlap may not be a valid connection. Use net highlighting and the unrouted count to find the missing link.', 'Record the unrouted count and trace at least one full net.', ['K4'], 'layout', 'design'),
  lesson('5.6', 'Outline and markings', 'A closed board outline defines the manufactured edge. Add readable polarity and switch-state markings, then inspect the design at actual scale.', 'The board outline looks closed at normal zoom, but an edge check reports a tiny gap. What should you do?', ['Close the gap on the edge layer and rerun the check', 'Trust the rendered preview because it looks closed', 'Draw over the gap on silkscreen'], 0, 'Fabrication uses the actual edge geometry. A tiny gap can make the manufacturing outline invalid.', 'Record board dimensions and inspect the outline and markings.', ['K4'], 'layout', 'design'),
  lesson('5.7', 'Run DRC', 'Design Rules Check tests the configured board rules and connectivity. Run schematic parity as part of the review; inspect every violation.', 'DRC passes, but you later discover the project clearance rule is smaller than your chosen fabricator allows. What follows?', ['Update the rule, rerun DRC, and repair any new violations', 'Keep the pass result because it was valid when run', 'Hide the clearance rule from the report'], 0, 'DRC only checks the rules entered. Correct the rule set and rerun the board check.', 'Record rules/version, DRC result, parity result, and any documented exceptions.', ['K4'], 'layout', 'design'),
  lesson('5.8', 'Review the board', 'Independently compare every net and footprint with the schematic and exact parts. Check polarity, edges, access, labels, and assembly.', 'The board passes DRC, but its LED cathode mark points to the anode pad. What should the release review do?', ['Correct the marking or footprint and regenerate outputs', 'Ignore the marking because copper connectivity passes', 'Assume assembly will discover the intended direction'], 0, 'A board can pass DRC and still mislead assembly. Resolve the polarity mismatch before release.', 'Record the board review checklist and unresolved issues.', ['K4', 'C1'], 'layout', 'design'),

  lesson('6.1', 'Generate files', 'Export copper, mask, silkscreen, outline, and Excellon drill data from the same approved board revision. Keep outputs together.', 'The Gerbers were regenerated after moving the switch, but the drill file is from yesterday. What should you do?', ['Send both because the copper files are current', 'Regenerate drills from the approved revision and inspect the full set', 'Rename the old drill file to match today’s date'], 1, 'Copper and drill data must come from the same approved board revision; inspect the exported package together.', 'Record board revision and the files generated.', ['K2', 'K4'], 'files', 'design'),
  lesson('6.2', 'Inspect Gerbers', 'Open exported files in GerbView. Inspect copper, mask, outline, markings, and drill alignment independently from the PCB editor.', 'GerbView shows the copper and outline, but the LED polarity mark is missing. What should you check?', ['Whether the silkscreen layer was exported and the mark is on it', 'Whether the schematic file name includes LED', 'Whether the copper color matches the editor theme'], 0, 'Inspect the exported silkscreen and its alignment with the other layers; fix and regenerate missing output.', 'Record a layer-by-layer and drill review, including any missing file.', ['K5'], 'files', 'design'),
  lesson('6.3', 'Prepare the order', 'Compare the fabricator preview with your board and recheck current options, price, shipping, and exact part availability. Do not order until the release review passes.', 'The vendor preview lacks a drill hole visible in GerbView. What should you compare before ordering?', ['The uploaded drill file, layer assignment, and approved revision', 'Only the board color option', 'The shipping speed and the project title'], 0, 'A missing hole may mean a wrong or missing drill upload or revision mismatch. Resolve it before payment.', 'Record the vendor preview check and bill of materials status; keep payment outside the app.', ['P1', 'K5'], 'files', 'design'),
  lesson('6.4', 'Release the design', 'Freeze a matching revision of schematic, board, checks, Gerbers, drills, and bill of materials before spending money.', 'The board and Gerbers match, but the bill of materials lists an older LED footprint. Is this revision ready to order?', ['Yes, because the fabrication files match the board', 'No; reconcile the exact part and footprint, then freeze a matching package', 'Yes, if the board preview looks correct'], 1, 'Part choice and footprint must agree with the approved files. Resolve the mismatch before release.', 'Record the release revision and each signed-off check, or mark release blocked.', ['K4', 'K5', 'P1'], 'files', 'design'),

  lesson('7.1', 'Inspect the bare board', 'Compare the received board with the approved output: outline, holes, pads, mask, silkscreen, and visible defects. Keep cells away.', 'The switch lead will not enter a hole on the received board. Which comparison will tell you where the mismatch arose?', ['Compare the actual lead and hole with the approved footprint and drill output', 'Enlarge the hole until the lead fits without checking the design', 'Assume the switch supplier changed the lead size'], 0, 'Check the part dimensions against the footprint and exported drill data before deciding whether the board or design is wrong.', 'Record what you inspected on the received board, or mark it not yet received.', ['K5'], 'bare', 'bench'),
  lesson('7.2', 'Prepare to solder', 'Set up a stable iron stand, ventilation, eye protection, and a clear workspace. Practice a joint on scrap before the real board.', 'The iron is hot, but its stand is missing and the workspace has loose wires across it. What is the right next step?', ['Hold the iron while clearing the wires', 'Stop and set up a stable stand and clear workspace first', 'Begin with the easiest joint and arrange the bench later'], 1, 'A hot iron needs a stable stand and a clear work area before soldering begins.', 'Record the setup and practice-joint observation, or mark equipment pending.', ['A1'], 'tested', 'bench'),
  lesson('7.3', 'Install the parts', 'Install and verify each exact part’s orientation before soldering. Keep cells out and follow component soldering limits.', 'The LED’s short lead points toward a pad marked +, but the exact part drawing identifies that lead as the cathode. What should you do?', ['Stop and resolve the part-to-pad polarity mismatch before soldering', 'Trust the printed + mark and solder it in', 'Power the unsoldered LED to see which way it lights'], 0, 'A polarity conflict between the real part and board needs resolution before permanent assembly.', 'Record part orientation and assembly sequence, or mark assembly pending.', ['A2', 'C1'], 'tested', 'bench'),
  lesson('7.4', 'Inspect joints', 'A good-looking photo is a clue, not proof. Inspect for bridges, dull or disturbed joints, incomplete wetting, and damaged pads; follow with electrical checks.', 'Two adjacent pads on different nets appear joined by solder. What evidence should you collect before first power?', ['Inspect and remove the bridge, then verify the nets are separate with cells absent', 'Check whether the LED happens to light despite the bridge', 'Assume the pads share a net because solder joined them'], 0, 'An unintended solder bridge can short separate nets. Repair it and verify the separation unpowered.', 'Record any joint concern, repair, and electrical recheck.', ['A2', 'A3'], 'tested', 'bench'),
  lesson('7.5', 'Check continuity', 'With cells absent, verify expected connections and investigate possible supply shorts. A continuity beep means the meter found a low-resistance path, which may run through an installed part; it does not identify a solder bridge by itself. Confirm meter mode on a known connection.', 'With cells removed, the meter beeps between two pads that the schematic places on different nets. What should you investigate?', ['An unintended bridge or wiring error between those nets', 'Whether the battery is nominally 3 V', 'Whether the LED is bright enough'], 0, 'Unexpected continuity between separate nets can reveal a bridge or other fault before power is applied.', 'Record expected and observed connections, including supply-short check.', ['M1', 'M2', 'B2'], 'bare', 'bench'),
  lesson('7.6', 'Apply first power', 'Only after unpowered inspection, insert cells and observe. Stop for heat, smell, smoke, or unexpected behavior. Record supply and resistor voltages rather than relying on light alone.', 'The LED lights, but the resistor is warmer than expected. What should you do?', ['Remove power and compare measured values with the resistor rating and circuit design', 'Leave it powered because the LED is lit', 'Increase the battery voltage to confirm brightness'], 0, 'Unexpected heat is a stop condition. Remove power, then investigate current, dissipation, and the actual part rating.', 'Record first-power observations and readings, or mark power-up pending.', ['M1', 'B2', 'C1'], 'tested', 'bench'),

  lesson('8.1', 'Start with the symptom', '“LED dark” is an observation with several possible causes. List hypotheses, then choose the safest measurement that separates them.', 'The LED is dark. One hypothesis is a drained battery; another is an open switch. Which observation should you collect first?', ['Measure the holder voltage and inspect the switch state', 'Replace the LED before checking power', 'Change the resistor to a lower value'], 0, 'The supply reading and switch state can narrow the cause without altering the circuit.', 'Record a symptom, two hypotheses, and your next safe test.', ['M1', 'C1'], 'tested', 'bench'),
  lesson('8.2', 'Localize the fault', 'Use unpowered continuity for connection questions and DC voltage for powered node questions. Decide what result each hypothesis predicts before probing.', 'A trace may be broken between the switch and resistor. With cells removed, which result would support that hypothesis?', ['No continuity between the trace’s intended endpoints', 'Continuity between those endpoints', 'A normal battery voltage at the holder'], 0, 'An open trace should fail a direct unpowered continuity check across its intended endpoints.', 'Record one hypothesis, predicted reading, actual or simulated reading, and conclusion.', ['M1', 'F1'], 'layout', 'bench'),
  lesson('8.3', 'Explain unusual current', 'Measure voltage across the series resistor and use its actual resistance to infer current. Then compare with the design assumptions.', 'A 100 Ω resistor measures 0.5 V across it. What current in milliamperes does that imply?', ['5 mA', '50 mA', '0.5 mA'], 0, '0.5 V / 100 Ω = 0.005 A = 5 mA.', 'Calculate current from a reading and state one possible cause if it differs from prediction.', ['F1', 'M1'], 'schematic', 'bench'),
  lesson('8.4', 'Repair and retest', 'Record the fault evidence before changing hardware. Remove cells, repair safely, then repeat the same discriminating test to see whether the hypothesis was correct.', 'You repaired a suspected open joint. Which result would support that diagnosis?', ['The same unpowered continuity test now shows the intended connection', 'The silkscreen looks cleaner after repair', 'The LED package is still the same color'], 0, 'Repeat the original discriminating test. A predicted change after repair supports the diagnosis.', 'Record before/after readings and whether they support your diagnosis.', ['A3', 'M1'], 'tested', 'bench'),
  lesson('8.5', 'Diagnose a new fault', 'For an unfamiliar failure, use observations to rule hypotheses in or out. A reasoned diagnosis is useful even before a physical repair succeeds.', 'A dark LED could be caused by an open switch or a reversed LED. With cells removed and the switch set to ON, which test separates those causes?', ['Check continuity across the switch contacts', 'Measure battery voltage at the empty holder', 'Measure continuity across the LED without checking its polarity'], 0, 'A switch that does not close will fail a direct continuity check; a reversed LED does not make the switch contacts open.', 'Describe an unfamiliar fault, your test choice, evidence, and remaining uncertainty.', ['M1', 'F1'], 'tested', 'bench'),

  lesson('9.1', 'Choose another LED', 'Pick a compatible exact LED and read its electrical conditions, polarity, dimensions, and package. A different color or part may change the resistor calculation and footprint.', 'A replacement LED has the same diameter but a different forward-voltage range. What must you revisit?', ['The resistor calculation and exact package/polarity match', 'Only the silkscreen color label', 'Only the switch footprint'], 0, 'A different LED can change the electrical range even when its visible size looks similar. Verify the exact package too.', 'Record the new part number, datasheet, relevant conditions, and footprint implications.', ['C1', 'K4'], 'files', 'design'),
  lesson('9.2', 'Recalculate', 'Recalculate the series resistor and power for the new LED using supply and LED ranges. State what is predicted and what still needs a real test.', 'Hypothetical revision: the supply is 3 V, the new LED is assumed to drop 1.8 V, and the target is 4 mA. What resistor value in ohms does this model suggest?', ['300 Ω', '75 Ω', '1200 Ω'], 0, '(3 V − 1.8 V) / 0.004 A = 300 Ω. The real revision still needs range and power checks using the exact parts.', 'Record new calculations with units, assumptions, and a comparison to the old design.', ['F1', 'F3', 'C2'], 'schematic', 'design'),
  lesson('9.3', 'Update and recheck', 'Update the schematic, footprint if needed, board, ERC, DRC, and fabrication outputs as one versioned revision. Keep old and new packages separate.', 'The revised LED needs a new footprint. The schematic and board are updated, but the Gerbers are from the old revision. What remains?', ['Regenerate and inspect outputs after rerunning the design checks', 'Order using the old Gerbers because the schematic is current', 'Rename the old output folder to the new revision'], 0, 'A footprint change must be carried through checks and exported manufacturing files in one matching revision.', 'Record the revised file set and each rerun check, or mark CAD work pending.', ['K2', 'K4', 'K5'], 'layout', 'design'),
  lesson('9.4', 'Defend the design', 'Explain what the evidence supports: exact parts, assumptions, checks, measured behavior, failure risks, and remaining uncertainty. A design review should not claim a physical board works without a test.', 'Your revised board passes ERC and DRC, but it has not been assembled. Which review claim matches the evidence?', ['The files passed documented checks; current and brightness remain unmeasured', 'The physical board is proven to work', 'The LED current must equal the typical datasheet value'], 0, 'CAD checks support a file review. Current and brightness still require a build and measurement.', 'Write a short design review with evidence and unresolved questions.', ['K2', 'K4', 'M1'], 'tested', 'design'),
]

const numericExercises: Record<string, { answer: number; unit: string; tolerance: number }> = {
  '1.3': { answer: 0.01, unit: 'A', tolerance: 0.00001 },
  '1.5': { answer: 0.02, unit: 'A', tolerance: 0.00001 },
  '2.4': { answer: 200, unit: 'Ω', tolerance: 0.5 },
  '2.5': { answer: 0.005, unit: 'W', tolerance: 0.00001 },
  '3.4': { answer: 3, unit: 'mA', tolerance: 0.01 },
  '8.3': { answer: 5, unit: 'mA', tolerance: 0.01 },
  '9.2': { answer: 300, unit: 'Ω', tolerance: 0.5 },
}
for (const item of lessons) if (numericExercises[item.id]) item.numeric = numericExercises[item.id]

export const lessonById: Record<string, LessonContent> = Object.fromEntries(lessons.map(item => [item.id, item]))

export const unitChecks = [
  { prompt: 'A newly wired LED board has its switch OFF, but no short check has been done. What is the next safe step?', options: ['Remove the cells and inspect polarity and unintended supply paths', 'Turn the switch ON briefly to see whether the LED lights', 'Measure continuity with the cells installed'], correct: 0, why: 'A switch position alone does not replace an unpowered pre-power inspection.' },
  { prompt: 'The LED is off with the only series switch open, yet the holder still reads 3 V. Which explanation fits?', options: ['The open switch interrupts loop current without removing battery voltage', 'The LED must be reversed because the holder has voltage', 'The resistor must draw current through the open switch'], correct: 0, why: 'An open switch interrupts current while the battery can retain terminal voltage.' },
  { prompt: 'A substitute LED lists a typical voltage at 10 mA, while your target is 4 mA. How should you use that number?', options: ['Record its test condition and check the relevant voltage range before choosing a resistor', 'Use the typical number as an exact drop at 4 mA', 'Ignore the datasheet and keep the original resistor'], correct: 0, why: 'A datasheet value is tied to test conditions; a substitution calls for a new range-based check.' },
  { prompt: 'The prototype lights, but inferred current is half your estimate. What should you compare first?', options: ['Measured supply and resistor voltages with the assumed values', 'Only the LED brightness against another color', 'Only the nominal battery label against the design note'], correct: 0, why: 'Actual voltage readings help locate which model assumption differs from the build.' },
  { prompt: 'ERC passes, but the selected switch closes a different pair of pins than the schematic expects. What should happen?', options: ['Correct the symbol-to-part mapping and rerun checks', 'Accept the ERC pass as proof of switch operation', 'Swap the silkscreen ON and OFF labels only'], correct: 0, why: 'ERC cannot verify an exact switch’s internal contact behavior against the intended use.' },
  { prompt: 'DRC passes, but a through-hole part blocks access to the switch. What should the board review do?', options: ['Move parts to preserve access, then rerun DRC', 'Keep placement because DRC passed', 'Shorten the switch label to make room'], correct: 0, why: 'DRC checks configured electrical and geometry rules, not whether a person can use the assembled switch.' },
  { prompt: 'Your vendor upload contains current Gerbers and an older drill file. What should you do before paying?', options: ['Regenerate drills from the approved board revision and inspect the package', 'Order because copper layers are current', 'Rename the old drill file to match the Gerbers'], correct: 0, why: 'The manufacturing outputs must belong to the same approved revision.' },
  { prompt: 'The assembled LED lights, but you have not measured resistor voltage. What can you conclude?', options: ['It conducts, but its current and resistor power still need checking', 'The current must match the design estimate', 'The board needs no further test because the LED lights'], correct: 0, why: 'Light alone does not establish current or power; measurements are needed.' },
  { prompt: 'A dark LED may result from an open switch or a reversed LED. Which next test best narrows those causes?', options: ['With cells removed and switch ON, check continuity across its contacts', 'Measure the holder voltage again after it already read normally', 'Replace the LED without testing the switch'], correct: 0, why: 'A direct switch check tests one hypothesis without changing the circuit.' },
  { prompt: 'The revised LED board passes CAD checks but has not been assembled. Which claim belongs in the review?', options: ['File checks passed; physical current and brightness remain unverified', 'The revised board is proven to work as predicted', 'The LED’s typical voltage fixes its actual current'], correct: 0, why: 'CAD results support a file review; physical behavior needs a built and measured board.' },
]

const extraChecks: typeof unitChecks = [
  { prompt: 'You need to check whether two solder pads are accidentally connected. Which setup is appropriate?', options: ['Use continuity mode with the AA cells removed', 'Use continuity mode with the switch OFF but cells installed', 'Use DC voltage mode with the cells removed'], correct: 0, why: 'Continuity testing requires an unpowered circuit and the correct meter mode.' },
  { prompt: 'A resistor has 1 V across it and carries 0.01 A. What is its resistance?', options: ['0.01 Ω', '10 Ω', '100 Ω'] as [string,string,string], correct: 2, why: 'R = V/I = 1 V / 0.01 A = 100 Ω.' },
  { prompt: 'A two-AA pack reads 2.7 V while the LED is on. How should this affect your calculation?', options: ['Use the measured loaded voltage and record the conditions', 'Replace it with 3.0 V because two cells are rated 1.5 V each', 'Assume the meter is wrong because the LED lights'], correct: 0, why: 'Nominal voltage is a rating, not a guaranteed measured value under load.' },
  { prompt: 'You need the LED branch current without moving the meter lead into a current jack. What can you measure?', options: ['Voltage across the known series resistor, then calculate I = V/R', 'Voltage across the battery, then assume all of it is across the resistor', 'Continuity across the powered resistor'], correct: 0, why: 'The measured resistor voltage and known resistance give branch current through Ohm’s law.' },
  { prompt: 'The LED symbol’s cathode is pin 2, but the chosen footprint connects pad 2 to the anode lead. What should happen?', options: ['Keep it because ERC passed', 'Reverse the silkscreen text only', 'Correct the mapping and verify against the exact part drawing'], correct: 2, why: 'Electrical symbol pins, footprint pads, and the physical part must agree.' },
  { prompt: 'A part drawing calls for a larger mounting hole than the footprint provides, though the 3D preview looks fine. What should you do?', options: ['Correct the footprint hole and recheck fabrication rules', 'Trust the 3D preview and order the board', 'Rotate the part until the lead appears centered'], correct: 0, why: 'A 3D preview does not establish the actual drilled hole size or fit.' },
  { prompt: 'The drill file predates a footprint change, but Gerbers are current. Can you release this package?', options: ['Yes, if the drill file name has the current revision', 'No; regenerate and inspect matching drill and Gerber outputs', 'Yes, if all copper tracks are visible'], correct: 1, why: 'The drill locations may have changed with the footprint; manufacturing outputs must match.' },
  { prompt: 'The soldered board looks good, but no supply-short check has been recorded. What should happen before inserting cells?', options: ['Insert cells with the switch OFF to see whether anything heats', 'Rely on the earlier PCB DRC result', 'Check polarity and unintended supply connections unpowered'], correct: 2, why: 'A physical assembly can have faults that CAD checks cannot detect.' },
  { prompt: 'After repairing a suspected open trace, which result supports your explanation?', options: ['The same continuity test changes from open to connected', 'The LED looks brighter but no reading is repeated', 'The battery label still says 1.5 V'], correct: 0, why: 'Repeating the discriminating test shows whether the predicted connection changed.' },
  { prompt: 'Your revised LED design passes DRC but has not been built. What can you claim?', options: ['It will certainly work', 'The configured board checks passed; physical behavior is unverified', 'Its measured current is known'] as [string,string,string], correct: 1, why: 'CAD checks do not establish measured physical behavior.' },
]

const thirdChecks: typeof unitChecks = [
  { prompt: 'On first power the LED lights, but you notice an unusual smell. What is the next step?', options: ['Keep power on to see whether the smell fades', 'Measure current while the board remains powered', 'Remove power and inspect the board before another trial'], correct: 2, why: 'Unusual odor is a stop condition even when the LED lights.' },
  { prompt: 'A jumper accidentally connects the battery holder terminals without the resistor or LED in the path. What should you predict?', options: ['A possible short with excessive current; remove cells', 'The same current as the intended series circuit', 'An open circuit because the LED is outside the path'], correct: 0, why: 'A low-resistance bypass across a battery can draw excessive current.' },
  { prompt: 'The LED is operated at 4 mA, but the datasheet’s typical forward voltage is measured at 10 mA. Which approach fits the evidence?', options: ['Use the listed typical value as an exact 4 mA drop', 'Review the stated conditions and characteristic data for the operating range', 'Assume the battery nominal voltage determines the LED drop'], correct: 1, why: 'Forward voltage changes with operating conditions; the listed point is not an exact value at 4 mA.' },
  { prompt: 'The LED goes dark when moved past the midpoint of a breadboard rail. Which test checks your split-rail hypothesis?', options: ['Measure voltage at the battery holder again', 'Replace the LED before checking the rail', 'Remove cells and check continuity across the midpoint'], correct: 2, why: 'An unpowered check across the suspected split tests the connection directly.' },
  { prompt: 'ERC passes, but the LED cathode is wired to the positive supply in your intended loop. What should you do?', options: ['Review the LED orientation against the exact part and correct the schematic', 'Accept the ERC pass as proof of correct LED direction', 'Change only the board silkscreen mark'], correct: 0, why: 'ERC cannot infer intended LED polarity in every circuit.' },
  { prompt: 'One ratsnest line remains between resistor and LED pads, even though copper appears close. What should you check?', options: ['Whether the silkscreen label bridges the gap', 'The actual copper connection and net assignment', 'Whether the 3D model hides the line'], correct: 1, why: 'A ratsnest line indicates the editor still sees an unrouted connection.' },
  { prompt: 'GerbView has copper and drills but no board outline. What should you inspect before release?', options: ['Only whether the PCB editor currently shows an outline', 'The part datasheet instead of the output layers', 'The edge layer export settings, then regenerate and inspect the files'], correct: 2, why: 'The fabricator receives exported files; a missing outline there must be fixed.' },
  { prompt: 'The assembled LED board lights, but you want to compare current with the design target. What should you record?', options: ['The resistor value and measured voltage across it', 'Only a photo showing the LED is on', 'Only the battery’s printed nominal voltage'], correct: 0, why: 'Resistor voltage and resistance allow an inferred current to compare with the target.' },
  { prompt: 'With a dark LED, you suspect an open switch or a reversed LED. Which result would favor the switch hypothesis?', options: ['The holder voltage is normal', 'With cells removed and switch ON, its contacts still show no continuity', 'The resistor value matches the design'], correct: 1, why: 'An open switch should fail a direct continuity test across its contacts.' },
  { prompt: 'The replacement LED has wider lead spacing. Your board still uses the old footprint. What is required?', options: ['Keep the footprint because ERC passes', 'Bend the leads without checking package limits', 'Update the footprint and board, then rerun checks and outputs'], correct: 2, why: 'A changed package affects the footprint, board layout, and manufacturing outputs.' },
]

export const unitAssessments = unitChecks.map((first, index) => [first, extraChecks[index], thirdChecks[index]].map((check, questionIndex) => ({ ...check, ...assessmentPracticeEdits[`${index}-${questionIndex}`] })))

export const finalReviewItems = [
  'Explain which component data and assumptions the design needs',
  'Explain how to review schematic connections and ERC findings',
  'Explain how footprints, layout, DRC, and schematic parity are checked',
  'Explain how Gerbers and drill files are inspected before ordering',
  'Explain assembly checks and how measurements or faults are recorded',
  'Explain what changes when substituting a different LED',
  'Identify remaining uncertainty and any hands-on work you attempted',
]
