import { learningText } from './learningLanguage'
import { useEffect, useRef } from 'react'
import { courseUnits, firstLessonTitle, lessonById, finalReviewItems } from './courseContent'
import { makeTask } from './learningTasks'
import { COURSE_VERSION, skillEvidence, type LearningRecord as RecordData, type Submission } from './learningStore'
import { skillNames } from './teachingProject'
import { gradePart, type Part } from './taskTypes'
const when=(date:string|number)=>new Date(date).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})
const name=(id:string)=>id==='0.1'?firstLessonTitle:id==='final'?'Independent design review':id.startsWith('unit-')?`Unit ${Number(id.slice(5))+1} check`:id.startsWith('review:')?`Review: ${skillNames[id.slice(7)]}`:lessonById[id]?.title??id
function AnswerEvent({event}:{event:Submission}) {
  const task=event.variantIndex!==undefined?makeTask(event.taskId,event.variantIndex,event.purpose==='final'):Array.from({length:5},(_,i)=>makeTask(event.taskId,i,event.purpose==='final')).find(t=>t.variantId===event.variantId)
  const describe=(part:Part)=>{const answer=event.answers[part.id];if(Array.isArray(answer))return answer.map(id=>part.options?.find(o=>o.id===id)?.label??id).join(' → ');if(answer&&typeof answer!=='string')return`${answer.value} ${answer.unit}`;if(part.id==='photo'&&event.variantIndex===undefined)return `Recorded photograph identity: ${answer}`;return part.options?.find(o=>o.id===answer)?.label??answer??'Not submitted'}
  return <details className="answer-event"><summary>{name(event.activityId)} · {event.phase==='setup'?'Test setup':event.phase==='retest'?'Correction / retest setup':event.correct?'Correct decisions':'Needs correction'} · {when(event.at)}</summary><p>{event.assisted?'Support/correction used':event.repeated?'Previously shown or attempted case':event.firstSubmission?'First submission on this case':'Later submission'} · {event.purpose==='review'?'Retrieval review':event.purpose==='final'?'Final changed task':'Course practice'}</p>{task&&task.variantId===event.variantId&&event.taskVersion===COURSE_VERSION?<dl>{task.parts.filter(p=>event.answers[p.id]!==undefined).map(p=><div key={p.id}><dt>{learningText(p.prompt)}</dt><dd>{learningText(describe(p))}</dd><dd className="record-help">{learningText(gradePart(p,event.answers[p.id]).feedback)}</dd></div>)}</dl>:<p>This event belongs to an earlier task revision. Its recorded outcome is preserved without regrading.</p>}</details>
}
export function LearningRecordView({record,open,reviewOnly=false}:{record:RecordData;open:(id:string)=>void;reviewOnly?:boolean}) {
  const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{heading.current?.focus();window.scrollTo(0,0)},[reviewOnly])
  const skills=Object.entries(skillNames).map(([id,title])=>({id,title,...skillEvidence(record,id)}))
  const ordered=reviewOnly?skills.filter(s=>s.events.length).sort((a,b)=>Number(b.needsPractice)-Number(a.needsPractice)||Number(b.due)-Number(a.due)||(a.dueAt??Infinity)-(b.dueAt??Infinity)):skills
  return <main className="records-main"><span className="lesson-eyebrow">YOUR LEARNING</span><h1 ref={heading} tabIndex={-1}>{reviewOnly?'Review your skills':'Learning record'}</h1><p>See actual decisions, support used and notes. A fresh correct task is evidence for that case, not proof of every PCB skill. Physical work remains self-reported.</p>{reviewOnly&&<p>Review intervals start at 1 day after supported work, 7 after a fresh success, and 21 after a fresh later review. These are initial product choices; reviews never lock course progress.</p>}
  <div className="skill-grid">{ordered.map(s=><article className="skill-card" key={s.id}><h2>{s.title}</h2><strong className={s.needsPractice?'needs-practice':'evidence-label'}>{s.label}</strong><p>{s.independentCount} fresh correct {s.independentCount===1?'case':'cases'} recorded.{s.lastIndependent&&` Latest: ${when(s.lastIndependent.at)}.`}</p>{s.latest&&!s.latest.correct&&<p>Last attempt needs a correction. Use a changed case to check the idea.</p>}{s.dueAt&&<p>{s.due?'Review due':'Next suggested review'}: {when(s.dueAt)}</p>}<button type="button" className="secondary-button" disabled={!s.events.length} onClick={()=>open(`review:${s.id}`)}>{s.needsPractice?'Practice this idea':s.due?'Start due review':'Review now'}</button></article>)}</div>
  {reviewOnly&&ordered.length===0&&<p>Complete some practice to collect evidence and receive review suggestions.</p>}
  {!reviewOnly&&<><h2>Notes and optional work</h2>{Object.entries(record.completions).length===0?<p>No completed activities yet. Submitted attempts are kept below, even if unfinished.</p>:Object.entries(record.completions).sort((a,b)=>b[1].at.localeCompare(a[1].at)).map(([id,value])=><details className="completion-record" key={id}><summary>{name(id)} · {value.legacy?'Earlier course completion':value.physical==='reported'?'Physical/CAD work self-reported':'Conceptual activity recorded'}</summary><p>{when(value.at)}{value.legacy?' · Earlier records do not establish the new task skills.':''}</p><p className="saved-note">{value.note||'No note added.'}</p>{Object.entries(value.fields).map(([field,text])=><p key={field}><strong>{learningText(field)}:</strong> {text||'Pending'}</p>)}{value.reviewStatuses&&<p>{id==='final'?finalReviewItems.filter((_,i)=>value.reviewStatuses?.[String(i)]!=='present').length:Object.values(value.reviewStatuses).filter(s=>s==='pending').length} review topics reported pending.</p>}{value.legacyAttempts&&<p>{value.legacyAttempts.length} earlier completed attempts preserved in the downloadable record.</p>}<button type="button" className="secondary-button" onClick={()=>open(id)}>Practice this activity</button></details>)}
    <h2>Submitted decisions</h2><p>Wrong submissions are saved immediately; leaving or repeating an activity keeps their history.</p>{record.submissions.length===0?<p>No submissions yet.</p>:[...record.submissions].reverse().map(event=><AnswerEvent key={event.id} event={event}/>)}</>}
  <p className="record-help">The course has {courseUnits.length} units. Notes can be read here without retaking a lesson.</p></main>
}
