import { lessonById, type SourceId } from './courseContent.ts'
import { project } from './teachingProject.ts'
import type { Artifact, Choice, Part, TaskCase } from './taskTypes'
import { makeBasicsTask } from './electronicsBasics.ts'
import { explainCalculations } from './calculationExplanations.ts'
const choice=(id:string,prompt:string,options:[string,string,string][],expected:string,explanation:string,skill:string):Part=>({id,prompt,kind:'choice',options:options.map(([id,label,feedback])=>({id,label,feedback})),expected,hint:'Compare the displayed evidence with the requested decision.',explanation,skillIds:[skill]})
const number=(id:string,prompt:string,expected:number,baseUnit:string,hint:string,skill='calculation',units?:string[],tolerance=0.01):Part=>({id,prompt,kind:'number',expected,baseUnit,units:units??({A:['A','mA'],V:['V','mV'],'Ω':['Ω','kΩ'],W:['W','mW'],mm:['mm']} as Record<string,string[]>)[baseUnit]??[baseUnit],tolerance,hint,explanation:`The modeled result is ${Number(expected.toPrecision(6))} ${baseUnit}.`,skillIds:[skill]})
const nodes=(id:string,prompt:string,expected:string[],hint:string,skill='measurement',options:Choice[]=project.terminals.map(p=>({id:p.id,label:p.label,feedback:''}))):Part=>({id,prompt,kind:'nodes',expected,options,hint,explanation:`The relevant points are ${expected.join(' and ')}.`,skillIds:[skill]})
const order=(id:string,prompt:string,options:[string,string][],hint:string,skill='workflow'):Part=>({id,prompt,kind:'order',options:options.map(([id,label])=>({id,label,feedback:''})),expected:options.map(([id])=>id),hint,explanation:'The sequence preserves the required dependencies.',skillIds:[skill]})
const release=(id='release')=>choice(id,'What is justified before release?', [['hold','Hold this package and correct/regenerate it','A found discrepancy must be resolved before this package is released.'],['send','Release the displayed package','The displayed discrepancy is still present; a file name or prior check cannot resolve it.'],['rename','Change only the release name','Renaming does not change the layer, hole, or part mapping.']],'hold','Hold release, correct the source/export, then independently inspect a matching regenerated package.','outputs')
const power=()=>choice('power','Choose the power state for this connection test.',[['removed','Both cells removed','Removing the cells removes this source.'],['off','Cells installed, switch OFF','The switch does not isolate every possible conductor. Remove cells for this continuity test.'],['on','Cells installed, switch ON','Continuity mode must not be used on this powered circuit.']],'removed','Use continuity only with the source removed.','safety')
const mode=()=>choice('mode','Choose the meter function.',[['continuity','Continuity','This tests an unpowered connection.'],['voltage','DC voltage','This particular test asks whether an unpowered connection is intact.'],['current','DC current','A current-mode connection is not the required unpowered path test.']],'continuity','Continuity addresses the selected unpowered connection. Check your own meter manual for its jacks and threshold.','measurement')
const rows=(data:string[][]):Artifact=>({kind:'measurements',variant:0,rows:data})
const calcCases=[{voltage:3.2,ledVoltage:2,resistance:300},{voltage:2.9,ledVoltage:2,resistance:150},{voltage:2.66,ledVoltage:2,resistance:330},{voltage:3.1,ledVoltage:1.9,resistance:240},{voltage:2.8,ledVoltage:1.9,resistance:180}]
const wirePairs=[['R1.2','D1.2'],['S1.2','R1.1'],['BT1+','S1.1'],['D1.1','BT1-'],['S1.1','S1.2']]
export const VARIANTS=5
export function makeTask(id:string,variant=0,finalCase=false):TaskCase {
  const v=variant%VARIANTS
  const item=lessonById[id]
  const t:TaskCase=id.startsWith('E.')?makeBasicsTask(id,v):{id,variantId:`${id}:case-${v}`,title:item?.title??'From idea to tested PCB',context:'Use the displayed revision A teaching example. Physical work remains optional.',artifact:{kind:'circuit',variant:v},parts:[],sources:item?.sources??['K2']}
  const put=(artifact:Artifact,context:string,parts:Part[])=>{t.artifact={...artifact,variant:v};t.context=context;t.parts=parts}
  switch(id){
    case '0.1': {
      const stages:[string,string][]=[['schematic','Draw connections'],['layout','Place pads and route copper'],['outputs','Export/inspect layers and holes'],['bare','Receive and inspect bare PCB'],['tested','Assemble and measure']]
      const ready=['schematic','layout','outputs','bare','tested'][v]
      const descriptions=['Connections are drawn; no physical placement yet.','Pads and copper are reviewed; no manufacturing exports yet.','Matching outputs are inspected; the board has not arrived.','The bare board arrived with no parts installed.','The assembled board has actual measurements.']
      put({kind:'workflow',variant:v,target:ready},descriptions[v],[order('sequence','Put the workflow in dependency order.',stages,'Connections precede physical layout; exports precede receiving the board; assembly and measurement follow receipt.'),choice('stage','Which artifact/state is described?',stages.map(([key,label])=>[key,label,`Compare the described evidence with this stage's job.`]),ready,'The artifact is identified from what has actually been completed.','workflow')]);break
    }
    case '0.2': put({kind:'circuit',variant:v,fault:'cells',target:wirePairs[v].join('|')},`You will move the connection ${wirePairs[v].join(' → ')}. Cells are currently installed.`,[power(),nodes('points','Mark the connection you will inspect after removing cells.',wirePairs[v],'Select the two named ends of the wire you are changing.','loop')]);break
    case '0.3': put({kind:'circuit',variant:v,target:wirePairs[v].join('|')},'The two highlighted terminals in the drawing are the endpoints of a wire you need to check. Both cells have been removed. Choose a meter setting, then select those two terminals.',[mode(),nodes('points','Select the two endpoints highlighted in the drawing.',wirePairs[v],'Probe the two ends of the named connection, rather than the supply or both ends of a component.')]);break
    case '0.4': put(rows([['Check','Observation'],['Power','Cells absent'],['Polarity','Matches reference'],['VCC to GND','Unplanned wire visible'],['S1','ON']]),'Review this pre-power log against the intended series path.',[choice('decision','What should happen next?', [['inspect','Keep cells out and locate the unplanned supply path','The path needs investigation before power.'],['power','Insert cells with S1 OFF','S1 OFF does not resolve the unplanned supply path.'],['continue','Insert cells with S1 ON','The pre-power evidence contains an unresolved unintended connection.']],'inspect','Keep the source out while the unexpected supply path is investigated.','safety'),nodes('supply','Mark the two supply endpoints relevant to this finding.',['BT1+','BT1-'],'The unexpected path joins the holder’s + and − contacts.','loop')]);break
    case '1.1': put({kind:'circuit',variant:v,fault:v%2?'open-wire':'open-switch',target:wirePairs[v].join('|')},'Trace revision A from supply to return. The drawing includes an open; the holder can still retain voltage.',[order('loop','Order the terminals in the intended closed path.',project.terminals.map(x=>[x.id,x.label]),'Start at BT1+, pass S1 and R1, reach D1 anode before cathode, then return.','loop'),choice('current','What does this open do to the single branch?', [['zero','Interrupts branch current','There is no closed series path.'],['supply','Makes the holder voltage necessarily zero','An open path does not discharge the holder or force its voltage to zero.'],['same','Leaves branch current unchanged','Charge cannot circulate around this modeled open series path.']],'zero','The modeled branch is open; battery voltage may remain.','loop')]);break
    case '1.2': {
      const target=v%2?'D1':'R1';const pair=target==='R1'?['R1.1','R1.2']:['D1.2','D1.1']
      put({...calcCases[v],kind:'circuit',variant:v},`Find the voltage across ${target}, then interpret what that measurement compares.`,[nodes('points',`Select the two ${target} ends.`,pair,`Across ${target} means its own two ends, not the holder ends.`),choice('meaning','What does a voltage measurement compare?', [['voltage','Potential at the two selected points','That is a voltage difference.'],['current','Charge flow at one point','A two-probe voltage measurement does not directly measure branch current.'],['resistance','Resistance of the powered LED','This request is a voltage comparison, not a resistance-mode test.']],'voltage','Voltage compares the potentials of the selected endpoints.','measurement')]);break
    }
    case '1.3': {const a=[6,12,8,15,3][v],k=[2.2,1.5,3.3,4.7,0.68][v];put(rows([['Given','Value'],['Current',`${a} mA`],['Resistance',`${k} kΩ`]]),'Express both values in the requested equivalent units.',[number('current','Express the given current in amperes.',a/1000,'A','Divide mA by 1000 to get A.','units',['A'],0.000001),number('resistance','Express the resistance in ohms.',k*1000,'Ω','Multiply kΩ by 1000 to get Ω.','units',['Ω'],0.01)]);break}
    case '1.4': {const {resistance:r,voltage:vs,ledVoltage:vf}=calcCases[v];const vr=vs-vf;put(rows([['Fixed condition','Value'],['R1 voltage',`${vr.toFixed(2)} V`],['Original R1',`${r} Ω`],['Changed R1',`${r*2} Ω`]]),'For this comparison only, hold the voltage across the resistor fixed.',[choice('direction','Predict the changed current.',[['half','Half the original current','At fixed V, doubling R halves I.'],['double','Twice the original current','Resistance is the divisor in I=V/R.'],['same','Unchanged','The fixed voltage does not cancel the change in resistance.']],'half','This is a fixed resistor-voltage comparison, not a fixed LED model.','calculation'),number('current','Calculate the current with the changed R1.',vr/(r*2),'A','Use the displayed resistor voltage divided by the changed resistance.','calculation',undefined,0.000001)]);break}
    case '1.5':case '3.4':case '8.3': {
      const x=calcCases[v],vr=x.voltage-x.ledVoltage;
      put({...x,kind:'circuit',variant:v},'The labels below the diagram give the battery voltage, LED-anode voltage above battery negative, and resistor value. The switch is closed, so R1.1 is at battery-positive voltage. Find the voltage between R1.1 and R1.2 before calculating current.',[nodes('points','Choose the resistor-voltage endpoints.',['R1.1','R1.2'],'Use the two R1 ends; supply endpoints would include the LED voltage too.'),number('voltage','What voltage is across R1?',vr,'V','Subtract the LED-side potential from the supply-side potential. Do not assign the full supply voltage to R1.','measurement',undefined,0.001),number('current','Infer branch current, with its unit.',vr/x.resistance,'A','Use the resistor voltage divided by its resistance. If you used the full supply, first remove the LED voltage.','calculation',undefined,0.00001)]);break
    }
    case '1.6': put({kind:'circuit',variant:v,fault:v%2?'open-wire':'bypass',target:wirePairs[v].join('|')},'Inspect the extra/missing connection in this drawing against revision A.',[choice('finding','What changed electrically?', [['bypass','R1 has an additional path around it','Look for a wire connecting the two R1 ends.'],['open','A required series connection is absent','Look for the visible break in an intended wire.'],['normal','Only a harmless drawing position changed','Connectivity has changed, not merely the page layout.']],v%2?'open':'bypass',v%2?'The missing wire opens the single series path.':'The extra wire bypasses intended current limiting.','loop'),choice('power','Choose the next power state.',[['removed','Keep cells removed while correcting','Correct this connection unpowered.'],['on','Power to see the effect','An unreviewed bypass/open is not an approved first-power state.'],['off','Keep cells installed with S1 OFF','Removing the source is required before rewiring.']],'removed','Correct and inspect this model before any real powered trial.','safety')]);break
    case '2.1':case '4.4': {
      put({kind:'footprint',variant:v,fault:'mapping'},'Reference: KiCad Device:LED pin 1=K/GND, pin 2=A/LED_A. The WP7113ID drawing identifies the physical cathode. Compare the candidate pad maps.',[choice('candidate','Which candidate preserves the complete mapping?', [['a','Candidate A: 1→A, 2→K','This swaps the anode and cathode relative to the selected symbol.'],['b','Candidate B: 1→K, 2→A','This preserves the selected symbol numbering and reference nets.'],['c','Either, because pitch is equal','Physical pitch does not establish electrical mapping.']],'b','Pin, pad, physical polarity and net must all agree.','mapping'),nodes('cathode','Select the reference cathode terminal.',['D1.1'],'This project’s selected symbol maps cathode K to pin 1.','mapping')]);break
    }
    case '2.2':case '9.1': {
      const green=id==='9.1';const parameter=v%3
      const dataset: string[][]=green?[['WP7113SGC','Value'],['Forward voltage typical','2.2 V'],['Forward voltage maximum','2.5 V'],['Test current IF','20 mA'],['Ambient TA','25 °C']]:[['WP7113ID, Rev V.14A','Value'],['Forward voltage typical','1.9 V'],['Forward voltage maximum','2.3 V'],['Test current IF','10 mA'],['Ambient TA','25 °C'],['Absolute maximum DC current','30 mA']]
      put({kind:'datasheet',variant:v,rows:dataset},'This excerpt transcribes the identified manufacturer parameter table. Keep the value, column and conditions together; use the original source for a real part decision.',[number('value',parameter===0?'Extract the typical forward voltage.':parameter===1?'Extract the maximum forward voltage.':'Extract the forward-voltage test current.',parameter===0?(green?2.2:1.9):parameter===1?(green?2.5:2.3):(green?0.02:0.01),parameter===2?'A':'V','Find the requested row/column in the excerpt. A maximum, typical value and test current have different roles.','datasheet',undefined,0.00001),choice('conditions','Which condition belongs with the forward-voltage row?', [['source',`IF=${green?'20':'10'} mA, TA=25 °C`,'These are the displayed test conditions.'],['target','The project target current, at any temperature','A chosen target is not the manufacturer’s test condition.'],['nominal','Two cells nominally total 3 V','A battery nominal rating is not the LED parameter’s test condition.']],'source','Keep the row’s current and temperature with its forward-voltage value.','datasheet'),choice('use','What can you claim at a different target current?', [['estimate','The listed typical value is a reference point, not a guaranteed target-current drop','The reference point has stated conditions.'],['exact','The LED must have exactly this typical drop','Typical does not guarantee every part or operating point.'],['maximum','The maximum column defines every possible operating condition','The maximum applies to its stated test conditions, not every current/temperature.']],'estimate','A real operating point needs relevant data/measurement; this excerpt alone does not fix it.','evidence')]);if(green)t.sources=['C3','C1'];break
    }
    case '2.3': {const target=[4,3,5,4,6][v];put(rows([['Trial current','Modeled visibility'],[`${target-1} mA`,'Hard to see'],[`${target} mA`,'Readable'],[`${target+2} mA`,'Readable']]),`Requirement: readable. Project ceiling: ${target+1} mA. Choose the lowest tested current that meets both. These visibility results are supplied examples, not physical guarantees.`,[number('target','Choose that target current.',target/1000,'A','Compare each tested observation with readability and the stated project ceiling.','datasheet',undefined,0.000001),choice('limit','What evidence is needed for an actual build?', [['part','Exact LED limits, resistor power and a real visibility check','The modeled table is insufficient for a physical claim.'],['rating','Only the absolute maximum LED current','A maximum is not a desired visibility target and does not verify this build.'],['label','Only nominal battery voltage','A nominal supply label establishes neither target current nor visibility.']],'part','Verify the selected parts and physical visibility under the intended conditions.','evidence')]);break}
    case '2.4':case '9.2': {const targets=[5,4,6,3,2],i=targets[v]/1000;const vs=id==='9.2'?3.2:3,vf=id==='9.2'?2:1.8;const r=(vs-vf)/i;put(rows([['Supplied assumption','Value'],['Supply',`${vs} V`],['LED voltage',`${vf} V`],['Target',`${targets[v]} mA`],['Range-case supply',`${vs+0.2} V`],['Range-case LED voltage',`${vf-0.1} V`]]),'Calculate the nominal resistance, then evaluate the supplied range case using that resistance. These voltage bounds are exercise assumptions.',[number('resistance','Calculate the nominal resistance.',r,'Ω','Subtract LED voltage from supply and divide by target current in A.','calculation',undefined,0.05),number('range','What current does the range case imply?',(vs+0.2-(vf-0.1))/r,'A','Use the range-case supply and LED voltage, with your nominal resistance.','calculation',undefined,0.00001),choice('claim','Does the nominal target establish the real current?', [['no','It is a modeled estimate that still needs part/range and physical checks','The supplied assumptions are not a measurement of a board.'],['yes','It establishes exact physical current','Part variation and actual supply are not fixed by this exercise.'],['rating','It establishes LED maximum current','A chosen model target is not the manufacturer’s rating.']],'no','Keep this calculation distinct from a physical guarantee.','evidence')]);break}
    case '2.5': {const r=[200,220,300,150,330][v],i=[5,6,4,8,3][v]/1000;put(rows([['Illustrative resistor specification','Value'],['Resistance',`${r} Ω ±5%`],['Sample current',`${i*1000} mA`],['Chosen project condition','Room ambient; require rating ≥ 2× calculated dissipation'],['Available example ratings','0.005 W / 0.125 W / 0.25 W']]),'The specification/rating choices are teaching data; no actual resistor is selected. The 2× condition is a project choice, not a universal standard.',[number('power','Calculate sample dissipation.',i*i*r,'W','Convert current to A, square it, then multiply by resistance.','calculation',undefined,0.00001),number('low','Calculate the low resistance bound.',r*0.95,'Ω','Subtract 5% of nominal resistance.','calculation',undefined,0.01),number('high','Calculate the high resistance bound.',r*1.05,'Ω','Add 5% of nominal resistance.','calculation',undefined,0.01),choice('rating','Which smallest offered rating meets the stated project condition?', [['small','0.005 W','This is below twice this sample dissipation.'],['mid','0.125 W','Compare it with twice the displayed calculated dissipation.'],['large','0.25 W','This meets the bound but is not the smallest offered rating that does.']],'mid','0.125 W meets this stated exercise condition; physical approval still needs the actual part and ambient/derating documentation.','datasheet')]);break}
    case '2.6':case '4.2': put({kind:'switch',variant:v},'The illustrative switch closes 1–2 in ON and 1–3 in OFF. Revision A must conduct in ON. Exact physical switch selection remains unresolved.',[nodes('contacts','Select the contacts to use.',['S1.1','S1.2'],'Use the ON contact pair shown in this contact diagram.','mapping',[1,2,3].map(x=>({id:`S1.${x}`,label:`S1 pin ${x}`,feedback:''}))),choice('unused','What happens to the third contact in this circuit?', [['separate','Keep it separate and document it as unused','This circuit uses the ON pair only.'],['ground','Join it to GND','That would change the switch’s OFF connection and can create an unwanted supply path.'],['bridge','Bridge all three pads','That removes the intended switching function.']],'separate','Keep the unused contact separate; check the exact real switch before assigning a physical footprint.','mapping')]);break
    case '2.7':case '8.2':case '8.5': {
      const pair=wirePairs[v],switchTest=v===4;const intact=v%2===0
      const target=pair.join('|');t.revealAfter=5
      put({kind:'circuit',variant:v,target,observation:intact?'Continuity: connection intact in this model.':'No continuity: this intended connection is open in the model.'},`LED is dark. Candidates: ${switchTest?'S1 remains open in ON':'an open in '+pair.join('–')} or reversed D1. Supply was already checked. Model has no parallel path between these test endpoints; remove cells before the connection test.`,[power(),mode(),nodes('points','Select the test endpoints that separate these candidates.',pair,'Test the intended suspect connection directly; another component or the holder does not answer this connection question.'),choice('predict-open','Predict the result for the open-connection candidate.',[['open','No continuity','An open does not provide this low-resistance path.'],['closed','Continuity','The open candidate interrupts this very path.']],'open','The open candidate predicts no continuity.','diagnosis'),choice('predict-reversed','Predict the result for reversed D1 with this connection intact.',[['open','No continuity','Reversing D1 does not open this separately tested wire/contact in this model.'],['closed','Continuity','This candidate keeps the tested connection intact.']],'closed','The intact connection predicts continuity; the hypotheses are discriminated.','diagnosis'),choice('conclusion','What does the revealed result support?', [['open','Supports an open at the tested connection','Use the returned result for these exact endpoints.'],['intact','Rules out this modeled open, while polarity still needs inspection','Use the returned result; continuity does not independently prove D1 polarity.'],['proved','Proves D1 is reversed','A connection test is not a polarity inspection.']],intact?'intact':'open',intact?'This wire is intact in the model. Inspect exact LED polarity next.':'The open result supports this connection hypothesis in the supplied model.','diagnosis'),choice('next','Choose the next evidence/action.', [['polarity','Inspect D1 physical/symbol/pad polarity','This is the remaining candidate after the modeled connection was found intact.'],['repair','Correct the modeled open, then repeat the same endpoint test','This follows a supported open-connection finding.'],['supply','Repeat only the already-confirmed supply test','That would not resolve the result of this discriminating connection test.']],intact?'polarity':'repair',intact?'Use the exact drawing and mapping before changing D1.':'Make a correction unpowered and repeat the same relevant test.','diagnosis')]);break
    }
    case '3.1':case '3.2':case '3.6': {const row=[5,6,8,10,12][v],dest=row+3;const opts=['a','e','f','j'].flatMap(letter=>[row,row+1,dest].map(n=>({id:`${letter}${n}`,label:`${letter}${n}`,feedback:''})));const art:Artifact={kind:'breadboard',variant:v,target:String(row),fault:id==='3.2'?'jumper':id==='3.6'?'rail':'groups'}
      if(id==='3.1')put(art,`Use the displayed internal strips: a–e and f–j are separate on each numbered row. Rail segments are also separate across the marked break.`,[nodes('strip',`Select both a${row} and its far-end connected hole.`,[`a${row}`,`e${row}`],'Stay on the same numbered a–e strip; do not cross the center gap or change row.','breadboard',opts),choice('rail','Does the pictured midpoint rail break connect its two segments?', [['no','No; they are separate in this model','The drawing explicitly contains a split.'],['yes','Yes; their stripe color is the same','Color is a label, not an electrical connection.']],'no','Check actual board topology with cells removed.','breadboard')])
      else if(id==='3.2')put(art,`R1 output is on e${row}; D1 anode is on a${dest}. Compare the jumper’s drawn destination with that required net. Cells are absent.`,[nodes('jumper','Select the intended jumper endpoints.',[`e${row}`,`a${dest}`],'The R1 output and D1 anode must share this net; an adjacent row does not connect internally.','breadboard',opts),power()])
      else put(art,'A normal supply and dark LED could fit a split rail or reversed D1. Define the test before interpreting it.',[power(),nodes('rail','Choose points on opposite sides of the midpoint split.',['rail-top','rail-bottom'],'Both points must bound the suspected split; two points on one segment cannot test it.','breadboard',[{id:'rail-top',label:'Upper rail endpoint',feedback:''},{id:'rail-bottom',label:'Lower rail endpoint',feedback:''},{id:'rail-upper-mid',label:'Upper segment middle',feedback:''}]),choice('result','The model returns no continuity across the split. What follows?', [['bridge','This rail path is open; bridge the required net unpowered and retest','The observed split supports this connection hypothesis.'],['led','This proves D1 is reversed','The rail test does not inspect LED orientation.'],['battery','The cells have no voltage','A continuity result on an unpowered rail does not measure the cells.']],'bridge','Repair the intended rail connection and repeat the same endpoint test.','diagnosis')]);break
    }
    case '3.3': put({...calcCases[v],kind:'circuit',variant:v},'The meter’s red probe is at BT1− and black probe at BT1+. The inspected powered model gives a negative holder voltage.',[choice('mode','Choose the meter setup for this reading.',[['voltage','COM and voltage jack, DC V','These match a two-point DC voltage test; follow the exact meter instructions.'],['current','COM and current jack, DC A','Across a supply, current-mode connections can short it; this is not a current test.'],['continuity','COM and resistance jack, continuity','This powered measurement requires voltage mode.']],'voltage','Use the exact meter’s voltage setup, never current mode across the holder.','measurement'),choice('sign','What explains the displayed negative sign?',[['reversed','Red is lower in potential than black','That follows these shown endpoints.'],['empty','Both cells must be empty','The sign alone does not show the source is empty.'],['open','The switch must be open','The holder sign is defined by probe polarity, not this inference.']],'reversed','Verify the points and reference before concluding a source failure.','measurement'),nodes('points','Select the holder endpoints for this voltage reading.',['BT1+','BT1-'],'Use the two holder contacts. R1 endpoints would measure resistor voltage.')]);break
    case '3.5': {const r=[200,300,220,150,330][v],vs=[2.7,2.8,2.9,2.6,2.75][v],vf=[1.9,2,1.8,1.9,1.85][v];put(rows([['Quantity','Model','Sample observation'],['Supply','3.0 V',`${vs} V`],['LED','2.0 V',`${vf} V`],['R1',`${r} Ω`,`${r} Ω assumed known`]]),'Compare the supplied observations with the model before proposing a component change.',[number('vr','Calculate observed resistor voltage.',vs-vf,'V','Use the observed supply minus observed LED voltage.','measurement',undefined,0.001),number('current','Recalculate observed current.',(vs-vf)/r,'A','Use the changed resistor voltage and the stated known resistance.','calculation',undefined,0.00001),choice('claim','What explains the modeled discrepancy?', [['values','Changed supply/component voltages can explain it','The sample changed quantities directly affect V/R.'],['fault','The sample proves the LED is defective','Different current alone does not establish this fault.'],['nominal','The observed supply must be replaced by nominal 3 V','A nominal rating cannot override the supplied loaded observation.']],'values','The supplied values explain the model difference; physical uncertainty remains.','evidence')]);break}
    case '4.1': put({kind:'files',variant:v,rows:[['Folder','Project','Schematic','PCB'],['current/A','LED_A','A','A'],['archive','LED_A','A−1','A−1'],['mixed','LED_A','A','A−1']]},'Choose a consistent project, then order the creation steps. Filenames alone do not verify revision.',[choice('folder','Which folder supplies the intended matching A pair?', [['current','current/A','Its two artifacts belong to A.'],['archive','archive','Its consistent pair belongs to an older revision.'],['mixed','mixed','Its board and schematic differ in revision.']],'current','Use the folder with the intended matching schematic and PCB.','workflow'),order('create','Order the project setup.',[['new','File → New Project / wizard'],['save','Save named project folder'],['schematic','Open/save schematic'],['board','Open/save corresponding PCB']],'Create/save the project before editing the corresponding schematic/PCB.')]);break
    case '4.3': put({kind:'junction',variant:v,fault:'junction',target:v%2?'X2':'X1'},'The intended connection after the switch (SW) joins S1.2 to R1.1. Find the marked crossing that needs a junction dot. The other crossing must stay separate.',[choice('join','Which marked crossing needs the intended SW junction?', [['X1','X1','Compare its reached pins and dot with the SW requirement.'],['X2','X2','Compare its reached pins and dot with the SW requirement.'],['both','Both crossings','The other crossing belongs to independent nets and must stay separate.']],v%2?'X2':'X1','Add the intended dot and highlight the SW net again.','schematic'),nodes('net','Which reference pins must SW reach?',['S1.2','R1.1'],'SW joins switch output and resistor input, not both resistor ends.','schematic')]);break
    case '4.5': put({kind:'rules',variant:v,rows:[['ERC exercise finding','Reference intent'],['R1.1 unconnected','Connect to SW/S1.2'],['S1.3 unused','Deliberately separate'],['No supply polarity inference','Human review required']]},'Resolve findings by intended connectivity, not by hiding the report.',[nodes('required','Select the connection R1.1 needs.',['R1.1','S1.2'],'The required SW net joins R1 input to the switch output.','schematic'),choice('unused','What disposition fits genuinely unused S1.3?', [['nc','Document/mark it no-connect after confirming the contact map','This applies only to the confirmed unused contact.'],['all','Apply no-connect to R1.1 too','R1.1 is required by the reference loop.'],['ground','Wire S1.3 to return to remove its warning','That changes the switch circuit and can create a supply path.']],'nc','Only an intentionally unused contact can receive this disposition. Rerun checks after the required fix.','rules')]);break
    case '4.6': put({kind:'circuit',variant:v,fault:'reversed-led'},'The report is rule-clean. Compare the shown LED polarity with revision A, using the labels rather than the report alone.',[choice('finding','Which functional relationship conflicts with the reference?', [['led','D1 cathode faces LED_A instead of return','Compare K/A orientation with the reference nets.'],['s1','S1 ON uses contacts 1–2','That is the intended ON pair.'],['r','R1 is in the series path','That preserves current limiting, rather than describing this mismatch.']],'led','Resolve the LED polarity/net relationship and rerun the checks.','schematic'),nodes('cathode','Where should the cathode return connect?',['D1.1','BT1-'],'K is D1.1 in this symbol and belongs on the return/GND net.','mapping')]);break
    case '5.1': {const targets=['silk','copper','mask','outline','drill'];const roles=['printed D1 polarity','R1-to-LED conducting path','pad opening in protective coating','manufactured board boundary','hole centers and sizes'];put({kind:'board',variant:v},`Select the layer/output for ${roles[v]}. Toggle the viewer to inspect what each contains.`,[choice('layer','Which role supplies that feature?',targets.map((x,i)=>[x,['Silkscreen','Copper','Solder mask','Edge.Cuts outline','Drill data'][i],`That role supplies ${roles[i]}, rather than ${roles[v]}.`]),targets[v],'Layer roles determine what the exported geometry means.','layout'),choice('printed','Does a printed silkscreen line carry the intended current?', [['no','No; the intended net needs connected copper','Printed assembly guidance is not an electrical route.'],['yes','Yes; touching pad drawings is enough','Silkscreen overlap does not join the copper net.']],'no','Check the copper endpoints and net assignment.','layout')]);break}
    case '5.2': put({kind:'footprint',variant:v,rows:[['Geometry','WP7113ID drawing','Candidate'],['Pitch','2.54 mm','2.54 mm'],['Recommended holes','0.9 mm','0.7 mm'],['Pad map','Pin 1: cathode (K) / pin 2: anode (A)','Pin 1: cathode (K) / pin 2: anode (A)']]},'The candidate is illustrative. Compare each dimension with the drawing; physical fit and fabrication tolerances remain to be validated.',[number('pitch','Extract the reference pitch.',2.54,'mm','Use the reference drawing column, not a 3D impression.','footprint',['mm'],0.001),choice('difference','Which candidate feature differs from the drawing recommendation?', [['hole','Its 0.7 mm holes','The recommended hole value is different.'],['pitch','Its 2.54 mm pitch','The displayed pitch matches.'],['map','Its Pin 1: cathode (K) / pin 2: anode (A) mapping','The displayed selected-symbol mapping matches.']],'hole','Resolve the hole recommendation and actual lead/service tolerances before approving a real footprint.','footprint')]);break
    case '5.3':case '5.7': {const min=[0.15,0.2,0.18,0.25,0.16][v],bad=min-0.05;put({kind:'rules',variant:v,rows:[['Illustrative clearance policy','Value'],['Required minimum',`${min.toFixed(2)} mm`],['Entered rule',`${bad.toFixed(2)} mm`],['Gap A',`${(min-0.02).toFixed(2)} mm`],['Gap B',`${(min+0.08).toFixed(2)} mm`],['Chosen project target',`${(min+0.05).toFixed(2)} mm`]]},'These are an exercise service policy and project target, not current JLCPCB limits. Compare the configured check with the policy.',[number('rule','Enter the chosen project clearance target.',min+0.05,'mm','Use the stated project target. Distinguish that choice from the minimum.','rules',['mm'],0.001),choice('gap','Which gap violates the required policy?', [['a','Gap A','Compare its distance with the required minimum.'],['b','Gap B','This distance exceeds the required minimum.'],['none','Neither, because the old DRC passed','The old check used a smaller rule than required.']],'a','Correct the geometry against the updated rules, then rerun DRC.','rules'),choice('parity','What separately checks PCB connections against its schematic?', [['parity','Schematic parity in the project DRC workflow','This comparison needs the corresponding schematic/project.'],['3d','Only the 3D preview','A visual model does not compare schematic connectivity.'],['standalone','Standalone PCB mode with no schematic','The parity option has no effect without the corresponding schematic context.']],'parity','Run parity in the project workflow and inspect its results.','rules')]);break}
    case '5.4': put({kind:'board',variant:v,fault:'placement'},'The gray holder envelope blocks candidate A. Candidate B is inside the board with actuator access; candidate C crosses the board edge.',[choice('place','Choose a usable switch placement.', [['a','Candidate A','The holder envelope blocks its actuator.'],['b','Candidate B','It is accessible and remains within the shown boundary.'],['c','Candidate C','The shown body crosses the intended boundary.']],'b','Use a placement that preserves access and geometry, then check exact part dimensions.','layout'),choice('proof','Does a clean DRC establish finger access?', [['no','No; human use/assembly review is needed','DRC checks configured geometric/electrical rules.'],['yes','Yes; DRC predicts how the user reaches it','Finger access is outside this configured rule check.']],'no','Keep access review alongside DRC.','evidence')]);break
    case '5.5': {const pair=wirePairs[v===4?0:v];const net=project.terminals.find(x=>x.id===pair[0])!.net;put({kind:'board',variant:v,fault:'unrouted',target:pair.join('|')},'One expected connection is shown as an unrouted dashed line. Select the two pads at the ends of that dashed line and their connection name to add a copper route in this exercise.',[nodes('route','Select the two missing-route pads.',pair,'Follow the dashed intended connection; do not bridge across R1.','layout'),choice('net','Which net must this route carry?', ['VCC','SW','LED_A','GND'].map(x=>[x,x,'Compare the selected pad net labels with this net.']),net,'Both route endpoints belong to the same reference net.','layout'),number('count','After the modeled missing route is correctly added, what unrouted count remains?',0,'connections','This exercise has one missing route. Completing it leaves none.','layout',['connections'],0)]);break}
    case '5.6': put({kind:'board',variant:v,fault:'edge-gap',target:v%2?'top':'right'},'Compare the actual edge geometry and D1 assembly mark with the approved reference.',[choice('edge','Locate the outline gap.',[['top','Top edge','Trace the top edge join.'],['right','Right edge','Trace the right edge join.'],['bottom','Bottom edge','The bottom edge is continuous in this example.']],v%2?'top':'right','Close the actual geometry on Edge.Cuts, then rerun its check.','layout'),nodes('mark','Select the pad beside which K belongs.',['D1.1'],'The selected symbol maps K to D1.1, not D1.2.','mapping')]);break
    case '5.8': put({kind:'board',variant:v,fault:'polarity'},'The reference maps D1.1 to K/GND. Independently compare copper and the printed assembly mark.',[choice('finding','Which review finding needs correction?', [['mark','The K mark points to D1.2','That conflicts with this selected symbol/part mapping.'],['return','D1.1 connects to GND','That is the intended return relationship.'],['route','R1.2 connects to D1.2','That is the intended LED_A net.']],'mark','Correct the misleading assembly mark and regenerate affected outputs.','mapping'),release()]);break
    case '6.1':case '6.4':case '9.3': {const changed=id!=='6.1';put({kind:'files',variant:v,rows:changed?[['Artifact','Revision/geometry'],['Approved board','B: wider teaching LED pitch'],['Gerbers','B'],['Drills','A: old pitch'],['BOM','B']]:[['Artifact','Revision'],['Approved board','A'],['Gerbers','A'],['Drills','A−1'],['BOM','A']]},'Inspect the actual inventory and relationships. Labels and geometry must agree; the changed-pitch case is hypothetical.',[choice('stale','Which output must be regenerated from the approved board?', [['drill','Drill data','Its revision/holes are inconsistent with the approved board.'],['name','Only the project name','A name cannot change stale holes.'],['bom','Only the BOM','The stated BOM already matches the approved revision.']],'drill','Regenerate the approved holes and inspect them with matching layer outputs.','outputs'),order('sequence','Order the correction/release steps.',[['design','Resolve source design/mapping'],['checks','Run configured checks and human review'],['export','Export matching layers and drills'],['inspect','Inspect the actual package independently'],['freeze','Freeze that matching revision']],'Checks follow the corrected source; independent output review follows export.'),release()]);break}
    case '6.2': {
      const faults=['missing-mark','drill-shift','missing-outline','drill-shift','missing-mark'];const fault=faults[v],layer=fault==='missing-mark'?'silk':fault==='missing-outline'?'outline':'drill';put({kind:'package',variant:v,fault},'Compare the exported view with the approved reference. Files are present in the manifest, but content must also match. Toggle layers; the viewer is an illustrative inspection model.',[choice('layer','Which layer/output exposes the discrepancy?', [['silk','Top silkscreen','Compare the actual printed features with the reference.'],['drill','Drill data over copper','Compare actual hole and pad centers.'],['outline','Edge.Cuts outline','Compare the actual exported boundary.']],layer,'Use the layer that actually contains the differing feature.','outputs'),choice('finding','What differs from the reference?', [['mark','D1 K mark is absent','Compare silkscreen contents, not only its filename.'],['hole','D1.1 hole center is displaced','Compare the hole overlay with its copper pad.'],['edge','The exported outline is absent','Inspect the exported boundary layer.']],fault==='missing-mark'?'mark':fault==='missing-outline'?'edge':'hole','A specific output discrepancy requires correction and a new package inspection.','outputs'),release()]);break
    }
    case '6.3':case '7.1': put({kind:'package',variant:v,fault:'missing-hole'},id==='6.3'?'The illustrative upload preview differs from the inspected local reference. Compare holes before any payment.':'Compare the illustrative receiving view with the approved geometry. No actual received board is being inspected.',[nodes('hole','Select the reference pad whose expected hole is missing.',['D1.1'],'Compare each expected pad/hole center with the actual view.','footprint'),choice('compare','What should the review compare?', [['files','Approved drill geometry, actual uploaded/received geometry and revision','These are the relevant artifacts.'],['color','Only board color','Color does not resolve a hole discrepancy.'],['speed','Only shipping speed','Shipping cannot change the missing geometry.']],'files','Resolve whether the source files, upload or received board differs before proceeding.','outputs'),release()]);break
    case '7.2': {const faults=['iron','extraction','cells','clutter','eyes'];put({kind:'station',variant:v,fault:faults[v]},'Inspect this illustrative station before heating/soldering. Follow your own equipment/material instructions and appropriate fume-control requirements.',[choice('concern','Identify the setup issue shown.',faults.map((x,i)=>[x,['Iron left on bench','Fume capture obstructed','Cells installed on work board','Flammable clutter near work','Eye protection absent'][i],`Compare this control with the station drawing; more than a generic ventilation label is needed.`]),faults[v],'Correct the shown setup issue before proceeding with physical soldering.','safety'),choice('material','Which source must also be checked for your own setup?', [['instructions','Equipment instructions and solder/flux SDS','They describe the selected equipment and materials.'],['voltage','Only nominal AA voltage','Low supply voltage does not remove hot-tool/material hazards.'],['drc','Only PCB DRC','CAD rules do not establish workstation preparation.']],'instructions','Use the selected materials/equipment guidance, with the cited safety principles.','safety')]);t.sources=['A1','S1','S2'];break}
    case '7.3': put({kind:'joints',variant:v,fault:'procedure'},'Check orientation before a joint, then order the process. Reference photographs provide examples; physical technique remains self-reported.',[nodes('orientation','Select D1 cathode’s intended pad.',['D1.1'],'K maps to pad 1/GND in this project.','mapping'),order('joint','Order the joint-making steps.',[['inspect','Verify mapping; cells removed'],['heat','Heat pad and lead together'],['feed','Feed solder to heated joint and allow wetting'],['cool','Remove solder/iron; cool without movement'],['recheck','Inspect and trim with eye protection']],'Wetting needs heated pad and lead; inspection follows cooling.','assembly')]);t.sources=['C1','A2','S2'];break
    case '7.4': {const concern=v%2?'wetting':'bridge';put({kind:'joints',variant:v,fault:concern},`Inspect photographs A–C. Find the ${concern==='bridge'?'unwanted connection between adjacent pads':'joint where solder has not wetted the pad'}. Use visible structure rather than brightness/shine alone.`,[choice('photo','Which photograph shows that concern?', [['bridge','Photo of adjacent bridged pads','Inspect whether solder physically spans the gap.'],['wetting','Photo of solder on a lead with poor pad wetting','Inspect contact with the pad surface.'],['good','Reference header joints','These provide the comparison; shine alone cannot classify all joints.']],concern,'The selected structure identifies a concern to investigate, not every hidden electrical condition.','assembly'),choice('recheck','After unpowered correction, what supports the repair?', [['repeat','Repeat relevant visual and unpowered path checks','This compares the corrected joint/path with its intended relationship.'],['shine','Only confirm that solder looks shiny','Appearance alone cannot verify the intended connection.'],['power','Insert cells without an unpowered recheck','The correction should be inspected before power.']],'repeat','Inspect and repeat the relevant test while cells are absent.','assembly')]);t.sources=['A3','M2'];break}
    case '7.5': put(rows([['Unpowered path','Intended relationship','Observation'],['A–B','Jumper connects these points','Continuity'],['C–D','No intended path; no other installed route in model','Continuity'],['E–F','Open switch in OFF','No continuity']]),'All cells are removed. Interpret the supplied connectivity model; a real populated board may have alternative paths.',[choice('unexpected','Which observation conflicts with the model?', [['ab','A–B','A planned jumper predicts continuity.'],['cd','C–D','The supplied model has no intended or alternate path here.'],['ef','E–F','An open switch predicts no continuity.']],'cd','Investigate C–D in this isolated model. On a real board, trace/isolate legitimate paths before declaring a bridge.','measurement'),choice('conclusion','Does a beep by itself identify solder as the cause?', [['no','No; it identifies a low-resistance path under that meter’s conditions','The cause requires path/visual evidence.'],['yes','Yes; every beep proves a solder bridge','Installed components and intended paths can also produce a beep.']],'no','Use actual connectivity, meter limits and inspection to identify the cause.','diagnosis')]);break
    case '7.6': {const stop=v%2===0;put(rows([['First-power sample log','Observation'],['Prior checks','Polarity/path checks passed'],['LED','ON'],['Odor',stop?'Unexpected odor':'No unusual odor'],['Heat','No unusual heat reported'],['Resistor',`${calcCases[v].resistance} Ω`],['Resistor voltage',`${(calcCases[v].voltage-calcCases[v].ledVoltage).toFixed(2)} V`]]),'Decide from the complete log; an ON LED does not override a stop condition.',[choice('action','What action follows this log?', [['stop','Remove power and inspect before another trial','Unexpected odor is a stop condition even with light.'],['record','Continue the planned voltage record under the stated normal conditions','This applies only when no stop condition is present.'],['complete','Claim all physical behavior verified because LED is ON','Light alone does not verify current, power or all assembly conditions.']],stop?'stop':'record',stop?'Remove the source; investigate before another trial.':'No displayed stop condition occurs; record the relevant planned measurements.','safety'),choice('claim','What does “LED ON” establish by itself?', [['light','The sample LED conducts/emits; current still needs its measurement','The observation is limited.'],['target','Current exactly matches the design target','Brightness alone does not supply current.'],['all','Every solder joint is correct','The observation does not inspect every joint.']],'light','Current and other physical claims need their own evidence.','evidence')]);break}
    case '8.1': put(rows([['Available evidence','Result'],['Visual observation','LED dark'],['Supply sample','3.0 V'],['Candidate 1','Open switch'],['Candidate 2','Reversed LED']]),'Separate the observation from its possible explanations, then select useful evidence.',[choice('symptom','Which is the observation, without an assumed cause?', [['dark','LED dark','This reports what was seen.'],['reversed','LED reversed','This is a proposed cause needing polarity evidence.'],['broken','Switch broken','This is a hypothesis, not the displayed observation.']],'dark','Record the symptom before assuming a cause.','diagnosis'),nodes('test','With cells removed and S1 ON, which points test the switch candidate?',['S1.1','S1.2'],'Test S1 contacts directly; holder voltage was already checked.','diagnosis')]);break
    case '8.4': {const corrected=v%2===0;put(rows([['Same endpoint test, cells removed','Reading'],['Before modeled repair','No continuity'],['After modeled repair',corrected?'Continuity':'No continuity']]),'The same intended connection was tested before and after a simulated repair. Interpret what changed.',[choice('inference','What does the comparison support?', [['fixed','The modeled connection changed from open to connected','This requires the same test to have changed as predicted.'],['unresolved','The connection remains unresolved by this repair','This follows if the repeated result remains open.'],['all','Every fault on the board is now fixed','One path test cannot establish the entire board.']],corrected?'fixed':'unresolved','A repeated relevant test supports only the condition it actually checks.','diagnosis'),choice('record','Which setup belongs in a useful repair record?', [['same','Power state, mode, endpoints and both readings','These make the comparison interpretable.'],['name','Only “repair successful”','That hides the test and its evidence.'],['light','Only the LED appearance','That is a different observation and does not compare this connection test.']],'same','Preserve the test setup, before/after observation and remaining uncertainty.','evidence')]);break}
    case '9.4': put(rows([['Evidence available','Scope'],['Calculation','Supplied hypothetical voltages'],['ERC/DRC','Configured file checks passed'],['Output inspection','Matching layers and holes reviewed'],['Physical build','Not performed']]),'Choose claims limited to the evidence available.',[choice('files','Which file claim is supported?', [['checked','The configured checks and output comparison passed','This matches the supplied file evidence.'],['physical','The assembled board’s current was verified','No physical board was measured.'],['universal','The design is guaranteed for every LED','The evidence has stated parts/assumptions and checks.']],'checked','File checks establish their checked scope, not physical guarantees.','evidence'),choice('current','Which current claim is supported?', [['modeled','Current was estimated under the supplied assumptions','That is the calculation’s scope.'],['measured','Actual current was measured','No physical measurement is present.'],['exact','Current is exactly fixed by typical LED voltage','Typical conditions do not guarantee this operating point.']],'modeled','Keep estimates, simulations and physical observations distinct.','evidence')]);break
    default: if(!id.startsWith('E.'))throw Error(`Missing practice contract for ${id}`)
  }
  if(['3.1','3.6'].includes(id)) t.sources=[...new Set([...t.sources,'B3' as SourceId])]
  changedCase(t,v)
  if(finalCase)transferCase(t,v)
  explainCalculations(t)
  const extra:Record<string,SourceId[]>={'1.1':['F2'],'1.3':['F1'],'1.5':['M1'],'2.1':['K3'],'2.5':['F3'],'3.2':['B1'],'4.4':['C1'],'5.2':['C1'],'5.6':['C1'],'9.2':['C3'],'8.5':['M2']}
  t.sources=[...new Set([...t.sources,...(extra[id]??[])])]
  if(t.parts.some(p=>p.skillIds.includes('mapping')))t.sources=[...new Set([...t.sources,'K6' as SourceId])]
  // Identical content gets identical exposure identity even if it is requested
  // under a different bank index. Cosmetic order/labels cannot earn fresh proof.
  const signature=JSON.stringify({context:t.context,artifact:{...t.artifact,variant:0,...(id==='3.6'?{target:'rail-test'}:{})},parts:t.parts.map(p=>({id:p.id,prompt:p.prompt,kind:p.kind,expected:p.expected,baseUnit:p.baseUnit,units:p.units,options:p.options?.map(o=>({id:o.id,label:id==='7.4'&&p.id==='photo'?o.id:o.label})).sort((a,b)=>a.id.localeCompare(b.id))}))})
  let hash=2166136261
  for(const char of signature) hash=Math.imul(hash^char.charCodeAt(0),16777619)>>>0
  t.variantId=`problem-${hash.toString(16)}`
  return t
}
function transferCase(t:TaskCase,v:number){
  const part=t.id
  if(part==='9.1'){
    const parameter=v%3;t.artifact={kind:'datasheet',variant:v,rows:[['WP7113YD Rev V.11B','Manufacturer parameter'],['Forward voltage typical','1.95 V'],['Forward voltage maximum','2.4 V'],['Test current IF','10 mA'],['Ambient TA','25 °C']]};t.context='Review a new yellow replacement, WP7113YD. Extract the requested parameter and its own conditions rather than reusing the green LED data.'
    t.parts[0]=number('value',parameter===0?'Extract the yellow part’s typical forward voltage.':parameter===1?'Extract its maximum forward voltage.':'Extract its forward-voltage test current.',parameter===0?1.95:parameter===1?2.4:0.01,parameter===2?'A':'V','Read this part’s own requested column and condition.','datasheet',undefined,0.00001)
    t.parts[1].options![0].label='IF=10 mA, TA=25 °C';t.parts=t.parts.slice(0,3);t.sources=['C4']
  }
  if(part==='9.2'){
    const vs=[3.1,2.95,3.25,2.85,3.05][v],vf=1.95,current=[3,4,5,2,6][v]/1000,r=(vs-vf)/current
    t.artifact=rows([['Final-case assumption','Value'],['Supply',`${vs} V`],['Assumed LED drop',`${vf} V`],['Target',`${current*1000} mA`],['Range supply',`${vs+0.15} V`],['Range LED drop','1.8 V']]);t.context='The yellow part’s 1.95 V value is typical at 10 mA. For this exercise only, assume that drop at the changed target. Calculate, then review the separate supplied range. Neither assumption guarantees actual current.'
    t.parts=[number('resistance','Calculate the nominal resistance.',r,'Ω','Use the final-case supply, assumed LED drop and target in A.','calculation',undefined,0.05),number('range','Calculate the range-case current with that resistor.',(vs+0.15-1.8)/r,'A','Use the range voltages and the nominal resistor.','calculation',undefined,0.00001),number('power','Calculate range-case resistor dissipation.',(vs+0.15-1.8)**2/r,'W','Use the range resistor voltage squared divided by resistance.','calculation',undefined,0.00001),choice('claim','What remains to verify on an actual build?',[['measure','Actual loaded supply, resistor voltage/resistance, current and component limits','This is what the model leaves unverified.'],['exact','Nothing; a typical voltage fixes the target current','Typical test conditions do not fix this operating point.']],'measure','Use actual parts, limits and measurements to check the model.','evidence')];t.sources=['C4','F1','F3']
  }
  if(part==='5.2'){
    const mismatches=v%2?['hole','map']:['pitch','hole'];t.artifact={kind:'footprint',variant:v,rows:[['Geometry','WP7113YD / selected-symbol reference','Candidate'],['Pitch','2.54 mm',mismatches.includes('pitch')?`${[2.2,2.54,3.1,2.54,2.8][v]} mm`:'2.54 mm'],['Recommended holes','0.9 mm',`${[0.6,0.7,0.65,0.75,0.8][v]} mm`],['Selected symbol map','Pin 1: cathode (K) / pin 2: anode (A)',mismatches.includes('map')?'Pin 1: anode (A) / pin 2: cathode (K)':'Pin 1: cathode (K) / pin 2: anode (A)']]};t.context='Review the new yellow LED drawing against a candidate with two discrepancies. Check every row, including polarity.'
    t.parts=[number('pitch','Extract the replacement drawing pitch.',2.54,'mm','Use the physical drawing reference, not the candidate.','footprint',['mm'],0.001),nodes('differences','Select every candidate feature that conflicts with its reference.',mismatches,'Compare each row independently; this candidate has two discrepancies.','footprint',['pitch','hole','map'].map(x=>({id:x,label:{pitch:'Lead pitch',hole:'Hole diameter',map:'Pad/polarity mapping'}[x]!,feedback:''})))];t.sources=['C4','K6','K4']
  }
  if(part==='6.2'){
    t.artifact={kind:'package',variant:v,fault:'multiple',target:project.pads[v+2].id};t.context='The final package has more than one mismatch. Inspect silkscreen and drills against the approved reference; a complete manifest alone is insufficient.'
    t.parts=[choice('layer','Which inspection combination finds the displayed discrepancies?',[['both','Silkscreen and drill overlay','Inspect both printed information and actual hole centers.'],['silk','Silkscreen only','This misses the displaced hole.'],['drill','Drills only','This misses the assembly mark.']],'both','Both independent outputs differ from their reference.','outputs'),choice('finding','Which complete finding matches the inspected content?',[['both',`D1 K is absent and ${t.artifact.target} hole is displaced`,'This reports both discrepancies.'],['mark','Only the K mark is absent','A hole mismatch also remains.'],['hole','Only a hole is displaced','The required mark is also absent.']],'both','Correct both affected outputs and reinspect the regenerated package.','outputs'),release()];t.sources=['K5']
  }
  if(part==='8.5'){
    const r=[180,270,390,240,330][v],intact=v%2===0,pair=['R1.1','R1.2'];t.context=`New candidates: R1 is internally open, or D1 is reversed with R1 intact. R1 is specified as ${r} Ω in this model. With cells removed there is no parallel path around it. Select a resistance test and predict both outcomes.`
    t.artifact={kind:'circuit',variant:v,target:pair.join('|'),observation:intact?`Resistance reading: ${r} Ω.`:'Resistance reading: OL / open in the stated model.',retestObservation:`Simulated correction/inspection complete. Cells removed; resistance mode; same R1 endpoints now read ${r} Ω. D1 mapping was inspected against the reference. No powered trial performed.`};t.revealAfter=5;t.retestAfter=9
    t.parts=[power(),choice('mode','Choose a mode for this known resistor test.',[['resistance','Resistance / Ω','This compares the resistor with its stated resistance.'],['continuity','Continuity beep only','A known resistor may exceed an unspecified beep threshold; read resistance instead.'],['current','DC current','This is an unpowered component-resistance test.']],'resistance','Read resistance with the source removed and the stated isolated topology; follow the exact meter manual.','measurement'),nodes('points','Select the resistor test endpoints.',pair,'Use both R1 ends, not the supply or LED ends.'),choice('predict-open','Predict the internally open resistor reading.',[['open','OL / open','This is the modeled open resistor.'],['finite',`Approximately ${r} Ω`,'That is the intact candidate.']],'open','The internally open candidate has no finite resistance in this supplied model.','diagnosis'),choice('predict-reversed','Predict R1 reading if only D1 is reversed.',[['open','OL / open','Reversing D1 does not open R1 in this isolated model.'],['finite',`Approximately ${r} Ω`,'R1 remains intact.']],'finite','The intact resistor remains near its stated resistance.','diagnosis'),choice('conclusion','What does the returned resistor reading support?',[['open','Supports the internally open R1 candidate','Use the actual returned reading.'],['intact','Rules out this modeled open R1; LED polarity still needs inspection','The resistor test does not directly measure LED orientation.'],['proved','Proves D1 is reversed','A resistor reading cannot establish polarity.']],intact?'intact':'open','Limit the inference to the tested component and model.','diagnosis'),choice('next','Choose the next inspection/correction.',[['polarity','Inspect D1 mapping against its exact drawing','This follows an intact R1 finding.'],['replace','Correct the open R1 unpowered, then repeat its test','This follows the modeled open reading.'] ],intact?'polarity':'replace','Use the supported result to choose the next action.','diagnosis'),nodes('retest-points','Select the same endpoints for the repeated resistance test.',pair,'Preserve the removed source and repeat the same R1 test.','diagnosis'),choice('retest-predict','Predict a successful repeated R1 test.',[['finite',`Approximately ${r} Ω`,'The intended resistor relationship is restored.'],['open','OL / open','That would remain unresolved.']],'finite','Predict the intact relationship before the repeated result.','diagnosis'),choice('retest-claim','What does the repeated record establish?',[['path','The modeled resistor relationship passes; powered current remains unverified','This stays within the repeated test.'],['all','Every physical fault was fixed','This simulated record is not a test of actual hardware.']],'path','The repeated unpowered component test does not verify a powered operating point.','evidence')];t.sources=['M1','M2','F1']
  }
  if(part==='9.4'){
    const current=[0.004,0.003,0.005,0.006,0.002][v],r=250;t.artifact=rows([['Final evidence record','Scope'],['Model','Estimated current'],['File review','Configured checks and output comparison passed'],['Sample bench log',`Loaded supply recorded; VR=${current*r} V across known 250 Ω`],['Missing check','Visibility in the intended enclosure not tested']]);t.context='Separate a supplied bench-log inference from a remaining use requirement. This is a different evidence record, not your own hardware report.'
    t.parts=[number('current','Infer current from this sample resistor reading.',current,'A','Use the sample resistor voltage divided by its known resistance.','calculation',undefined,0.00001),choice('scope','Which combined claim fits the record?',[['limited','The sample current can be inferred; intended-enclosure visibility remains unverified','The record supports one measurement inference, not the missing use check.'],['complete','Current and intended-enclosure visibility are both verified','No enclosure visibility observation is recorded.'],['none','No current inference is possible','The record contains resistor voltage and known resistance.']],'limited','Report the supported inference and the specifically missing physical-use observation.','evidence')];t.sources=['F1','M1']
  }
}
// Variants change requested evidence or an actual discrepancy, not just wording.
function changedCase(t:TaskCase,v:number){
  const id=t.id,pair=wirePairs[v]
  if(id==='1.1')t.parts.push(nodes('open','Select the two terminals that bound the shown open.',t.artifact.fault==='open-switch'?['S1.1','S1.2']:pair,'Locate the actual gap in the intended path; do not select an intact component.','loop'))
  if(id==='1.4'){
    const x=calcCases[v],vr=x.voltage-x.ledVoltage,factor=[2,3,0.5,4,1.5][v],keys=['half','third','double','quarter','two-thirds'],labels=['Half','One third','Double','One quarter','Two thirds']
    t.artifact=rows([['Fixed condition','Value'],['R1 voltage',`${vr.toFixed(2)} V`],['Original R1',`${x.resistance} Ω`],['Changed R1',`${x.resistance*factor} Ω`]])
    t.parts=[choice('direction','Predict changed current relative to the original.',keys.map((key,i)=>[key,labels[i],'At fixed resistor voltage, current changes inversely with resistance.']),keys[v],`Resistance changes by a factor of ${factor}; current changes by its reciprocal. This assumes fixed resistor voltage.`, 'calculation'),number('current','Calculate the current with the changed R1.',vr/(x.resistance*factor),'A','Use the fixed displayed resistor voltage divided by the new resistance.','calculation',undefined,0.000001)]
  }
  if(id==='1.6'&&v===4){t.artifact.fault=undefined;t.context='Compare this drawing with the intended revision A series circuit. It may match the reference.';t.parts[0].expected='normal';t.parts[0].options!.find(o=>o.id==='normal')!.label='The required series path matches the reference';t.parts[0].explanation='This drawing preserves the required series loop and current-limiting resistor.';t.parts[1].options![0].label='Keep cells removed until all planned pre-power checks are complete';t.parts[1].explanation='The drawing comparison does not replace the remaining physical pre-power inspection.'}
  if(['5.3','5.7'].includes(id)){
    const table=t.artifact.rows!,min=parseFloat(table[1][1]),gapA=v===1||v===4?min+0.04:min-0.02,gapB=v===1||v===2?min-0.03:min+0.08
    table.find(row=>row[0]==='Gap A')![1]=`${gapA.toFixed(2)} mm`;table.find(row=>row[0]==='Gap B')![1]=`${gapB.toFixed(2)} mm`
    const expected=gapA<min?gapB<min?'both':'a':gapB<min?'b':'none'
    t.parts[1]=choice('gap','Which displayed gap violates the required minimum?',[['a','Gap A only','Compare both distances with the actual required minimum.'],['b','Gap B only','Compare both distances with the actual required minimum.'],['both','Both A and B','Compare each distance independently with the minimum.'],['none','Neither displayed gap','A prior report alone does not establish this; inspect the given distances.']],expected,'The violation decision follows the actual gap values and required policy. Keep that separate from the entered rule.','rules')
  }
  if(['2.7','8.2','8.5'].includes(id)){
    t.parts.push(nodes('retest-points','After the modeled unpowered correction, select the same endpoints for the repeated connection test.',pair,'Repeat the original relevant endpoint test; preserve removed cells and continuity mode.','diagnosis'),choice('retest-predict','Predict the repeated connection test after a successful correction.',[['closed','Continuity','The corrected intended connection should now be intact.'],['open','No continuity','A successful correction must satisfy the intended connection.']],'closed','State the predicted repaired relationship before viewing the repeated result.','diagnosis'))
    t.retestAfter=9;t.artifact.retestObservation='Simulated correction log: cells remain removed; continuity mode; same selected endpoints return continuity. LED polarity was inspected against the reference and corrected if needed. No powered trial has been performed.'
    t.parts.push(choice('retest-claim','What does this repeated record establish?',[['path','This modeled connection passes the repeated test; powered current still needs its own check','The repeated test addresses a defined connection.'],['all','Every physical fault has been fixed','A simulated connection log does not verify an actual board.'],['current','The target current was physically measured','This is an unpowered connection test, not a current measurement.']],'path','Keep the repair evidence limited to the simulated repeated test and recorded inspection.','evidence'))
  }
  if(id==='0.3'){t.context=`Cells are removed. Verify the intended ${pair.join(' ↔ ')} connection, rather than its powered voltage.`}
  if(id==='0.4'){
    const fault=['Unplanned VCC–GND wire','D1 polarity disagrees with reference','Required SW connection missing','Unplanned VCC–GND wire','D1 polarity disagrees with reference'][v]
    t.artifact=rows([['Check','Observation'],['Power','Cells absent'],['Finding',fault],['S1','ON']]);t.context='Review this pre-power log against the intended series path. Locate the endpoints involved in its finding.'
    const ends=v%3===0?['BT1+','BT1-']:v%3===1?['D1.1','D1.2']:['S1.2','R1.1']
    t.parts[0].options![0].label='Keep cells out and investigate the finding';t.parts[0].explanation='Resolve the indicated discrepancy with the source removed before power.'
    t.parts[0].options!.forEach(o=>o.feedback='Resolve the indicated discrepancy with the cells removed before any powered trial.')
    t.parts[1]=nodes('supply','Mark the endpoints involved in the reported finding.',ends,'Locate the points in the reference that bound the indicated connection/component.','loop')
  }
  if(['2.1','4.4'].includes(id)){
    const leftK=v%2===0,net=v%3===0?'GND':'LED_A'
    t.artifact={kind:'footprint',variant:v,rows:[['Physical pad position','Selected symbol pin','Required net'],['Left',leftK?'1 / K':'2 / A',leftK?'GND':'LED_A'],['Right',leftK?'2 / A':'1 / K',leftK?'LED_A':'GND'],['Candidate A left/right nets','',v%3===0?'LED_A / GND':'GND / LED_A'],['Candidate B left/right nets','',v%3===0?'GND / LED_A':'LED_A / GND']]}
    const aCorrect=(v%3!==0)===leftK
    t.context='Use the physical pad positions and the selected KiCad LED mapping (1 K, 2 A). Choose the candidate whose complete net assignment agrees with the reference.'
    t.parts[0]=choice('candidate','Which candidate has the required physical-to-net mapping?',[['a','Candidate A','Compare both pad assignments with the reference.'],['b','Candidate B','Compare both pad assignments with the reference.'],['c','Both candidates','The candidates assign opposite nets.']],aCorrect?'a':'b','Both physical positions must agree with the symbol polarity and net.','mapping')
    t.parts[1]=choice('position',`Which physical pad position must connect to ${net}?`,[['left','Left','Compare that pad’s selected symbol pin and net.'],['right','Right','Compare that pad’s selected symbol pin and net.']],(net==='GND')===leftK?'left':'right','Identify the physical position from the full pin/pad/net mapping.','mapping')
  }
  if(['2.6','4.2'].includes(id)){
    const off=v%2===1
    t.context=`The illustrative switch closes 1–2 in ON and 1–3 in OFF. For this changed wiring case, the branch must conduct in ${off?'OFF':'ON'}. This varies the task requirement; revision A uses ON. Exact switch selection remains unresolved.`
    t.parts[0]=nodes('contacts','Select the contacts for the requested conducting position.',['S1.1',off?'S1.3':'S1.2'],'Use common and the contact reached in the requested position.','mapping',[1,2,3].map(x=>({id:`S1.${x}`,label:`S1 pin ${x}`,feedback:''})))
  }
  if(id==='4.1'){
    const correct=['current','archive','mixed'][v%3],rev=['A','B','C','D','E'][v]
    t.artifact={kind:'files',variant:v,rows:[['Folder','Schematic','PCB'],...['current','archive','mixed'].map(x=>[x,x===correct?rev:'prior',x===correct?rev:x==='mixed'?rev:'prior'])]};t.context=`Find the matching ${rev} project artifacts, then order project creation. Check the inventory rather than trusting the folder label.`
    t.parts[0]=choice('folder',`Which folder has the intended matching ${rev} pair?`,['current','archive','mixed'].map(x=>[x,x,'Compare both artifact revisions with the intended revision.']),correct,'The intended revision must match in both artifacts.','workflow')
  }
  if(id==='4.5'){
    const ends=wirePairs[v===4?0:v];t.artifact={kind:'rules',variant:v,rows:[['ERC finding','Reference intent'],[`${ends[0]} disconnected`,`Required connection to ${ends[1]}`],['S1.3 unused','Deliberately separate']]}
    t.parts[0]=nodes('required','Select the required connection that resolves this finding.',ends,'Follow the required reference net; no-connect cannot repair a required connection.','schematic')
  }
  if(id==='4.6'){
    const fault=['reversed-led','bypass','open-wire','open-wire','reversed-led'][v];t.artifact={kind:'circuit',variant:v,fault,target:pair.join('|')};t.context='The configured report is clear. Compare the actual circuit connectivity/polarity against revision A.'
    t.parts[0]=choice('finding','Which functional relationship conflicts with the reference?',[['led','D1 polarity is reversed','Compare the diode bar with the reference nets.'],['r','R1 is bypassed','Trace whether another path joins both resistor ends.'],['open','An intended wire is open','Trace each required series connection.']],fault==='reversed-led'?'led':fault==='bypass'?'r':'open','A rule report cannot replace this functional circuit comparison.','schematic')
  }
  if(id==='5.2'){
    const fault=['hole','pitch','map','hole','pitch'][v],pitch=v===4?'3.0':'2.0',hole=v===3?'0.6':'0.7'
    t.artifact={kind:'footprint',variant:v,rows:[['Geometry','WP7113ID drawing/reference','Candidate'],['Pitch','2.54 mm',fault==='pitch'?`${pitch} mm`:'2.54 mm'],['Recommended holes','0.9 mm',fault==='hole'?`${hole} mm`:'0.9 mm'],['Selected symbol map','Pin 1: cathode (K) / pin 2: anode (A)',fault==='map'?'Pin 1: anode (A) / pin 2: cathode (K)':'Pin 1: cathode (K) / pin 2: anode (A)']]}
    t.parts[1]=choice('difference','Which candidate feature conflicts with its reference?',[['hole','Hole diameter','Compare the recommended hole and actual candidate.'],['pitch','Lead pitch','Compare both pitch values.'],['map','Pad/polarity map','Compare both numbered polarity assignments.']],fault,'Resolve the specific discrepancy before checking actual lead and fabrication tolerances.','footprint')
  }
  if(id==='5.4'){
    t.artifact.target=String(v%3);t.context='Inspect the holder envelope, switch candidates and board boundary. Find a placement with actuator access and its body inside the board.'
    const good=['b','c','a'][v%3];t.parts[0]=choice('place','Choose a usable switch placement.',['a','b','c'].map(x=>[x,`Candidate ${x.toUpperCase()}`,'Check both actuator access and the complete body boundary.']),good,'The selected body has access and stays inside this illustrative outline; verify exact physical dimensions separately.','layout')
  }
  if(id==='5.8'){
    const fault=['polarity','missing-mark','unrouted','polarity','unrouted'][v];t.artifact={kind:'board',variant:v,fault,target:wirePairs[v===4?0:v].join('|')};t.context='Compare copper and silkscreen against revision A; inspect the layers before release.'
    t.parts[0]=choice('finding','Which discrepancy needs correction?',[['mark','K mark beside the wrong pad','Compare the mark with D1.1/K.'],['absent','K mark absent','Inspect the silkscreen for the required mark.'],['route','A required copper route is absent','Trace the reference connections in copper.']],fault==='polarity'?'mark':fault==='missing-mark'?'absent':'route','Resolve the actual discrepancy and regenerate/reinspect affected outputs.','mapping')
  }
  if(['6.1','6.4','9.3'].includes(id)){
    const stale=['drill','copper','bom','drill','copper'][v],rev=['A','B','C','D','E'][v]
    t.artifact={kind:'files',variant:v,rows:[['Artifact','Inspected revision'],['Approved source',rev],['Copper Gerbers',stale==='copper'?'prior':rev],['Drill data',stale==='drill'?'prior':rev],['BOM',stale==='bom'?'prior':rev]]};t.context=`Identify the stale artifact against approved revision ${rev}. These are exercise files; renaming does not update their geometry or part inventory.`
    t.parts[0]=choice('stale','Which output needs regeneration?',[['drill','Drill data','Compare the actual revision with the approved source.'],['copper','Copper Gerbers','Compare the actual revision with the approved source.'],['bom','BOM','Compare the actual revision with the approved source.']],stale,'Regenerate the discrepant artifact from the approved source and inspect a matching package.','outputs')
  }
  if(['6.3','7.1'].includes(id)){
    const target=project.pads[v].id;t.artifact.target=target;t.parts[0]=nodes('hole','Select the reference pad whose expected hole is missing.',[target],'Compare actual hole centers with the approved geometry.','footprint')
  }
  if(id==='7.3'){
    const target=v%2?'R1':'D1',pin=v%2?'R1.2':'D1.1';t.context=target==='D1'?'Before making a D1 joint, verify cathode mapping, then order the process.':'Before making an R1 output joint, identify its LED_A connection, then order the process.'
    t.parts[0]=nodes('orientation',target==='D1'?'Select the intended cathode pad.':'Select the resistor terminal on LED_A.',[pin],'Find the selected terminal from the reference connections.','mapping')
  }
  if(id==='7.4'){
    const ids=['bridge','wetting','good'];t.parts[0].options=ids.map((_,i)=>({id:ids[(i+v)%3],label:`Photo ${String.fromCharCode(65+i)}`,feedback:'Inspect the pad gap and the lead/pad contact in this photograph.'}))
  }
  if(id==='7.5'){
    const wrong=['ab','cd','ef'][v%3],names=['A–B','C–D','E–F'];t.artifact=rows([['Unpowered path','Intended relationship','Observation'],...names.map((name,i)=>[name,i===1?'No intended or alternate route':'Intended wire intact',i===1?(wrong==='cd'?'Continuity':'No continuity'):wrong===['ab','cd','ef'][i]?'No continuity':'Continuity'])]);t.context='Cells are removed; the supplied model has no parallel paths. Find the observation that conflicts with the intended relationship.'
    t.parts[0]=choice('unexpected','Which observation conflicts with this model?',['ab','cd','ef'].map((x,i)=>[x,names[i],'Compare the observed path with its specific intended relationship.']),wrong,'Investigate this conflicting path under the stated isolated model.','measurement')
  }
  if(id==='3.6'){
    const connected=v%2===1;t.revealAfter=4;t.artifact.observation=connected?'Continuity across the selected segments. A jumper joins the segments in this supplied model.':'No continuity across the selected segments. No jumper joins them in this supplied model.'
    t.context='Candidates for a dark LED: an unconnected midpoint rail or reversed D1. Supply was checked. A jumper may join the rail segments outside this cropped view. Define an unpowered connection test and prediction before seeing its reading.'
    t.parts=[power(),mode(),nodes('rail','Select endpoints on opposite sides of the midpoint.',['rail-top','rail-bottom'],'Bound the suspected midpoint; two points on one segment do not test it.','breadboard',[{id:'rail-top',label:'Upper rail endpoint',feedback:''},{id:'rail-bottom',label:'Lower rail endpoint',feedback:''},{id:'rail-upper-mid',label:'Upper segment middle',feedback:''}]),choice('prediction','What does an unconnected midpoint predict?',[['open','No continuity','There is no path across the midpoint.'],['closed','Continuity','An unconnected midpoint cannot supply this path.']],'open','Predict the connection result for the rail hypothesis before measuring.','diagnosis'),choice('result','What does the returned rail test support?',[['open','The midpoint connection is open; correct the intended net unpowered and retest','Use the specific returned connection reading.'],['intact','The modeled rail connection is intact; inspect polarity next','An intact rail rules out this open there, not every other fault.'],['proved','D1 polarity is now proved','This path test does not measure LED orientation.']],connected?'intact':'open','Use the result to update this connection hypothesis and choose the next relevant inspection.','diagnosis')]
  }
  if(id==='3.3')t.artifact.caption=`Modeled meter display: −${calcCases[v].voltage} V. Red probe BT1−; black probe BT1+; DC voltage mode after a passed pre-power inspection.`
  if(id==='6.2'&&v===3){t.artifact.target='R1.1';t.parts[1].options!.find(o=>o.id==='hole')!.label='R1.1 hole center is displaced'}
  if(id==='6.2'&&v===4){t.artifact.fault='missing-switchmark';t.parts[1].options!.find(o=>o.id==='mark')!.label='S1 ON assembly label is absent'}
  if(id==='9.1'){t.artifact.rows!.push(['Lead pitch','2.54 mm'],['Recommended holes','0.9 mm']);t.parts.push(number('geometry',v%2===0?'Extract the replacement drawing’s lead pitch.':'Extract its recommended hole diameter.',v%2===0?2.54:0.9,'mm','Keep pitch and hole diameter distinct; read the requested drawing feature.','footprint',['mm'],0.001))}
  if(id==='9.4'&&v>=2){
    const clear=v===3;t.artifact.rows!.find(row=>row[0]==='ERC/DRC')![1]=clear?'Configured checks passed':'DRC has unresolved clearance findings'
    t.parts[0]=choice('files','Which file claim is supported?',[['checked','Configured checks and output comparison passed','This needs both stated checks to have passed.'],['unresolved','Output comparison was performed; file approval still has an unresolved check','A remaining DRC finding limits this claim.'],['physical','The actual assembled current was verified','A file report alone is not a physical current measurement.']],clear?'checked':'unresolved','Keep the claim within the actual configured-check and inspection record.','evidence')
  }
  if(id==='8.1'){
    const pair=wirePairs[v];t.artifact=rows([['Available evidence','Result'],['Observation','LED dark'],['Supply sample','3.0 V'],['Candidate 1',`Open at ${pair.join(' ↔ ')}`],['Candidate 2','Reversed D1']]);t.context='Separate the symptom from possible causes. Select a direct unpowered test of the indicated open-connection candidate.';t.parts[1]=nodes('test','Which endpoints directly test that candidate?',pair,'Select the connection proposed to be open, with cells removed and S1 ON for a contact test.','diagnosis')
  }
  if(id==='9.4'){
    const measured=v%2===1,i=[4,5,6,3,2][v];t.artifact=rows([['Evidence available','Scope'],['Calculation','Supplied assumptions'],['ERC/DRC','Configured file checks passed'],['Output inspection','Matching layers and holes reviewed'],['Physical work',measured?`Supplied bench log: VR=${(i*.2).toFixed(1)} V; R=200 Ω; current inferred`:'Not performed']]);t.context='Choose claims limited to the supplied record. A bench-log example is separate from your own physical work.'
    t.parts[1]=choice('current','Which current claim is supported?',[['modeled','Current was estimated under hypothetical assumptions only','This is appropriate when no physical observation is recorded.'],['measured','A sample physical current was inferred from measured resistor voltage and stated resistance','This needs the displayed bench-log evidence.'],['exact','Current is fixed exactly by typical LED voltage','Typical does not guarantee a physical operating point.']],measured?'measured':'modeled','Keep model estimates and the supplied bench-log inference distinct from your own hardware evidence.','evidence')
  }
}
export const unitTaskIds=[['0.2','0.3','0.4'],['1.1','1.5','1.6'],['2.2','2.4','2.5'],['3.1','3.4','1.3'],['4.3','4.4','4.6'],['5.5','5.7','2.2'],['6.2','6.4','4.4'],['7.4','7.5','0.4'],['8.5','8.3','7.5'],['9.1','9.2','9.3']]
export const finalTaskIds=['9.1','9.2','5.2','6.2','8.5','9.4']
export function activityTasks(id:string):string[] {return id==='final'?finalTaskIds:id==='unit-basics'?['E.3','E.6','E.9']:id.startsWith('unit-')?unitTaskIds[Number(id.slice(5))]:id.startsWith('review:')?[reviewTaskFor(id.slice(7))]:[id]}
export function reviewTaskFor(skill:string):string {return ({components:'E.5',transistors:'E.6',workflow:'0.1',safety:'0.2',loop:'1.1',units:'1.3',calculation:'1.5',datasheet:'2.2',mapping:'4.4',breadboard:'3.1',measurement:'3.3',schematic:'4.3',footprint:'5.2',rules:'5.7',layout:'5.5',outputs:'6.2',assembly:'7.4',diagnosis:'8.5',evidence:'9.4'} as Record<string,string>)[skill]??'1.5'}
