// Revisions made after reviewing every lesson against the worked example and
// checking whether the alternatives represent plausible learner mistakes.
export type PracticeEdit = {
  prompt?: string
  options?: [string, string, string]
  correct?: number
  why?: string
}

export const lessonPracticeEdits: Record<string, PracticeEdit> = {
  '0.3': { options: ['Use DC voltage mode between those two points with the cells removed', 'A meter in continuity mode between the jumper and LED lead', 'Use continuity mode between the holder terminals instead of the suspected path'] },
  '1.1': { prompt: 'The switch is closed, but one LED lead has lifted out of its breadboard row. The holder still measures voltage. What happens to loop current?', options: ['The lifted lead opens the path, so loop current stops while the holder can retain voltage', 'The holder voltage must vanish whenever a lead lifts', 'Current continues through the LED because the switch is closed'], why: 'A loose lead is another kind of open circuit. The switch may be closed and the battery may still have voltage, but the broken series path stops loop current.' },
  '1.2': { prompt: 'You need the voltage across the LED, not the supply or the resistor. Where should the two voltage probes go?', options: ['One on each LED terminal', 'One on each battery terminal, because the LED is in the same loop', 'One on each resistor terminal, because the same current flows through both parts'], why: 'Voltage compares two chosen points. Probing both ends of the LED measures its voltage; the same series current does not make the resistor and LED voltages equal.' },
  '1.4': { prompt: 'A resistor changes from 300 Ω to 150 Ω while the voltage across it stays fixed. What happens to its current?', options: ['It halves because the resistance value is smaller', 'It doubles because the resistance is halved', 'It stays fixed because the voltage is unchanged'], why: 'I = V/R. At a fixed resistor voltage, halving R doubles I; this says nothing about how the LED voltage might change in a real circuit.' },
  '1.6': { options: ['The jumper may remove current limiting from the LED', 'The resistor still limits current because it remains soldered in place', 'The open switch will protect the LED even after it is closed'] },
  '2.3': { options: ['Increase current to the LED’s absolute maximum because it is a recommended target', 'Compare visibility tests with the exact LED limits and resistor power', 'Keep the target unchanged because brightness is unrelated to current'] },
  '2.6': { options: ['Which physical pins connect in each switch position and how they map to the symbol', 'Which two pads sit closest together in the footprint drawing', 'Whether a three-pin symbol is available, without checking which contacts close'] },
  '3.2': { options: ['Check the row connections against the schematic with cells absent', 'Check only the LED-to-resistor jumper because the other parts already look placed', 'Trust matching row labels without checking which holes share an internal strip'] },
  '3.3': { prompt: 'You put the black probe on the holder’s + contact and the red probe on its − contact in DC voltage mode. What sign should a normally installed pack show?', options: ['A negative sign, because red is at lower potential than black', 'A positive sign, because the cells themselves are installed normally', 'No sign, because reversing probes cancels the voltage'], why: 'A DC voltmeter reports the red-probe potential relative to black. With red on − and black on +, the displayed value is negative even if the cells are installed correctly.' },
  '3.5': { prompt: 'Your model used a 3.0 V supply, but the holder measures 2.5 V while the LED is on. What should you do before changing the resistor?', options: ['Recalculate using the measured supply and a plausible LED-voltage range', 'Keep 3.0 V in the calculation because that is the pack’s nominal rating', 'Raise the assumed LED voltage until the original current prediction fits'], why: 'Use the measured loaded supply and a defensible LED range. Changing a part to rescue a prediction before revisiting its assumptions can hide the real cause.' },
  '3.4': { prompt: 'You measure 0.9 V across a known 300 Ω series resistor. What branch current does this imply?', options: ['3 mA', '0.3 mA', '30 mA'], why: 'I = V/R = 0.9 V / 300 Ω = 0.003 A = 3 mA. This uses the voltage across the resistor, not the whole supply.' },
  '4.1': { options: ['Which schematic and board belong to the intended project revision', 'Which file has the latest modification time, even if the other file is from another folder', 'Which folder has a matching project name, without opening its schematic and board'] },
  '4.2': { options: ['Map the symbol pins to the actual switch operation before using it', 'Choose a three-pin symbol and assume the middle pin is the common contact', 'Swap PCB pad labels later while leaving the schematic mapping unexplained'] },
  '4.3': { options: ['Add a junction or redraw the connection, then highlight the net again', 'Accept the drawing because the two lines visibly cross, then continue to layout', 'Run ERC and treat a pass as proof that these two exact pins share one net'] },
  '4.6': { options: ['LED orientation and the complete intended current path', 'Only whether the switch symbol closes the expected pins', 'Only whether the footprint has a cathode mark, leaving the schematic unchanged'] },
  '5.1': { options: ['Yes, because a visible line touching both pads is a connection on any layer', 'No; route the connection on copper', 'Yes, if a solder-mask opening exposes the printed line'] },
  '5.2': { options: ['Correct the hole size using the exact part drawing and fabrication rules', 'Increase only the surrounding pad diameter and leave the drill unchanged', 'Keep the hole because the 3D model appears to fit the switch'] },
  '5.3': { options: ['Check the current vendor rules and seek comfortable margin or change the layout', 'Use the published minimum as the default width for every track because the vendor lists it', 'Leave the project’s default clearance even though it is below the vendor’s rule'] },
  '5.4': { options: ['Move it where a finger can reach it while keeping clearances', 'Rotate the switch under the holder so its actuator faces the edge', 'Keep the placement because DRC reports no electrical error'] },
  '5.5': { options: ['The net assignment and actual pad-to-track connection', 'Whether changing the nearby silkscreen line makes the connection appear continuous', 'Whether the copper is close enough in the 3D view, regardless of the unrouted count'] },
  '5.6': { options: ['Close the gap on the edge layer and rerun the check', 'Add a silkscreen line over the visible gap but leave the edge geometry', 'Enlarge the nearby copper fill so it overlaps both edge segments'] },
  '5.7': { options: ['Update the rule, rerun DRC, and repair any new violations', 'Keep the old DRC pass and rely on a visual inspection of the gap', 'Increase trace width but leave the project clearance rule unchanged'] },
  '5.8': { options: ['Correct the marking or footprint and regenerate outputs', 'Trust the schematic symbol because DRC passed, even if the board mark misleads assembly', 'Change only the bill of materials while leaving the board mark and pad mapping'] },
  '6.1': { options: ['Export only the copper again because moving a switch cannot affect holes', 'Regenerate drills from the approved revision and inspect the full set', 'Keep the old drill file if its name contains the new revision number'] },
  '6.2': { options: ['Whether the silkscreen layer was exported and the mark is on it', 'Whether the mark is visible in the PCB editor without checking the exported layer', 'Whether regenerating copper files alone restores the missing printed mark'] },
  '6.3': { prompt: 'GerbView shows a rectangular outline, but the fabricator’s preview shows a smaller, cropped board. What should you check before paying?', options: ['The uploaded outline layer, its mapping, and the intended board dimensions', 'The local Gerber view only, because it guarantees the vendor received the same file', 'The quoted shipping cost, because preview dimensions are cosmetic'], why: 'The vendor preview represents the files and layer mapping it received. Resolve the outline and dimension mismatch before ordering.' },
  '6.4': { options: ['Yes, because matching Gerbers and board are enough even if the listed part does not fit', 'No; reconcile the exact part and footprint, then freeze a matching package', 'Yes, if you plan to buy a different LED after the boards arrive'] },
  '7.1': { options: ['Compare the actual lead and hole with the approved footprint and drill output', 'Compare the lead and physical hole only, without checking what the design specified', 'Compare the 3D preview with the board, without the part drawing or drill output'] },
  '7.3': { options: ['Stop and resolve the part-to-pad polarity mismatch before soldering', 'Trust the printed + mark without checking whether the footprint pads are mapped correctly', 'Use a generic short-lead rule without checking the exact part drawing'] },
  '7.4': { options: ['Inspect and remove the bridge, then verify the nets are separate with cells absent', 'Remove the bridge and power the board immediately without an unpowered recheck', 'Rely on the repaired joint’s appearance without checking whether the pads remain connected'] },
  '7.5': { prompt: 'With cells removed, two pads intended to be separate give a continuity beep. What should you check before calling it a solder bridge?', options: ['Trace any legitimate low-resistance path through installed parts, then inspect the pads and wiring', 'Treat every beep between differently named nets as proof of a solder bridge', 'Ignore the beep if the PCB passed DRC before assembly'], why: 'A continuity beep reports a low-resistance path, not its cause. A component or another route may connect the probe points; inspect the circuit and the actual board before diagnosing a bridge.' },
  '8.1': { options: ['Measure the holder voltage and inspect the switch state', 'Inspect LED polarity first, without checking either proposed supply or switch cause', 'Replace the battery based on the dark LED alone'] },
  '8.2': { options: ['No continuity between the trace’s intended endpoints', 'No continuity across the switch contacts, even though the suspected trace is elsewhere', 'Continuity between the trace endpoints but no voltage at the empty holder'] },
  '8.4': { options: ['The same unpowered continuity test now shows the intended connection', 'A different test shows the battery voltage is unchanged after repair', 'The repaired joint looks smoother, but its connection is not retested'] },
  '8.5': { prompt: 'A dark LED could be caused by a broken trace between the resistor and LED or by a reversed LED. With cells removed, which test isolates the trace hypothesis?', options: ['Check continuity between the two intended ends of that trace', 'Check only continuity across the switch contacts', 'Measure the empty battery holder’s voltage'], why: 'A direct unpowered continuity check across the suspected trace tests whether its intended endpoints connect. A good trace would shift attention to LED orientation or another cause.' },
  '9.1': { options: ['The resistor calculation and exact package/polarity match', 'Only the resistor calculation if the new LED has the same body diameter', 'Only the footprint if the new LED has a similar advertised brightness'] },
  '9.3': { options: ['Regenerate and inspect outputs after rerunning the design checks', 'Rerun ERC and DRC but keep Gerbers from before the footprint change', 'Regenerate Gerbers but keep the drill file from before the footprint change'] },
  '9.4': { prompt: 'A revised LED design has a source-backed resistor calculation, but its updated board files have not been checked or exported. Which claim fits the evidence?', options: ['The electrical estimate is documented; the board and fabrication package remain unreviewed', 'The design is ready to order because the resistor calculation is complete', 'The revised board will have the calculated current because the datasheet was used'], why: 'The calculation supports a predicted electrical range under stated assumptions. It does not establish that the updated layout, outputs, or physical board are correct.' },
}

// The index is the question's position within its unit (0–2). Each edit must
// test a different decision rather than repeating an earlier check.
export const assessmentPracticeEdits: Record<string, PracticeEdit> = {
  '2-2': { prompt: 'An example circuit has 8 mA through a 150 Ω resistor. About how much power does that resistor dissipate?', options: ['0.0096 W', '0.000053 W', '1.2 W'], correct: 0, why: 'Convert 8 mA to 0.008 A, then calculate I²R = 0.008² × 150 = 0.0096 W. This is a model value; an exact part choice still needs a rating and range check.' },
  '6-1': { prompt: 'The PCB editor shows an LED polarity mark, but that mark is absent from the exported silkscreen. What should you check before sharing the files?', options: ['Whether the LED datasheet uses the same polarity symbol', 'Whether the silkscreen layer and mark were exported, then regenerate and inspect the output', 'Whether the copper layer still contains the LED pads'], why: 'The recipient sees the exported layers, not the editor view. Fix the silkscreen output and inspect the regenerated package.' },
  '7-2': { prompt: 'After assembly, two pads intended to be separate beep in continuity mode with cells removed. What is the best next step?', options: ['Apply power briefly to see if the LED still lights', 'Assume a solder bridge from the beep alone and scrape between the pads', 'Check for a legitimate path through installed parts, then inspect for an unwanted bridge'], correct: 2, why: 'A beep indicates a low-resistance path. Trace the circuit and inspect the board to determine whether that path is expected before making a repair.' },
  '8-2': { prompt: 'The LED is dim. A 200 Ω series resistor has 0.4 V across it. What current does that imply?', options: ['0.2 mA', '2 mA', '20 mA'], why: 'I = V/R = 0.4 V / 200 Ω = 0.002 A = 2 mA. Compare that reading with the design target before changing parts.' },
  '9-1': { prompt: 'For a hypothetical revised LED, assume 3.2 V supply, 2.0 V across the LED, and a 6 mA target. What resistance does this model suggest?', options: ['20 Ω', '120 Ω', '200 Ω'], correct: 2, why: 'The resistor has 1.2 V across it. Divide 1.2 V by 0.006 A to get 200 Ω; real parts need a range and rating check.' },
}
