// Feedback is indexed by the original option order, before options are
// rearranged on screen. A null marks the correct answer.
export type ChoiceFeedback = [string | null, string | null, string | null]

export const lessonChoiceFeedback: Record<string, ChoiceFeedback> = {
  '0.2': ['An OFF switch can leave other parts of the board connected to the cells.', null, 'Continuity mode is for an unpowered circuit; remove the cells first.'],
  '0.3': ['DC voltage mode compares electrical potential; it will not test this unpowered connection.', null, 'Probe the two endpoints of the suspected jumper path, not the holder.'],
  '0.4': ['A possible supply short is a reason to keep the cells out until you know the path.', null, 'A beep reports a low-resistance path; it does not certify that the wiring is safe.'],
  '1.1': [null, 'A loose LED lead does not remove voltage from the holder.', 'A closed switch cannot restore a path broken at the LED lead.'],
  '1.2': [null, 'Battery terminals give supply voltage, which need not equal the LED voltage.', 'The resistor and LED share current in series, but each can have a different voltage.'],
  '1.4': ['The resistance is smaller, so I = V/R gives more current at fixed voltage.', null, 'Fixed voltage does not mean fixed current when resistance changes.'],
  '1.6': [null, 'A parallel jumper can carry current around a resistor even while it remains in place.', 'Closing the switch does not restore the resistor’s current limit if a bypass exists.'],
  '2.1': ['A printed mark can be wrong; compare the exact part and pad mapping before soldering.', null, 'Do not power a part to guess its orientation when the drawing and mark disagree.'],
  '2.2': ['Typical describes a stated test condition; it is not a guarantee at another current.', null, 'The battery label does not make the LED’s typical voltage exact.'],
  '2.3': ['An absolute limit is a boundary, not a recommended brightness target.', null, 'LED brightness can change with current; check it alongside the part limits.'],
  '2.6': [null, 'Pad spacing says where a part fits, not which contacts close in ON.', 'A three-pin symbol still needs its numbered contacts mapped to the physical switch.'],
  '2.7': [null, 'A normal holder reading already makes the battery a less useful first suspect.', 'Bypassing the resistor removes the planned current limit and does not diagnose the fault.'],
  '3.1': [null, 'Do not move wires or probe a powered circuit when an unpowered connection test answers this.', 'Matching printed rail colors do not prove the rail is continuous internally.'],
  '3.2': [null, 'The questionable jumper may affect another connection; trace the whole intended loop.', 'Printed rows are only a guide; confirm the actual shared holes.'],
  '3.3': [null, 'The sign follows probe placement even when the cells are installed normally.', 'Reversing probes changes the sign of a DC reading; it does not erase the voltage.'],
  '3.5': [null, 'Nominal voltage is a label, not the measured supply under this load.', 'Do not adjust an assumption just to preserve a prediction; use part data and readings.'],
  '3.6': [null, 'A holder reading does not tell you whether two rail sections connect.', 'Changing the LED before testing the rail does not isolate the suspected fault.'],
  '4.1': [null, 'A recent timestamp does not show that the schematic and board are a matching revision.', 'A folder name alone cannot establish which design files belong together.'],
  '4.2': [null, 'The middle pin is often common, but confirm this exact switch’s contact drawing.', 'A PCB change without a matching schematic mapping leaves the design inconsistent.'],
  '4.3': [null, 'A visible crossing need not create an electrical junction in KiCad.', 'ERC cannot establish that these particular pins share the intended net.'],
  '4.4': [null, 'Lead fit does not fix the electrical swap between numbered pads.', 'A 3D model change does not alter copper pad numbering.'],
  '4.5': [null, 'ERC checks its configured rules; it does not know your intended LED direction.', 'Rotating a footprint cannot repair an incorrect schematic connection.'],
  '4.6': [null, 'Switch behavior is only one part of the loop; the LED polarity still needs review.', 'The board marking cannot correct an electrically reversed schematic path.'],
  '5.1': ['A line can look connected while belonging only to printed silkscreen.', null, 'A mask opening exposes copper; it does not turn printed ink into a conductor.'],
  '5.2': [null, 'A larger pad does not make its drill hole wide enough for the lead.', 'The 3D view is not a measurement of the manufactured hole.'],
  '5.3': [null, 'A capability minimum is a limit; using it everywhere leaves no margin for variation.', 'Project rules must reflect the chosen fabricator before the DRC result means much.'],
  '5.4': [null, 'An actuator hidden under the holder remains hard to reach after rotation.', 'DRC does not check whether someone can reach the switch.'],
  '5.5': [null, 'Silkscreen does not create the missing copper connection.', 'The unrouted count reflects net connectivity even when a 3D view looks close.'],
  '5.6': [null, 'Silkscreen changes the print, not the shape used to cut the board.', 'Copper fill cannot close a gap in the board edge geometry.'],
  '5.7': [null, 'The old pass tested an incorrect rule; it cannot establish compliance with the vendor rule.', 'Changing width does not correct a clearance setting that is still too small.'],
  '5.8': [null, 'The assembled part may follow the wrong mark even if the schematic is correct.', 'A bill of materials change does not repair a polarity mark or pad mismatch.'],
  '6.1': ['A switch move can affect both copper and hole locations; export a matching set.', null, 'A filename does not change the positions stored in an old drill file.'],
  '6.2': [null, 'The fabricator receives the exported layer, which can differ from the editor view.', 'Copper regeneration will not restore a missing silkscreen mark.'],
  '6.3': [null, 'A local view cannot prove that the same outline reached the vendor.', 'Preview dimensions affect the board you would receive, so resolve them before payment.'],
  '6.4': ['The physical part still has to match the footprint in the board package.', null, 'A later purchase cannot make an incompatible footprint fit the ordered board.'],
  '7.1': [null, 'Those two measurements show a mismatch, but the design files tell where it arose.', 'A rendering alone cannot verify actual lead and drill dimensions.'],
  '7.2': ['Holding a hot iron while rearranging the bench creates a burn risk.', null, 'Clear the workspace and set up the stand before continuing soldering.'],
  '7.3': [null, 'A printed mark may be wrong; reconcile it with the exact part and pad numbers.', 'Generic lead conventions do not resolve a conflict with this part’s own drawing.'],
  '7.4': [null, 'Retest with power absent before deciding the unwanted connection is gone.', 'Appearance alone cannot establish that the two nets are isolated.'],
  '7.5': [null, 'Installed components may make a low-resistance path without a solder bridge.', 'DRC checked a design file before assembly, not this physical connection.'],
  '7.6': [null, 'Unexpected heat is a stop condition even when the LED produces light.', 'Remove power before investigating a part that may be overheating.'],
  '8.1': [null, 'LED polarity is worth checking later, but first test the two stated hypotheses.', 'A dark LED alone does not establish that the battery is weak.'],
  '8.2': [null, 'A switch reading tests the switch, not the specific trace you suspect.', 'Continuity between the trace ends argues against an open trace; an empty holder has no supply reading.'],
  '8.4': [null, 'An unchanged battery reading does not test whether the repaired joint now connects.', 'A smoother joint is a visual clue; repeat the electrical check.'],
  '8.5': [null, 'Switch contacts do not test the suspected resistor-to-LED trace.', 'An empty holder reading does not test the trace or LED orientation.'],
  '9.1': [null, 'Matching body diameter does not establish matching polarity, lead spacing, or voltage range.', 'Similar brightness does not prove the old resistor or footprint remains suitable.'],
  '9.3': [null, 'Old Gerbers still describe the previous footprint despite fresh checks.', 'A footprint change may move holes, so old drills cannot be paired with new Gerbers.'],
  '9.4': [null, 'A resistor calculation cannot verify an unchecked layout or exported package.', 'Datasheet assumptions predict a range; they cannot guarantee current in an untested board.'],
}

export const assessmentChoiceFeedback: Record<string, ChoiceFeedback> = {
  '0-0': [null, 'Switch OFF does not replace an unpowered inspection.', 'Continuity mode must not be used on the powered board.'],
  '0-1': [null, 'Cells present mean the circuit is not safely unpowered for continuity mode.', 'DC voltage mode cannot test a connection with the cells removed.'],
  '0-2': ['A smell is a stop condition even if the LED lights.', 'Remove power before attempting further measurement. ', null],
  '1-0': [null, 'Supply voltage alone does not imply reversed LED polarity.', 'An open series switch blocks current through the resistor.'],
  '1-1': ['This reverses the V/I relationship.', 'Divide 1 V by 0.01 A, which gives one hundred ohms.', null],
  '1-2': [null, 'A direct holder bypass does not include the intended resistor.', 'The jumper can close a path even when the LED is outside it.'],
  '2-0': [null, 'A typical voltage measured at 10 mA is not exact at 4 mA.', 'The new part needs its own datasheet review.'],
  '2-1': [null, 'The nominal label does not replace the loaded reading.', 'A working LED does not make the meter reading wrong.'],
  '2-2': [null, 'This divides current instead of squaring it in I²R.', 'This is far above the result for 8 mA through 150 Ω; check your ampere conversion.'],
  '3-0': [null, 'Color comparison does not explain the electrical difference.', 'Nominal battery voltage is not the measured loaded voltage.'],
  '3-1': [null, 'Some battery voltage may be across the LED; measure the resistor itself.', 'Continuity mode is only for unpowered connection checks.'],
  '3-2': ['A holder reading does not test the suspected rail break.', 'Replacing a part before testing the rail does not isolate the cause.', null],
  '4-0': [null, 'ERC does not know the physical switch contact arrangement.', 'A label cannot fix the symbol-to-part pin mapping.'],
  '4-1': ['ERC does not check the footprint against the exact physical LED.', 'Text does not change the electrical pad mapping.', null],
  '4-2': [null, 'ERC does not always infer your intended LED direction.', 'A board marking cannot fix schematic wiring.'],
  '5-0': [null, 'DRC cannot test whether a person can access the switch.', 'A shorter label does not move the obstructing part.'],
  '5-1': [null, 'The 3D model is not evidence that a real lead fits a real hole.', 'Rotation does not change the hole diameter.'],
  '5-2': ['Silkscreen cannot complete a copper net.', null, 'The model view does not change the unrouted count.'],
  '6-0': [null, 'The old drill file may contain obsolete hole positions.', 'Renaming a file does not regenerate its hole data.'],
  '6-1': ['The datasheet does not show whether the board mark was exported.', null, 'Copper pads can be present while the printed polarity mark is missing.'],
  '6-2': ['The exported package needs an actual outline.', 'Part data cannot repair a missing outline layer.', null],
  '7-0': [null, 'Light does not establish measured branch current.', 'A lit LED is only one observation, not a complete test.'],
  '7-1': ['Do not apply power before the unpowered short check.', 'DRC cannot detect an assembly bridge or reversed part.', null],
  '7-2': ['Power cannot safely diagnose a possible unintended connection.', 'The beep can arise through another low-resistance path; inspect before repairing.', null],
  '8-0': [null, 'Repeating a normal holder reading does not distinguish switch from LED polarity.', 'Replacing the LED before testing the switch leaves the cause uncertain.'],
  '8-1': [null, 'A brighter LED without the repeated test does not isolate the old open.', 'A printed battery rating does not test the repaired trace.'],
  '8-2': ['0.4 divided by 200 is 0.002 A, not 0.0002 A.', null, 'Convert 0.002 A to 2 mA, not 20 mA.'],
  '9-0': [null, 'CAD checks cannot establish measured physical behavior.', 'A typical datasheet point does not fix the circuit current.'],
  '9-1': ['1.2 V divided by 0.006 A is much larger than 20 Ω.', '120 Ω would give 10 mA at the stated 1.2 V resistor drop.', null],
  '9-2': ['A different lead spacing calls for a footprint review.', 'Bending leads without checking the part and board can hide a mismatch.', null],
}
