import { learningText, labelTerms } from './learningLanguage'
import { useEffect, useRef, useState } from 'react'
import { project } from './teachingProject'
import { lessonArticles } from './lessonArticles'
import { lessonById, sources, type SourceId } from './courseContent'
import { sourceLedger, checkedDate } from './sourceLedger'
import { CircuitView } from './ArtifactView'
import { Icon } from './Icon'
export function SourceLinks({ids}:{ids:SourceId[]}) {return <details className="source-ledger"><summary>Sources, conditions and assumptions</summary>{[...new Set(ids)].map(id=><div key={id}><a href={sources[id].url} target="_blank" rel="noreferrer">{sources[id].title}</a><p>{learningText(sourceLedger[id].section)} · {sourceLedger[id].revision} · Checked {sourceLedger[id].checked ?? checkedDate}</p><p><strong>Supports:</strong> {learningText(sourceLedger[id].supports)}</p><p>{learningText(sourceLedger[id].boundary)}</p></div>)}<p>Problem values, modeled observations, tolerances, design margins and review intervals are stated teaching choices. They are separate from verified source claims.</p></details>}
const terms=[...new Map([...Object.entries(lessonArticles).flatMap(([id,article])=>article.terms.map(([term,meaning])=>({term,meaning,id}))),...labelTerms.map(([term,meaning])=>({term,meaning,id:''}))].map(t=>[t.term.toLowerCase(),t])).values()]
export function ReferencePanel({close}:{close:()=>void}){
  const[tab,setTab]=useState('project'),[search,setSearch]=useState('');const closeRef=useRef<HTMLButtonElement>(null)
  useEffect(()=>{const before=document.activeElement as HTMLElement|null;closeRef.current?.focus();return()=>before?.focus()},[])
  function keys(event:React.KeyboardEvent){if(event.key==='Escape'){event.preventDefault();close()}if(event.key==='Tab'){const nodes=[...event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled), input, select, a[href], summary')].filter(node=>node.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}}
  return <div className="reference-backdrop"><section className="reference-panel" role="dialog" aria-modal="true" aria-labelledby="reference-title" onKeyDown={keys}><header><h2 id="reference-title">Reference</h2><button ref={closeRef} type="button" className="icon-button" aria-label="Close reference" onClick={close}><Icon name="close"/></button></header><nav aria-label="Reference sections">{[['project','Project'],['glossary','Glossary'],['meter','Units and meter'],['sources','Sources']].map(([id,label])=><button type="button" key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {tab==='project'&&<><h3>LED project · revision A</h3><p>{project.status}</p><CircuitView artifact={{kind:'circuit',variant:0}}/><h3>Drawing labels</h3><dl className="reading-terms">{labelTerms.slice(0,11).map(([term,meaning])=><div key={term}><dt>{term}</dt><dd>{meaning}</dd></div>)}</dl><h3>Connections</h3><table className="teaching-table"><thead><tr><th>Net</th><th>Terminals</th></tr></thead><tbody>{project.connections.map(([a,b])=><tr key={a}><td>{learningText(project.terminals.find(p=>p.id===a)?.net??'')}</td><td>{learningText(a)} ↔ {learningText(b)}</td></tr>)}</tbody></table><ul>{project.assumptions.map(x=><li key={x}>{learningText(x)}</li>)}</ul><h3>Physical part status</h3><table className="teaching-table"><tbody>{project.bom.map(([ref,part,status])=><tr key={ref}><th>{learningText(ref)}</th><td>{part}</td><td>{learningText(status)}</td></tr>)}</tbody></table><h3>Teaching file inventory</h3><ul>{project.outputs.map(x=><li key={x.file}>{x.role}: {x.file} · A</li>)}</ul><p>Layer models in the exercises are illustrative. Exact parts, a real CAD/build package and physical measurements need their separate checks.</p></>}
    {tab==='glossary'&&<><label className="record-label" htmlFor="glossary-search">Find a term</label><input className="reference-search" id="glossary-search" type="search" value={search} onChange={e=>setSearch(e.target.value)}/><dl className="reading-terms">{terms.filter(t=>`${t.term} ${t.meaning}`.toLowerCase().includes(search.toLowerCase())).map(t=><div key={t.term}><dt>{t.term}</dt><dd>{learningText(t.meaning)}</dd>{t.id&&<small>Lesson {t.id}: {lessonById[t.id].title}</small>}</div>)}</dl></>}
    {tab==='meter'&&<><h3>Conversions and resistor relationships</h3><p>1 A = 1000 mA · 1 kΩ = 1000 Ω · 1 W = 1000 mW.</p><p>For an ohmic resistor: I = V/R, V = IR, R = V/I. Use the voltage across the resistor. P = IV = I²R = V²/R.</p><h3>Measurement setup</h3><ul><li>Direct-current (DC) voltage: one probe on each requested endpoint after a separate pre-power inspection. Follow the exact meter manual for the common (COM) socket, voltage socket and range.</li><li>Continuity: remove cells. A beep threshold is meter-dependent; identify legitimate alternative paths before declaring a short.</li><li>Current mode: a different series measurement. Never place a current-mode meter directly across a battery.</li></ul><SourceLinks ids={['F1','F3','M1','M2']}/></>}
    {tab==='sources'&&<SourceLinks ids={Object.keys(sources) as SourceId[]}/>}
  </section></div>
}
