import { learningText } from './learningLanguage'
import { useEffect, useRef } from 'react'
import { ArtifactView } from './ArtifactView'
import { Icon } from './Icon'
import { answerPresent, gradePart, type Part, type TaskCase } from './taskTypes'
import type { ActivityDraft, Answer } from './learningStore'
function Field({part,answer,change,disabled=false}:{part:Part;answer?:Answer;change:(answer:Answer)=>void;disabled?:boolean}){
  if(part.kind==='number') {const got=answer&&typeof answer!=='string'&&!Array.isArray(answer)?answer:{value:'',unit:part.units![0]};return <div className="answer-number"><label htmlFor={`value-${part.id}`}>Value</label><input id={`value-${part.id}`} aria-label={learningText(part.prompt)+' value'} type="text" inputMode="decimal" value={got.value} disabled={disabled} onChange={e=>change({...got,value:e.target.value})}/><label htmlFor={`unit-${part.id}`}>Unit</label><select id={`unit-${part.id}`} aria-label={learningText(part.prompt)+' unit'} value={got.unit} disabled={disabled} onChange={e=>change({...got,unit:e.target.value})}>{part.units!.map(u=><option key={u}>{u}</option>)}</select></div>}
  if(part.kind==='nodes') {const got=Array.isArray(answer)?answer:[];return <div className="node-options">{part.options!.map(o=><label key={o.id}><input type="checkbox" checked={got.includes(o.id)} disabled={disabled} onChange={()=>change(got.includes(o.id)?got.filter(x=>x!==o.id):[...got,o.id])}/>{learningText(o.label)}</label>)}</div>}
  if(part.kind==='order') {const got=Array.isArray(answer)?answer:part.options!.map(o=>o.id);const move=(i:number,d:number)=>{const next=[...got];[next[i],next[i+d]]=[next[i+d],next[i]];change(next)};return <ol className="sort-list">{got.map((id,i)=><li className="sort-card" key={id}><span className="sort-index">{i+1}</span><span className="sort-copy"><strong>{part.options!.find(o=>o.id===id)?.label && learningText(part.options!.find(o=>o.id===id)!.label)}</strong></span><div className="sort-controls"><button type="button" aria-label={`Move ${part.options!.find(o=>o.id===id)?.label && learningText(part.options!.find(o=>o.id===id)!.label)} up`} disabled={disabled||i===0} onClick={()=>move(i,-1)}><Icon name="up" size={16}/></button><button type="button" aria-label={`Move ${part.options!.find(o=>o.id===id)?.label && learningText(part.options!.find(o=>o.id===id)!.label)} down`} disabled={disabled||i===got.length-1} onClick={()=>move(i,1)}><Icon name="down" size={16}/></button></div></li>)}</ol>}
  return <div className="answer-radio">{part.options!.map(o=><label key={o.id} className={answer===o.id?'selected':''}><input type="radio" name={part.id} value={o.id} checked={answer===o.id} disabled={disabled} onChange={()=>change(o.id)}/><span>{learningText(o.label)}</span></label>)}</div>
}
export function TaskRunner({task,draft,change,submit,advance}:{task:TaskCase;draft:ActivityDraft;change:(patch:Partial<ActivityDraft>)=>void;submit:()=>void;advance:()=>void}){
  const observation=useRef<HTMLDivElement>(null),retest=useRef<HTMLDivElement>(null)
  useEffect(()=>{if(draft.revealed){observation.current?.focus();observation.current?.scrollIntoView({block:'center'})}},[draft.revealed])
  useEffect(()=>{if(draft.retested){retest.current?.focus();retest.current?.scrollIntoView({block:'center'})}},[draft.retested])
  const visible=task.revealAfter&&!draft.revealed?task.parts.slice(0,task.revealAfter):task.retestAfter&&!draft.retested?task.parts.slice(0,task.retestAfter):task.parts
  const grades=visible.map(p=>gradePart(p,draft.answers[p.id]));const ready=visible.every(p=>answerPresent(p,draft.answers[p.id]));const complete=draft.checked&&grades.every(g=>g.correct)&&(!task.revealAfter||draft.revealed)&&(!task.retestAfter||draft.retested)
  const firstNode=visible.find(p=>p.kind==='nodes')
  const changeAnswer=(part:Part,answer:Answer)=>change({answers:{...draft.answers,[part.id]:answer},checked:false,...(task.revealAfter && task.parts.indexOf(part)<task.revealAfter?{revealed:false,retested:false}:task.retestAfter&&task.parts.indexOf(part)<task.retestAfter?{retested:false}:{})})
  const selected=firstNode&&Array.isArray(draft.answers[firstNode.id])?draft.answers[firstNode.id] as string[]:[]
  return <div className="task-runner"><p className="lesson-lead">{learningText(task.context)}</p><ArtifactView task={task} selected={selected} onPoint={firstNode?(id)=>changeAnswer(firstNode,selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]):undefined} resolved={complete&&['unrouted','junction','jumper','edge-gap'].includes(task.artifact.fault??'')}/>
    {firstNode&&<p className="record-help">Select diagram points or use the named checkboxes below. Selected points are outlined.</p>}
    <form onSubmit={e=>{e.preventDefault();if(ready&&!complete)submit()}}>{visible.map((part,i)=><div key={part.id}>
      {task.revealAfter&&i===task.revealAfter&&draft.revealed&&<div ref={observation} tabIndex={-1} className="modeled-observation" role="status"><strong>Modeled observation</strong><p>{learningText(task.artifact.observation??'')}</p><p>Only the submitted safe setup returns this observation. It is not a measurement of your board.</p></div>}
      {task.retestAfter&&i===task.retestAfter&&draft.retested&&<div ref={retest} tabIndex={-1} className="modeled-observation" role="status"><strong>Repeated modeled test</strong><p>{learningText(task.artifact.retestObservation??'')}</p></div>}
      <fieldset className="task-part"><legend><span>{i+1}.</span> {learningText(part.prompt)}</legend><Field part={part} answer={draft.answers[part.id]} change={answer=>changeAnswer(part,answer)}/>{draft.checked&&<div className={`part-feedback ${grades[i].correct?'correct':'incorrect'}`} role="status"><strong>{grades[i].correct?'Supported':'Check this decision'}</strong><p>{learningText(grades[i].feedback)}</p></div>}</fieldset>
    </div>)}<div className="lesson-actions"><span className="record-help">{draft.followup?'Apply the correction to this changed case.':task.revealAfter&&!draft.revealed?'Submit setup and predictions before seeing the result.':'Use the artifact to support each decision.'}</span>{complete?<button type="button" className="primary-button" onClick={advance}>Continue <Icon name="arrow"/></button>:<button type="submit" className="primary-button" disabled={!ready}>{task.revealAfter&&!draft.revealed?'Check test and reveal observation':'Check decisions'}</button>}</div></form>
  </div>
}
